In [110]:
import polars as pl
import spacy

nlp = spacy.load('pt_core_news_lg')

In [115]:
textos = pl.read_parquet('../database/textos/*.parquet').select('id', 'texto')
metadata = pl.read_parquet('../database/metadata/*.parquet')

In [117]:
metadata

shape: (1_262_498, 19)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ numberPage ┆ pubName ┆ name      ┆ artType   ┆ … ┆ highlight ┆ idMateria ┆ highlight ┆ highlight │
│ ---        ┆ ---     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ image     ┆ imagename │
│ str        ┆ str     ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ ---       ┆ ---       │
│            ┆         ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ str       │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 12         ┆ DO1     ┆ PORTARIA  ┆ PORTARIA  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 12         ┆ DO1     ┆ PORTARIA  ┆ PORTARIA  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 12         ┆ DO1     ┆ PORTARIA  ┆ PORTARIA  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 12         ┆ DO1     ┆ PORTARIA  ┆ PORTARIA  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 5          ┆ DO1     ┆ PORTARIA  ┆ PORTARIA  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 58         ┆ DO3     ┆ 2025-12-3 ┆ Extrato   ┆ … ┆           ┆ 23469728  ┆           ┆           │
│            ┆         ┆ 0/1150364 ┆ de Creden ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ 5/COMPRAS ┆ ciamento  ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ NET…      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 58         ┆ DO3     ┆ 2025-12-3 ┆ Extrato   ┆ … ┆           ┆ 23470217  ┆           ┆           │
│            ┆         ┆ 0/1150374 ┆ de Creden ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ 6/COMPRAS ┆ ciamento  ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ NET…      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 58         ┆ DO3     ┆ 2025-12-3 ┆ Extrato   ┆ … ┆           ┆ 23470438  ┆           ┆           │
│            ┆         ┆ 0/1150376 ┆ de Creden ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ 5/COMPRAS ┆ ciamento  ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ NET…      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 58         ┆ DO3     ┆ 2025-12-3 ┆ Extrato   ┆ … ┆           ┆ 23470552  ┆           ┆           │
│            ┆         ┆ 0/1150376 ┆ de Creden ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ 1/COMPRAS ┆ ciamento  ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ NET…      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 58         ┆ DO3     ┆ 2025-12-3 ┆ Extrato   ┆ … ┆           ┆ 23470580  ┆           ┆           │
│            ┆         ┆ 0/1150378 ┆ de Creden ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ 0/COMPRAS ┆ ciamento  ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ NET…      ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [120]:
metadata.filter(pl.col('pubName') == 'DO1').select('id').to_arrow()

pyarrow.Table
id: large_string
----
id: [["12002010442","12002010443","12002010444","12002010445","12002010746",...,"515_20231228_21278593","515_20231229_21287449","515_20231229_21287478","515_20231229_21287605","515_20231229_21288193"]]

In [126]:
textos_atos = textos.filter(
    pl.col('id').is_in(metadata.filter(pl.col('pubName') == 'DO1').select('id').to_series())
)

textos_pessoal = textos.filter(
    pl.col('id').is_in(metadata.filter(pl.col('pubName') == 'DO2').select('id').to_series())
)

textos_contratacoes = textos.filter(
    pl.col('id').is_in(metadata.filter(pl.col('pubName') == 'DO3').select('id').to_series())
)

/var/folders/tp/48888knx3z114kf8p48_0p6w0000gn/T/ipykernel_26846/3028984874.py:1: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  textos_atos = textos.filter(
/var/folders/tp/48888knx3z114kf8p48_0p6w0000gn/T/ipykernel_26846/3028984874.py:5: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  textos_pessoal = textos.filter(
/var/folders/tp/48888knx3z114kf8p48_0p6w0000gn/T/ipykernel_26846/3028984874.py:9: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  textos_contratacoes = textos.filter(

In [133]:
textos_pessoal.filter(pl.col('texto').str.contains('</p>'))

shape: (12_687, 2)
┌───────────────────────┬─────────────────────────────────┐
│ id                    ┆ texto                           │
│ ---                   ┆ ---                             │
│ str                   ┆ str                             │
╞═══════════════════════╪═════════════════════════════════╡
│ 529_20200102_12324586 ┆ </p><p>                         │
│                       ┆ PORTARIA Nº 2, DE 20 D…         │
│ 529_20200102_12326901 ┆ </p><p class="identifica">PORT… │
│ 529_20200102_12326902 ┆ </p><p class="identifica">PORT… │
│ 529_20200102_12326903 ┆ </p><p class="identifica">PORT… │
│ 529_20200102_12326911 ┆ </p><p class="identifica">PORT… │
│ …                     ┆ …                               │
│ 529_20251204_23385368 ┆ PORTARIA DIGER-MD Nº 5.304, de… │
│ 529_20251208_23394076 ┆ PORTARIA Nº 75 - SVP/1-RIO-SSA… │
│ 529_20251208_23394391 ┆ PORTARIA Nº 301/25-SAP.5-SVP 3… │
│ 529_20251209_23398653 ┆ PORTARIA Nº 74 - SVP/1-RIO-SSA… │
│ 529_20251215_23420356 ┆ PORTARIA DIGER-MD Nº 5.588, de… │
└───────────────────────┴─────────────────────────────────┘

In [113]:
nlp(textos.item(0,1)).similarity(nlp(textos.item(100000,1)))

0.9408036470413208

In [114]:
ids = sorted(set(textos.select('id').to_numpy().flatten()))
df = pl.DataFrame(schema=ids)

In [99]:
df

shape: (0, 1_262_482)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ 1020_2019 ┆ 1020_2020 ┆ 1020_2021 ┆ 1020_2022 ┆ … ┆ 701_20230 ┆ 701_20230 ┆ 701_20230 ┆ 701_2023 │
│ 0116_1139 ┆ 0120_1236 ┆ 0423_1345 ┆ 0124_1420 ┆   ┆ 101_20225 ┆ 101_20225 ┆ 101_20225 ┆ 0101_202 │
│ 1945      ┆ 5728      ┆ 6833      ┆ 6301      ┆   ┆ 284.xml   ┆ 288-1.xml ┆ 293-1.xml ┆ 25293-2. │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ xml      │
│ null      ┆ null      ┆ null      ┆ null      ┆   ┆ null      ┆ null      ┆ null      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ null     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
{j:nlp(textos.filter(pl.col('id')==i).item(0,1)).similarity(nlp(textos.filter(pl.col('id')==j)))}

In [107]:
for i in ids:
    for j in ids:
        print({j: nlp(textos.filter(pl.col('id')==i).item(0,1)).similarity(nlp(textos.filter(pl.col('id')==j).item(0,1)))})
        break
    break

{'1020_20190116_11391945': 1.0}

In [109]:
for i in ids:
    data = {'id': i}
    
    for j in ids:
        data.update({j: nlp(textos.filter(pl.col('id')==i).item(0,1)).similarity(nlp(textos.filter(pl.col('id')==j).item(0,1)))})
        
    df = pl.concat(
        [
            df, 
            pl.DataFrame(
                data
            )
        ]
    )
    break

/var/folders/tp/48888knx3z114kf8p48_0p6w0000gn/T/ipykernel_26846/2894412706.py:5: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  data.update({j: nlp(textos.filter(pl.col('id')==i).item(0,1)).similarity(nlp(textos.filter(pl.col('id')==j).item(0,1)))})

KeyboardInterrupt:

In [94]:
textos.filter(pl.col('id')=='530_20210525_13531892').item(0,1)

'EXTRATOS DE TERMOS ADITIVOS\nContratante: UNIÃO - MINISTÉRIO DA DEFESA - COMANDO DO EXÉRCITO - SECRETARIA DE ECONOMIA E FINANÇAS - CNPJ 00.394.452/0284-58. Objeto: Prorrogação de vigência de prestação de serviço de mensalidades do pessoal vinculado ao Comando do Exército. Fundamento legal: Portaria nº 1.271, de 13 de agosto de 2018, do Comandante do Exército; Portaria nº 124-SEF/C Ex, de 18 de fevereiro de 2021; e Edital de Credenciamento nº 01/2017-SEF.\nNúmero do Termo Aditivo: 19-090-01-SEF/CPEx - ADMINISTRAÇÃO DOS COMPOSSUÍDORES DA SQN 103 BLOCO E, CNPJ 02.930.946/0001-82. Data da Assinatura: 13/MAI/21. Vigência: 14/ABR/22.\nNúmero do Termo Aditivo: 19-089-02-SEF/CPEx - ADMINISTRAÇÃO DOS COMPOSSUÍDORES DA SQN 103 BLOCOS D, CNPJ 02.964.553/0001-90. Data da Assinatura: 13/MAI/21. Vigência: 15/ABR/22.\nNúmero do Termo Aditivo: 19-105-02-SEF/CPEx - ADMINISTRAÇÃO DOS COMPOSSUÍDORES DA SQN 306 BLOCOS K, CNPJ 02.982.484/0001-47. Data da Assinatura: 05/ABR/21. Vigência: 15/ABR/22.\nNúmero do Termo Aditivo: 19-112-01-SEF/CPEx - ADMINISTRAÇÃO DOS COMPOSSUÍDORES DA SQS 209 BLOCO I, CNPJ 02.996.108/0001-01. Data da Assinatura: 06/MAI/21. Vigência: 14/ABR/22.'

In [81]:
df = pl.DataFrame({
    "col1": [1, 2, 3],
    "col2": [4, 5, 6]
})

In [ ]:
pl.concat([df, pl.DataFrame({'col1':[4], 'col2':[7], 'col3':[7, 8, 9, 10]})])

In [77]:
df[0,0] = 0

In [78]:
df

shape: (3, 2)
┌──────┬──────┐
│ col1 ┆ col2 │
│ ---  ┆ ---  │
│ i64  ┆ i64  │
╞══════╪══════╡
│ 0    ┆ 4    │
│ 2    ┆ 5    │
│ 3    ┆ 6    │
└──────┴──────┘

In [52]:
nlp(textos.item(0,1))

PORTARIA DAC Nº 1.747/SIE, DE 26 DE DEZEMBRO DE 2001
Autoriza a empresa JET SERVICE COMERCIAL LTDA a executar serviços auxiliares de transporte aéreo nos aeroportos brasileiros.
O CHEFE DO SUBDEPARTAMENTO DE INFRA-ESTRUTURA DO DEPARTAMENTO DE AVIAÇÃO CIVIL, no uso da delegação de competência outorgada pela Portaria DAC Nº 1727/DGAC, de 21 de dezembro de 2001, e de acordo com o art. 1º e 7º da Portaria nº 467/GM-5, de 3 de junho de 1993, e com fundamento no art. 102 da Lei nº 7565, de 19 de dezembro de 1986, que dispõe sobre o Código Brasileiro de Aeronáutica, resolve:
Art. 1º Autorizar a empresa JET SERVICE COMERCIAL LTDA, sediada na cidade de São Paulo, para executar serviços auxiliares de transporte aéreo, nos aeroportos brasileiros, denominados Serviços Operacionais, discriminados no subitem 2.1 da Instrução de Aviação Civil - IAC 2301-0899, aprovada pela Portaria nº 533/DGAC, de 12 de agosto de 1999, publicada no Diário Oficial da União nº 160, de 20 de agosto de 1999.
Art. 2º A empresa ora autorizada se compromete por si e seus prepostos, sob pena de revogação desta Portaria:
a) não transferir seu controle acionário ou parte de seu capital à pessoa física ou jurídica, sem prévia autorização do DAC; e
b) informar, a cada período de 6 meses, o aeroporto onde está operando.
Art. 3º Para operar em qualquer aeroporto brasileiro, a empresa deverá atender às disposições contidas na IAC supracitada.
Art. 4º Esta Portaria entra em vigor na data de sua publicação, no Diário Oficial da União.
Cel. Eng. ALLEMANDER JESUS PEREIRA FILHO

In [62]:
nlp(textos.item(100000,1))

PORTARIA DIRAP Nº 1.400/DPC, DE 31 DE MARÇO DE 2005
O DIRETOR DE ADMINISTRAÇÃO DO PESSOAL, no uso da competência que lhe foi subdelegada pela Portaria nº 033/COMGEP, de 17 de setembro de 1991, em seu artigo 3º, item 13, alínea “a”, resolve:
Tornar sem efeito as nomeações de CARLA WOYCIEKOSKI (COD. VAGA 608879) e LISIANE FREITAS LEAL (COD. VAGA 606314) na Portaria DIRAP nº 696/DPC, de 18 de fevereiro de 2005, publicada no DOU nº 35, Seção 2, de 22 de fevereiro de 2005, para exercerem os cargos de Psicólogo e Técnico de Laboratório, respectivamente, ambos na classe “D”, padrão I, com lotação no Hospital de Aeronáutica de Canoas, por não terem tomado posse dentro do prazo previsto, conforme o artigo 13, § 6º, da Lei nº 8.112, de 11 de dezembro 1990.
Brig.-Ar OSVALDO JOSÉ DE OLIVEIRA

In [44]:
textos

shape: (1_262_498, 2)
┌───────────────────────┬─────────────────────────────────┐
│ id                    ┆ texto                           │
│ ---                   ┆ ---                             │
│ str                   ┆ str                             │
╞═══════════════════════╪═════════════════════════════════╡
│ 12002010442           ┆ PORTARIA DAC Nº 1.747/SIE, DE … │
│ 12002010443           ┆ PORTARIA DAC Nº 1.748/SIE, DE … │
│ 12002010444           ┆ PORTARIA DAC Nº 1.749/SIE, DE … │
│ 12002010445           ┆ PORTARIA Nº 45/DAdM, DE 27 DE … │
│ 12002010746           ┆ PORTARIA INTERMINISTERIAL Nº 2… │
│ …                     ┆ …                               │
│ 530_20251231_23469728 ┆ EXTRATO DE CREDENCIAMENTO Nº 3… │
│ 530_20251231_23470217 ┆ EXTRATO DE CREDENCIAMENTO Nº 3… │
│ 530_20251231_23470438 ┆ EXTRATO DE CREDENCIAMENTO Nº 2… │
│ 530_20251231_23470552 ┆ EXTRATO DE CREDENCIAMENTO Nº 3… │
│ 530_20251231_23470580 ┆ EXTRATO DE CREDENCIAMENTO Nº 3… │
└───────────────────────┴─────────────────────────────────┘