In [81]:
import polars as pl

In [82]:
metadata = pl.read_parquet('../database/metadata/*.parquet')

In [83]:
metadata.describe()

shape: (9, 20)
┌────────────┬───────────┬─────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ numberPag ┆ pubName ┆ name      ┆ … ┆ highlight ┆ idMateria ┆ highlight ┆ highlight │
│ ---        ┆ e         ┆ ---     ┆ ---       ┆   ┆ ---       ┆ ---       ┆ image     ┆ imagename │
│ str        ┆ ---       ┆ str     ┆ str       ┆   ┆ str       ┆ str       ┆ ---       ┆ ---       │
│            ┆ str       ┆         ┆           ┆   ┆           ┆           ┆ str       ┆ str       │
╞════════════╪═══════════╪═════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 1262498   ┆ 1262498 ┆ 1262498   ┆ … ┆ 217717    ┆ 216936    ┆ 145833    ┆ 145833    │
│ null_count ┆ 0         ┆ 0       ┆ 0         ┆ … ┆ 1044781   ┆ 1045562   ┆ 1116665   ┆ 1116665   │
│ mean       ┆ null      ┆ null    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ std        ┆ null      ┆ null    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ min        ┆ 1         ┆ DO1     ┆ # EXTRATO ┆ … ┆           ┆ 10449257  ┆           ┆           │
│            ┆           ┆         ┆ DE 2TA    ┆   ┆           ┆           ┆           ┆           │
│            ┆           ┆         ┆ 004CABW20 ┆   ┆           ┆           ┆           ┆           │
│            ┆           ┆         ┆ 16        ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ null      ┆ null    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%        ┆ null      ┆ null    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%        ┆ null      ┆ null    ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ max        ┆ 99-100-10 ┆ DO3E    ┆ “DECISÃO  ┆ … ┆ tit       ┆ 23634373  ┆ data:imag ┆ 3_MD_1434 │
│            ┆ 1-329     ┆         ┆           ┆   ┆           ┆           ┆ e/jpeg;ba ┆ 4351_001. │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆ se64,/9j/ ┆ jpg       │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆ 4AA…      ┆           │
└────────────┴───────────┴─────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [84]:
metadata = metadata.with_columns(
    id = pl.when(pl.col('id').str.ends_with('.xml')).then(pl.col('id').str.replace('.xml', '')).otherwise(pl.col('id'))
)

In [85]:
print('Quantidade de dados nulos:\n')
for col in metadata.columns:
    print(col, metadata.select(col).null_count().item(), sep=': ')

Quantidade de dados nulos:

numberPage: 0
pubName: 0
name: 0
artType: 0
pubDate: 0
artCategory: 0
pdfPage: 0
editionNumber: 3
id: 0
idOficio: 1044233
artClass: 1044233
artSize: 1044233
artNotes: 1044233
highlightType: 1048586
highlightPriority: 1048586
highlight: 1044781
idMateria: 1045562
highlightimage: 1116665
highlightimagename: 1116665

Por que a quantidade de dados nulos das colunas 'idOficio', 'artClass', 'artSize' e 'artNotes' é a mesma?

Acredito que esteja relacionado com o tempo, no sentido que esses atributos passaram a ser adotados em modelos posteriores das publicações.

- Não é relacionado com o tempo. Temos nulos disstribuídos de 2002 a 2025.
- O atributo que mais parece se relacionar com a ausência desses dados é o pdfPage, porque é distribuído mais uniformemente. Basendo-se nisso, posso imaginar que esses atributos só constem na primeira publicação de determinada página, por exemplo. Assim poderemos interpolar e distribuir esses atributos pelas outras linhas que possuam a mesma pdfPage.
- Não consegui entender o motivo desses dados nulos do idOficio, mas vou tomar a decisão da simplicidade e remover os dados nulos completamente do dataset.

In [86]:
metadata = metadata.select('id', 'numberPage', 'pubName', 'name', 'artType', 'pubDate', 'artCategory', 'pdfPage', 'editionNumber')
metadata

shape: (1_262_498, 9)
┌────────────┬───────────┬─────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ numberPag ┆ pubName ┆ name      ┆ … ┆ pubDate   ┆ artCatego ┆ pdfPage   ┆ editionNu │
│ ---        ┆ e         ┆ ---     ┆ ---       ┆   ┆ ---       ┆ ry        ┆ ---       ┆ mber      │
│ str        ┆ ---       ┆ str     ┆ str       ┆   ┆ str       ┆ ---       ┆ str       ┆ ---       │
│            ┆ str       ┆         ┆           ┆   ┆           ┆ str       ┆           ┆ str       │
╞════════════╪═══════════╪═════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1200201044 ┆ 12        ┆ DO1     ┆ PORTARIA  ┆ … ┆ 04/01/200 ┆ Ministéri ┆ http://pe ┆ 3         │
│ 2          ┆           ┆         ┆           ┆   ┆ 2         ┆ o da Agri ┆ squisa.in ┆           │
│            ┆           ┆         ┆           ┆   ┆           ┆ cultura,/ ┆ .gov.br/i ┆           │
│            ┆           ┆         ┆           ┆   ┆           ┆ Pec…      ┆ mpr…      ┆           │
│ 1200201044 ┆ 12        ┆ DO1     ┆ PORTARIA  ┆ … ┆ 04/01/200 ┆ Ministéri ┆ http://pe ┆ 3         │
│ 3          ┆           ┆         ┆           ┆   ┆ 2         ┆ o da Agri ┆ squisa.in ┆           │
│            ┆           ┆         ┆           ┆   ┆           ┆ cultura,/ ┆ .gov.br/i ┆           │
│            ┆           ┆         ┆           ┆   ┆           ┆ Pec…      ┆ mpr…      ┆           │
│ 1200201044 ┆ 12        ┆ DO1     ┆ PORTARIA  ┆ … ┆ 04/01/200 ┆ Ministéri ┆ http://pe ┆ 3         │
│ 4          ┆           ┆         ┆           ┆   ┆ 2         ┆ o da Agri ┆ squisa.in ┆           │
│            ┆           ┆         ┆           ┆   ┆           ┆ cultura,/ ┆ .gov.br/i ┆           │
│            ┆           ┆         ┆           ┆   ┆           ┆ Pec…      ┆ mpr…      ┆           │
│ 1200201044 ┆ 12        ┆ DO1     ┆ PORTARIA  ┆ … ┆ 04/01/200 ┆ Ministéri ┆ http://pe ┆ 3         │
│ 5          ┆           ┆         ┆           ┆   ┆ 2         ┆ o da Agri ┆ squisa.in ┆           │
│            ┆           ┆         ┆           ┆   ┆           ┆ cultura,/ ┆ .gov.br/i ┆           │
│            ┆           ┆         ┆           ┆   ┆           ┆ Pec…      ┆ mpr…      ┆           │
│ 1200201074 ┆ 5         ┆ DO1     ┆ PORTARIA  ┆ … ┆ 07/01/200 ┆ Ministéri ┆ http://pe ┆ 10.397,DE │
│ 6          ┆           ┆         ┆           ┆   ┆ 2         ┆ o da Defe ┆ squisa.in ┆ 28DEDEZEM │
│            ┆           ┆         ┆           ┆   ┆           ┆ sa/GABINE ┆ .gov.br/i ┆ BRODE2001 │
│            ┆           ┆         ┆           ┆   ┆           ┆ TE …      ┆ mpr…      ┆           │
│ …          ┆ …         ┆ …       ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 530_202512 ┆ 58        ┆ DO3     ┆ 2025-12-3 ┆ … ┆ 31/12/202 ┆ Ministéri ┆ http://pe ┆ 249       │
│ 31_2346972 ┆           ┆         ┆ 0/1150364 ┆   ┆ 5         ┆ o da Defe ┆ squisa.in ┆           │
│ 8          ┆           ┆         ┆ 5/COMPRAS ┆   ┆           ┆ sa/Comand ┆ .gov.br/i ┆           │
│            ┆           ┆         ┆ NET…      ┆   ┆           ┆ o d…      ┆ mpr…      ┆           │
│ 530_202512 ┆ 58        ┆ DO3     ┆ 2025-12-3 ┆ … ┆ 31/12/202 ┆ Ministéri ┆ http://pe ┆ 249       │
│ 31_2347021 ┆           ┆         ┆ 0/1150374 ┆   ┆ 5         ┆ o da Defe ┆ squisa.in ┆           │
│ 7          ┆           ┆         ┆ 6/COMPRAS ┆   ┆           ┆ sa/Comand ┆ .gov.br/i ┆           │
│            ┆           ┆         ┆ NET…      ┆   ┆           ┆ o d…      ┆ mpr…      ┆           │
│ 530_202512 ┆ 58        ┆ DO3     ┆ 2025-12-3 ┆ … ┆ 31/12/202 ┆ Ministéri ┆ http://pe ┆ 249       │
│ 31_2347043 ┆           ┆         ┆ 0/1150376 ┆   ┆ 5         ┆ o da Defe ┆ squisa.in ┆           │
│ 8          ┆           ┆         ┆ 5/COMPRAS ┆   ┆           ┆ sa/Comand ┆ .gov.br/i ┆           │
│            ┆           ┆         ┆ NET…      ┆   ┆           ┆ o d…      ┆ mpr…      ┆           │
│ 530_202512 ┆ 58        ┆ DO3     ┆ 2025-12-3 ┆ … ┆ 31/12/202 ┆ Ministéri ┆ http://pe ┆ 249       │
│ 31_2347055 ┆           ┆         ┆ 0/1150376 ┆   ┆ 5         ┆ o da Defe ┆ squisa.in ┆           │
│ 2          ┆           ┆         ┆ 1/COMPRAS ┆   ┆           ┆ sa/Comand ┆ .gov.br/i ┆           │
│            ┆           ┆         ┆ NET…      ┆   ┆           ┆ o d…      ┆ mpr…      ┆           │
│ 530_202512 ┆ 58        ┆ DO3     ┆ 2025-12-3 ┆ … ┆ 31/12/202 ┆ Ministéri ┆ http://pe ┆ 249       │
│ 31_2347058 ┆           ┆         ┆ 0/1150378 ┆   ┆ 5         ┆ o da Defe ┆ squisa.in ┆           │
│ 0          ┆           ┆         ┆ 0/COMPRAS ┆   ┆           ┆ sa/Comand ┆ .gov.br/i ┆           │
│            ┆           ┆         ┆ NET…      ┆   ┆           ┆ o d…      ┆ mpr…      ┆           │
└────────────┴───────────┴─────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [87]:
metadata = (
    metadata
    .with_columns(
        pl.col('artType').replace(
            {
                'EXTRATO': 'Extrato',
                'EXTRATOS': 'Extrato',
                'AVISO': 'Aviso',
                'AVISOS': 'Aviso',
                'PORTARIA': 'Portaria', 
                'PORTARIAS': 'Portaria', 
                'PREGÃO': 'Pregão',
                'RESULTADO': 'Resultado',
                'RESULTADOS': 'Resultado',
                'RETIFICAÇÃO': 'Retificação',
                'RETIFICAÇÕES': 'Retificação',
                'EDITAL': 'Edital',
                'EDITAIS': 'Edital',
                'DESPACHO': 'Despacho',
                'DESPACHOS': 'Despacho',
                'TOMADA': 'Tomada',
                'ATA': 'Ata',
                'DECISÃO': 'Decisão',
                'PROCESSO': 'Processo',
                'PROCESSOS': 'Processo',
                'CONVITE': 'Convite',
                'RESOLUÇÃO': 'Resolução',
                'CONCORRÊNCIA': 'Concorrência',
                'DECRETO': 'Decreto',
                'LEILÃO': 'Leilão',
                'DELIBERAÇÃO': 'Deliberação',
                'EXPEDIENTE': 'Expediente',
                'ANEXO': 'Anexo',
                'ANEXOS': 'Anexo'
            }
        )
    )
)

In [88]:
metadata = (
    metadata
    .with_columns(
        artCategory = pl.col('artCategory')
        .str.to_uppercase()
        .str.replace('ª', '', literal=True)
        .str.replace('ª', '', literal=True)
        .str.replace('º', '', literal=True)
        .str.replace('º', '', literal=True)
    )
)

In [89]:
MINISTÉRIO DA DEFESA/COMANDO DO EXÉRCITO/COMANDO MILITAR DO NORDESTE/1 GRUPAMENTO DE ENGENHARIA/3º BATALHÃO DE ENGENHARIA DE CONSTRUÇÃO

SyntaxError: invalid syntax (2214526388.py, line 1)

In [ ]:
categorias = (
    metadata
    .group_by('artCategory')
    .agg(pl.col('id').count())
    .sort('id', descending=True)
)