In [40]:
import numpy as np
import polars as pl
from rapidfuzz import fuzz as rapidfuzz_fuzz, process

In [41]:
textos = (
    pl.read_parquet('../database/textos/*.parquet')
    .join(
        pl.read_parquet('../database/metadata/*.parquet'),
        on='id'
    )
    .with_columns(
        pl.col('pubDate').str.to_date(format='%d/%m/%Y')
    )
    .filter(
        pl.col('pubDate').dt.year()>=2018,
        pl.col('artCategory').str.to_lowercase().str.contains(r'(marinha|ex[ée]rcito|aeron[áa]utica)')
    )
).select('id', 'texto')

In [42]:
textos

shape: (511_298, 2)
┌─────────────────────────┬─────────────────────────────────┐
│ id                      ┆ texto                           │
│ ---                     ┆ ---                             │
│ str                     ┆ str                             │
╞═════════════════════════╪═════════════════════════════════╡
│ 515_20190102_11355821   ┆                                 │
│                         ┆ PORTARIA Nº 2.082, DE 27 DE D…  │
│ 515_20190102_11355822   ┆                                 │
│                         ┆ PORTARIA Nº 2.083, DE 27 DE D…  │
│ 515_20190104_11366759   ┆                                 │
│                         ┆ PORTARIA Nº 401/DPC, DE 19 DE…  │
│ 515_20190107_11365668-1 ┆                                 │
│                         ┆                                 │
│                         ┆ PORTARIA DECEA Nº 258/JJAER,…   │
│ 515_20190107_11365668-2 ┆                                 │
│                         ┆ Art. 38 As sessões serão públ…  │
│ …                       ┆ …                               │
│ 530_20251231_23469728   ┆ EXTRATO DE CREDENCIAMENTO Nº 3… │
│ 530_20251231_23470217   ┆ EXTRATO DE CREDENCIAMENTO Nº 3… │
│ 530_20251231_23470438   ┆ EXTRATO DE CREDENCIAMENTO Nº 2… │
│ 530_20251231_23470552   ┆ EXTRATO DE CREDENCIAMENTO Nº 3… │
│ 530_20251231_23470580   ┆ EXTRATO DE CREDENCIAMENTO Nº 3… │
└─────────────────────────┴─────────────────────────────────┘

In [43]:
VALOR_PATTERN = r'R\$\s?(?:\d{1,3}(?:\.\d{3})*|\d+)(?:,\d{2})?'
ENT_PATTERN = r'[A-ZÁÂÃÉÊÍÓÔÕÚÇ]+\s[A-ZÁÂÃÉÊÍÓÔÕÚÇ\s]+'
PROCESSO_PATTERN = r'\b\d{5}\.?\d{6}\/?\d{4}\-?\d{2}\b'
CNPJ_PATTERN = r'\b\d{2}\.?\d{3}\.?\d{3}\/?\d{4}\-?\d{2}\b'
DATA_PATTERN = r'\b\d{1,2}/\d{1,2}/\d{2,4}\b|\b\d{1,2}\s+de\s+[a-zçãõáéíóúâêô]+\s+de\s+\d{4}\b'

In [44]:
def filter_nested_entities(items):
    if items is None:
        return []

    normalized_items = [item.strip() for item in items if item and item.strip()]

    return [
        item
        for item in normalized_items
        if not any(item != other and item in other for other in normalized_items)
    ]

textos = textos.with_columns(
    valores=pl.col('texto').str.extract_all(VALOR_PATTERN),
    entidades=pl.col('texto').str.extract_all(ENT_PATTERN).map_elements(
        filter_nested_entities,
        return_dtype=pl.List(pl.String)
    ),
    nups=pl.col('texto').str.extract_all(PROCESSO_PATTERN),
    cnpjs=pl.col('texto').str.extract_all(CNPJ_PATTERN),
    datas=pl.col('texto').str.to_lowercase().str.extract_all(DATA_PATTERN)
)

In [45]:
textos

shape: (511_298, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ id           ┆ texto       ┆ valores     ┆ entidades   ┆ nups        ┆ cnpjs       ┆ datas       │
│ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ str          ┆ str         ┆ list[str]   ┆ list[str]   ┆ list[str]   ┆ list[str]   ┆ list[str]   │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 515_20190102 ┆             ┆ []          ┆ ["PORTARIA  ┆ []          ┆ []          ┆ ["27 de     │
│ _11355821    ┆ PORTARIA Nº ┆             ┆ N", "DE     ┆             ┆             ┆ dezembro de │
│              ┆ 2.082, DE   ┆             ┆ DEZEMBRO    ┆             ┆             ┆ 2018", "30… │
│              ┆ 27 DE D…    ┆             ┆ DE…         ┆             ┆             ┆             │
│ 515_20190102 ┆             ┆ []          ┆ ["PORTARIA  ┆ []          ┆ []          ┆ ["27 de     │
│ _11355822    ┆ PORTARIA Nº ┆             ┆ N", "DE     ┆             ┆             ┆ dezembro de │
│              ┆ 2.083, DE   ┆             ┆ DEZEMBRO    ┆             ┆             ┆ 2018", "30… │
│              ┆ 27 DE D…    ┆             ┆ DE…         ┆             ┆             ┆             │
│ 515_20190104 ┆             ┆ []          ┆ ["PORTARIA  ┆ []          ┆ []          ┆ ["19 de     │
│ _11366759    ┆ PORTARIA Nº ┆             ┆ N", "DE     ┆             ┆             ┆ dezembro de │
│              ┆ 401/DPC, DE ┆             ┆ DEZEMBRO    ┆             ┆             ┆ 2018", "3 … │
│              ┆ 19 DE…      ┆             ┆ DE…         ┆             ┆             ┆             │
│ 515_20190107 ┆             ┆ []          ┆ ["PORTARIA  ┆ []          ┆ []          ┆ ["10 de     │
│ _11365668-1  ┆             ┆             ┆ DECEA N",   ┆             ┆             ┆ dezembro de │
│              ┆ PORTARIA    ┆             ┆ "DE DEZEM…  ┆             ┆             ┆ 2018", "16… │
│              ┆ DECEA Nº    ┆             ┆             ┆             ┆             ┆             │
│              ┆ 258/JJAER,… ┆             ┆             ┆             ┆             ┆             │
│ 515_20190107 ┆             ┆ []          ┆ ["V         ┆ []          ┆ []          ┆ []          │
│ _11365668-2  ┆ Art. 38 As  ┆             ┆ D", "A J",  ┆             ┆             ┆             │
│              ┆ sessões     ┆             ┆ … "TRANSMIS ┆             ┆             ┆             │
│              ┆ serão públ… ┆             ┆ SÃO …       ┆             ┆             ┆             │
│ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           │
│ 530_20251231 ┆ EXTRATO DE  ┆ ["R$ 151.06 ┆ ["EXTRATO   ┆ ["63064.010 ┆ ["08.242.47 ┆ ["15/12/202 │
│ _23469728    ┆ CREDENCIAME ┆ 2,00"]      ┆ DE CREDENCI ┆ 971/2023-38 ┆ 1/0001-18"] ┆ 5", "14/12/ │
│              ┆ NTO Nº 3…   ┆             ┆ AMENTO N"…  ┆ "]          ┆             ┆ 2026", ……   │
│ 530_20251231 ┆ EXTRATO DE  ┆ ["R$        ┆ ["EXTRATO   ┆ ["63064.010 ┆ ["60.143.97 ┆ ["15/12/202 │
│ _23470217    ┆ CREDENCIAME ┆ 20.000,00"] ┆ DE CREDENCI ┆ 971/2023-38 ┆ 2/0001-67"] ┆ 5", "14/12/ │
│              ┆ NTO Nº 3…   ┆             ┆ AMENTO N"…  ┆ "]          ┆             ┆ 2026", ……   │
│ 530_20251231 ┆ EXTRATO DE  ┆ ["R$        ┆ ["EXTRATO   ┆ ["63064.010 ┆ ["70.030.60 ┆ ["09/12/202 │
│ _23470438    ┆ CREDENCIAME ┆ 20.000,00"] ┆ DE CREDENCI ┆ 971/2023-38 ┆ 6/0001-55"] ┆ 5", "08/12/ │
│              ┆ NTO Nº 2…   ┆             ┆ AMENTO N"…  ┆ "]          ┆             ┆ 2026", ……   │
│ 530_20251231 ┆ EXTRATO DE  ┆ ["R$        ┆ ["EXTRATO   ┆ ["63064.010 ┆ []          ┆ ["10/12/202 │
│ _23470552    ┆ CREDENCIAME ┆ 5.000,00"]  ┆ DE CREDENCI ┆ 971/2023-38 ┆             ┆ 5", "09/12/ │
│              ┆ NTO Nº 3…   ┆             ┆ AMENTO N"…  ┆ "]          ┆             ┆ 2026", ……   │
│ 530_20251231 ┆ EXTRATO DE  ┆ ["R$        ┆ ["EXTRATO   ┆ ["63064.010 ┆ []          ┆ ["15/12/202 │
│ _23470580    ┆ CREDENCIAME ┆ 20.000,00"] ┆ DE CREDENCI ┆ 971/2023-38 ┆             ┆ 5", "14/12/ │
│              ┆ NTO Nº 3…   ┆             ┆ AMENTO N"…  ┆ "]          ┆             ┆ 2026", ……   │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [46]:
print(textos.filter(pl.col('valores').list.len() > 0).item(6, 'texto'))

PORTARIA Nº 184/HNRE, DE 18 DE DEZEMBRO DE 2020
O DIRETOR DO HOSPITAL NAVAL DE RECIFE, em conformidade com contido na Orientação Normativa AGU nº 33/2011, resolve:
Art. 1º Que seja dada publicidade, por meio do Diário Oficial da União, aos Termos de Adesão ao Edital de Credenciamento nº 2/2019, Processo Administrativo n° 63066.003213/2019-67, deste Hospital, assinado pela Organização de Saúde Extra-Marinha abaixo especificada:
I - COOPERATIVA DOS MÉDICOS ANESTESIOLOGISTAS DE PERNAMBUCO.
a)CNPJ nº 11.187.085/0001-85; e
b) Valor Estimativo: R$ 200.000,00 (duzentos mil reais).
Art. 2º Fundamentação: Inexigibilidade de Licitação, com fundamento no art. 25, caput, da Lei nº 8.666/1993.
Art. 3º Esta Portaria entra em vigor na presente data.
Capitão de Mar e Guerra (Md) CÁSSIO DE SOUZA SANTOS

In [47]:
print(textos.item(1, 'texto'))

PORTARIA Nº 2.083, DE 27 DE DEZEMBRO DE 2018
Fixa as metas de desempenho institucional para o ano de 2019, no âmbito do Exército, para fim de aplicação da Portaria do Comandante do Exército nº 1.180, de 30 de novembro de 2010.
O COMANDANTE DO EXÉRCITO, no uso das atribuições que lhe conferem o art. 4º da Lei Complementar nº 97, de 9 de junho de 1999, alterada pela Lei Complementar nº 136, de 25 de agosto de 2010, o inciso I do art. 20 da Estrutura Regimental do Comando do Exército, aprovada pelo Decreto nº 5.751, de 12 de abril de 2006, e em conformidade com o Decreto nº 7.133, de 19 de março de 2010, o parágrafo 1º do art. 21 da Portaria do Comandante do Exército nº 1.180, de 30 de novembro de 2010, ouvido o Estado-Maior do Exército, resolve:
Art. 1º Fixar as metas globais de desempenho institucional para o ano de 2019, no âmbito do Exército, para fim de aplicação da Portaria do Comandante do Exército nº 1.180, de 30 de novembro de 2010.
Art. 2º Determinar que o Centro de Comunicação Social do Exército realize a divulgação das metas estabelecidas no site institucional do Exército Brasileiro, em conformidade com o art. 22 da Portaria do Comandante do Exército nº 1.180, de 30 de novembro de 2010.
Art. 3º Estabelecer que esta Portaria entre em vigor a partir de 1º de janeiro de 2019.
METAS GLOBAIS DE DESEMPENHO INSTITUCIONAL PARA O ANO DE 2019
<p>
OBJETIVO ESTRATÉGICO
RESPONSÁVEL PELO INDICADOR
INDICADOR
FÓRMULA
META
Fortalecer a dimensão humana
Departamento-Geral do Pessoal
Percentual de militares com faixa de desempenho igual ou superior ao desempenho esperado
(Nº de militares com faixa de desempenho igual ou maior que o desempenho esperado (7,0 £ desempenho £ 9,1) / Nº de militares avaliados) x100
100%
Fortalecer a dimensão humana
Departamento de Educação e Cultura do Exército
Índice de atendimento à Família Militar no Sistema Colégio Militar do Brasil (SCMB)
(Nº de matrículas atendidas /Nº de matrículas solicitadas) x100
80%
Fortalecer os valores, deveres e a ética militar
Departamento de Educação e Cultura do Exército
Índice de visitação de civis e de militares aos espaços culturais do Exército
(Nº de visitantes aos espaços culturais em A/ Nº de visitantes em A-1) x100
105%
Ampliar a Integração do Exército à Sociedade
Departamento de Engenharia e Construção
Índice de apoios realizados pela Engenharia Militar em benefício da Sociedade
(Nº de apoios atendidos / Nº de solicitações recebidas) x100
90%
Implantar um novo e efetivo sistema logístico militar terrestre
Comando Logístico
Índice de atendimento aos Contratos de Objetivos firmados com as Regiões Militares
(Nº de contratos atendidos / Nº de contratos firmados) x100
100%
Maximizar a obtenção de recursos do orçamento e outras fontes
Secretaria de Economia e Finanças
Índice de execução orçamentária do Comando do Exército até 30 NOV do ano A
(Montante dos Recursos orçamentários executados até 30 NOV ano A pelo Comando do Exército/ Montante dos Recursos Orçamentários autorizado para o Comando do Exército ano A) x100
90%
Implantar um novo e efetivo sistema de ciência, tecnologia e inovação
Departamento de Ciência e Tecnologia
Quantidade de protótipos e lotes pilotos entregues para avaliação.
Nº de itens (protótipos e lotes pilotos) entregues para avaliação
8

Gen Ex EDUARDO DIAS DA COSTA VILLAS BÔAS

In [48]:
textos.item(1,  'entidades')

shape: (6,)
Series: '' [str]
[
	"PORTARIA N"
	"DE DEZEMBRO DE"
	"O COMANDANTE DO EXÉRCITO"
	"METAS GLOBAIS DE DESEMPENHO IN…
	"OBJETIVO ESTRATÉGICO
RESPONSÁV…
	"EDUARDO DIAS DA COSTA VILLAS B…
]

In [49]:
contagem_entidades = {}

for i in range(textos.height):
    for entidade in textos.item(i, 'entidades'):
        if entidade not in contagem_entidades:
            contagem_entidades[entidade] = 1
        else:
            contagem_entidades[entidade] += 1

In [50]:
contagem_entidades

{'PORTARIA N': 65315,
 'DE DEZEMBRO DE': 7244,
 'O COMANDANTE DO EXÉRCITO': 6071,
 'RESULTADO DO DESEMPENHO INSTITUCIONAL DO EB': 1,
 'OBJETIVO ESTRATÉGICO\nRESPONSÁVEL\nINDICADOR\nFÓRMULA\nMETA\nDESEMPENHO\nF': 2,
 'DESEMPENHO GLOBAL': 7,
 'EDUARDO DIAS DA COSTA VILLAS BÔAS': 710,
 'METAS GLOBAIS DE DESEMPENHO INSTITUCIONAL PARA O ANO DE': 5,
 'OBJETIVO ESTRATÉGICO\nRESPONSÁVEL PELO INDICADOR\nINDICADOR\nFÓRMULA\nMETA\nF': 1,
 'O DIRETOR DE PORTOS E COSTAS': 1519,
 'CONSIDERAÇÕES GERAIS': 22,
 'ÁREAS DE SEGURANÇA': 10,
 'ROBERTO GONDIM CARNEIRO DA CUNHA': 435,
 'PORTARIA DECEA N': 113,
 'O DIRETOR': 523,
 'GERAL DO DEPARTAMENTO DE CONTROLE DO ESPAÇO AÉREO': 127,
 'JEFERSON DOMINGUES DE FREITAS\n\nANEXO I\nREGULAMENTO DA COMPETÊNCIA': 1,
 'FUNCIONAMENTO E PROCEDIMENTO DOS PROCESSOS DA JUNTA DE JULGAMENTO DA AERONÁUTICA': 1,
 'RJJAER\nTÍTULO I\nDA COMPETÊNCIA': 1,
 'ORGANIZAÇÃO E FUNCIONAMENTO DA JUNTA DE JULGAMENTO DA AERONÁUTICA\nCAPÍTULO I\nDA FINALIDADE': 1,
 'FUNCIONAMENTO E JURISDIÇÃO\nS': 1,
 'A JJAER': 6,
 'IV\nD': 162,
 'CAPÍTULO II\nDA ORGANIZAÇÃO DA JUNTA DE JULGAMENTO DA AERONÁUTICA\nS': 1,
 'O P': 2062,
 'CAPÍTULO III\nDO FUNCIONAMENTO DA JUNTA DE JULGAMENTO DA AERONÁUTICA\nS': 1,
 'A SECAP': 2,
 'V\nD': 13,
 'A J': 41,
 'VI\nD': 91,
 'A C': 3207,
 'VII\nD': 77,
 'VIII\nD': 70,
 'TÍTULO II\nDO PROCEDIMENTO PARA A APURAÇÃO E JULGAMENTO DE INFRAÇÕES DE TRÁFEGO AÉREO E DESCUMPRIMENTO DAS NORMAS QUE REGULAM O SISTEMA DE CONTROLE DO ESPAÇO AÉREO BRASILEIRO': 1,
 'CAPÍTULO I\nDOS PRINCÍPIOS GERAIS\nS': 1,
 'AGENTES DA AUTORIDADE AERONÁUTICA': 1,
 'ASSINATURA ELETRÔNICA': 3,
 'AUTO DE INFRAÇÃO': 8,
 'ÁREA DE MANOBRAS': 1,
 'CIRCULAÇÃO AÉREA GERAL': 1,
 'CIRCULAÇÃO OPERACIONAL MILITAR': 1,
 'ESTAÇÃO PRESTADORA DE SERVIÇOS DE TELECOMUNICAÇÕES AERONÁUTICAS E DE TRÁFEGO AÉREO': 1,
 'FICHA DE COMUNICAÇÃO DE INFRAÇÃO': 1,
 'FORMULÁRIO DE ANÁLISE PRELIMINAR': 1,
 'IDENTIFICAÇÃO ELETRÔNICA': 1,
 'INFRAÇÃO DE TRÁFEGO AÉREO': 1,
 'MEIO ELETRÔNICO': 1,
 'MENSAGEM DE COMUNICAÇÃO DE IRREGULARIDADE DE TRÁFEGO AÉREO': 2,
 'NOTIFICAÇÃO DE AUTUAÇÃO': 1,
 'NOTIFICAÇÃO DE DECISÃO': 1,
 'NOTIFICAÇÃO PARA PAGAMENTO DE GUIA DE RECOLHIMENTO DA UNIÃO': 1,
 'ÓRGÃO DE CONTROLE DE TRÁFEGO AÉREO': 1,
 'ÓRGÃO DOS SERVIÇOS DE TRÁFEGO AÉREO': 1,
 'ÓRGÃO REGIONAL DO DECEA': 1,
 'ÓRGÃO DE CONTROLE DE OPERAÇÕES AÉREAS MILITARES': 1,
 'PLATAFORMA DE COMUNICAÇÃO PROCESSUAL': 1,
 'TRANSMISSÃO ELETRÔNICA': 1,
 'CAPÍTULO II\nDA COMPETÊNCIA\nS': 1,
 'CAPÍTULO III\nDOS PROCEDIMENTOS PARA A APURAÇÃO DE IRREGULARIDADES E INFRAÇÕES\nS': 1,
 'O A': 634,
 'O C': 4555,
 'O Ó': 21,
 'A FCI': 1,
 'CAPÍTULO IV\nDO PROCESSO ADMINISTRATIVO\nS': 1,
 'A P': 1168,
 'III\nD': 65,
 'O AI': 2,
 'A D': 661,
 'CAPÍTULO V\nDAS PENALIDADES E DAS PROVIDÊNCIAS ADMINISTRATIVAS\nS': 1,
 'TÍTULO III\nDAS DISPOSIÇÕES TRANSITÓRIAS\nA': 1,
 'TÍTULO IV\nDAS DISPOSIÇÕES FINAIS\nCAPÍTULO I\nDA SEGURANÇA INSTITUCIONAL\nA': 1,
 'CAPÍTULO II\nDAS DISPOSIÇÕES NÃO CONSTANTES DO CAPÍTULO ANTERIOR\nA': 1,
 'CAPÍTULO III\nDOS CASOS OMISSOS\nA': 1,
 'CAPÍTULO IV\nDA VIGÊNCIA\nA': 1,
 'ANEXO II\nTABELA PARA ENQUADRAMENTO DE INFRAÇÕES': 1,
 'EM R': 9,
 'PESSOA JURÍDICA\nC': 1,
 'PESSOA FÍSICA\nPESSOA JURÍDICA\nJJ': 7,
 'V\nF': 2,
 'VII\nP': 9,
 'III\nI': 3,
 'VI\nI': 2,
 'TRÁFEGO DE EMBARCAÇÕES': 4,
 'INFORMAÇÕES SOBRE O TRÁFEGO': 3,
 'PESCA E': 4,
 'NAVEGAÇÃO NAS ÁREAS DE SEGURANÇA DE PLATAFORMAS DE PETRÓLEO E DEMAIS UNIDADES OFFSHORE': 2,
 'NAVEGAÇÃO NAS ÁREAS DE SEGURANÇA DE UNIDADES ESTACIONÁRIAS DE PRODUÇÃO DE PETRÓLEO E DEMAIS UNIDADES OFFSHORE': 1,
 'DENÚNCIA DE INVASÃO NA ÁREA DE SEGURANÇA DE PLATAFORMA DE PETRÓLEO E DEMAIS UNIDADES OFFSHORE': 2,
 'ROBERTO GONDIM CARNEIRO DA CUNHA\n\nANEXO': 1,
 'O DIRETOR DO ARSENAL DE MARINHA DO RIO DE JANEIRO': 140,
 'MULTISUPRIMENTOS SUPRIMENTOS E EQUIPAMENTOS PARA ESCRITORIO E INFORMÁTICA EIRELLI': 1,
 'LIBERAL ENIO ZANELATTO': 75,
 'INSTRUÇÃO TÉCNICO': 11,
 'ADMINISTRATIVA N': 12,
 'DE JANEIRO DE': 8064,
 'O DIRETOR DE FISCALIZAÇÃO DE PRODUTOS CONTROLADOS': 43,
 'FÁBIO PIRES DO VAL': 14,
 'O COMANDANTE DA AERONÁUTICA': 6751,
 'O GAP': 481,
 'O CEAP': 2,
 'ANTONIO CARLOS MORETTI BERMUDEZ': 2080,
 'A I': 248,
 'MAERSK TRAINING BRASIL': 2,
 'PORTARIA GAP': 173,
 'NT N': 23,
 'A DISTRIBUIDORA DE PRODUTOS HOSPITALAR LTDA': 2,
 'O ORDENADOR DE DESPESAS DO GRUPAMENTO DE APOIO DE NATAL': 17,
 'CARLOS JOSÉ RODRIGUES T': 32,
 'PAULO MACHADO PEREIRA JUNIOR': 2,
 'LINCOLN JORGE TAGOMORI': 2,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nSTARNAV DRACO': 5,
 'ROBERTO GONDIM CARNEIRO DA CUNHA\nV': 48,
 'JOSÉ ROBERTO MATTOS DOS SANTOS': 1,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nUP PEARL': 5,
 'JOSE MARIA MOREIRA GOMES': 2,
 'DIEGO MARCELO BALDINI': 2,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nMAERSK VEGA': 3,
 'JOSIAS DE ALMEIDA FERREIRA FILHO': 1,
 'DANIEL CHAUVIERE DO CARMO': 1,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nSABLE': 1,
 'BRUNO MARIANO DE OLIVEIRA': 1,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nBONGO': 1,
 'LUIZ GONZAGA CAMPOS': 2,
 'ENIO RENATO LOPES DE ALBUQUERQUE': 1,
 'DPC REV': 5,
 'TUP ATR L': 1,
 'ALEXANDRE VERAS VASCONCELOS': 18,
 'CELESTINO NUNES DE OLIVEIRA NETO': 4,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nOSTREIRO': 4,
 'SÉRGIO MAURÍCIO HILL REGENERATI': 2,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nSTARNAV REGULUS': 3,
 'INFRA CO': 26,
 'PORTARIAS DE': 670,
 'O DIRETOR DO INSTITUTO DE CARTOGRAFIA AERONÁUTICA': 968,
 'DECEA N': 22,
 'APROVAR O PLANO BÁSICO DE ZONA DE PROTEÇÃO DE AERÓDROMO': 1,
 'FAZENDA GUADALUPE': 1,
 'FAZENDA PAMPA ALEGRE': 1,
 'FAZENDA REMANSO': 1,
 'FAZENDA BREJON': 1,
 'HELISUL JURERÊ': 2,
 'BLUE TOWER': 1,
 'FAZENDA SÃO SEBASTIÃO DO JATOBAZINHO': 1,
 'SÍTIO AEROPORTUÁRIO ESTEIRINHA': 2,
 'FAZENDA OLHO D': 2,
 'FAZENDA SOSSEGO': 3,
 'FAZENDA CAPÃO VERDE': 1,
 'FAZENDA TAMARA': 1,
 'HOSPITAL DA BAHIA': 1,
 'VR AVIATION': 2,
 'CHÁCARA SÃO JOSÉ': 2,
 'PISTA ALDEIA RIO VERMELHO': 1,
 'JOÃO GALDINO': 1,
 'FAZENDA TRÊS FRONTEIRAS': 4,
 'RETIRO SANTA RITA': 1,
 'FAZENDA VITÓRIA': 15,
 'FAZENDA ONÇA PARDA': 2,
 'FAZENDA PRIMAVERA': 14,
 'RIO NEGRINHO': 1,
 'FAZENDA SÃO JOSÉ': 27,
 'AERO PARQUE TUPÃ': 1,
 'ALIMENTOS DALLAS': 1,
 'FAZENDA TIMBAÚBA I': 1,
 'COMANDANTE ALMIR MENDES DE OLIVEIRA': 2,
 'MONTE DAS ACÁCIAS': 1,
 'VILA DO CARVALHO': 1,
 'HOSPITAL TOTALCOR': 1,
 'FAZENDA NOVA FRONTEIRA': 2,
 'FAZENDA ROSA DO DESERTO': 2,
 'AERÓDROMO LOBO AGROPECUÁRIA': 1,
 'AERÓDROMO PIRAQUARA': 1,
 'BEVERLY HILLS': 1,
 'FAZENDA SANTA ZÉLIA': 1,
 'FAZENDA MANO JULIO': 1,
 'TERRA BRANCA': 1,
 'POVOADO CAMAÇARI': 1,
 'FAZENDA SANTA FÉ': 10,
 'FAZENDA SESMARIAS': 3,
 'RICARDO DA SILVA MIRANDA C': 23,
 'O COMANDANTE DA MARINHA': 2432,
 'ILQUES BARBOSA JUNIOR': 727,
 'PASQUALOTTO BRAVA': 4,
 'LAGO AZUL': 1,
 'AQUIRAZ FORTALEZA': 2,
 'TERRAS DE SÃO JOSÉ': 1,
 'SÍTIO CANHANHEIRO': 1,
 'WARNA ROOS': 1,
 'RIACHO VERDE': 1,
 'CONCÓRDIA CORPORATE': 1,
 'ICS GUARUJÁ': 1,
 'TREND BANK': 1,
 'CONJUNTO HOSPITALAR MANDAQUI': 1,
 'FAZENDA SERRA GRANDE': 3,
 'FAZENDA TAUÁ': 3,
 'PORTARIA DIRENS N': 135,
 'EA EAOEAR': 44,
 'O DIRETOR DE ENSINO': 138,
 'RUI CHAGAS MESQUITA': 75,
 'DESPACHO N': 142,
 'MARCOS SILVA RODRIGUES\nV': 20,
 'ANDERSON ALMEIDA DE AZEVEDO': 5,
 'FRANCISCO BELCHIOR SANTANA SOUZA FILHO': 2,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nCBO TERRA BRASILIS': 4,
 'JOSÉ MARIA DE MATOS': 2,
 'ALAN SERGIO MEIRELES ALCANTARA': 2,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nCBO CABRÁLIA': 3,
 'PEDRO HUGO SOARES DOTTORI': 6,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nASSO TRENTUNO': 5,
 'MAURICIO ANGELI SPINOSA': 2,
 'GILBERT GOMES DE MELO': 2,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nFAR SAGA': 2,
 'EA CFS': 129,
 'EA EIAC': 35,
 'EA EAOAP': 33,
 'EA CADAR': 45,
 'EA CAFAR': 41,
 'O DIRETOR DE ADMINISTRAÇÃO DA MARINHA': 236,
 'JOSÉ CARLOS MATHIAS': 8,
 'C A': 3176,
 'HUGO CAVALCANTE NOGUEIRA': 67,
 'ANTONIO CARLOS MORETTI BERMUDEZ\nO R': 10,
 'O CHEFE DO GRUPAMENTO DE APOIO DE MANAUS': 41,
 'FLÁVIO GARCIA NETTO MACHADO': 17,
 'PLÁCIDOS COMERCIAL LTDA': 6,
 'CONSELHO DE ADMINISTRAÇÃO\nATA N': 59,
 'DE OUTUBRO DE': 8326,
 'JOSÉ ALBERTO CUNHA COUTO': 7,
 'ENÉAS TADEU FERNANDES ERVILHA': 5,
 'MURILO FRANCISCO BARELLA': 84,
 'A AMAZUL': 98,
 'O E': 1622,
 'BENTO COSTA LIMA LEITE DE ALBUQUERQUE JUNIOR\nR': 17,
 'JOAQUIM SILVA E LUNA\nR': 14,
 'PAULO ROBERTO PERTUSI\nR': 10,
 'NEY ZANELLA DOS SANTOS\nD': 19,
 'FERNANDO ATLEE PHILLIPS LIGIÉRO\nR': 6,
 'DANIEL MASSAMI HIRATA\nR': 14,
 'CLAUDIA SBRAGIA MAZZO\nS': 26,
 'ATA N': 1216,
 'O S': 872,
 'DE NOVEMBRO DE': 7383,
 'PAULO RICARDO MÉDICI': 4,
 'KELLY CRISTINA MATOS DOS SANTOS': 1,
 'MARCUS VINICIUS LIMA DE SOUZA': 57,
 'JOSÉ WANDERLEY PINHEIRO': 3,
 'MAURICIO MORAES CREMONESI': 5,
 'BB P': 21,
 'O CONTI': 6,
 'ITA N': 1,
 'O REITOR DO INSTITUTO TECNOLÓGICO DE AERONÁUTICA': 28,
 'ALEXANDRE BERGONSI BERNAT': 1,
 'VAGA ORDINÁRIA': 85,
 'ALEXANDRE MARANHÃO DA ROCHA': 1,
 'ALVARO TEDESCHI NETO': 1,
 'ANA CLARA DE CARVALHO NORONHA': 4,
 'VAGA PRIVATIVA': 25,
 'ANNA KARENINA PEREIRA ARANTES': 1,
 'ARTHUR QUEIROZ RAMOS': 1,
 'AUGUSTO HENRIQUE PERUCHI ZANCA': 1,
 'AURÉLIO MIGUEL DA MOTA FERNANDES': 1,
 'AYRTON DA SILVA ISERI': 1,
 'BERNARDO DIAS': 1,
 'BRUNA FERNANDES VERTEMATI': 3,
 'BRUNO BENJAMIM BERTUCCI': 1,
 'BRUNO FRANCA ROSTIROLLA': 1,
 'BRUNO HENRIQUE ALMEIDA DA CUNHA': 1,
 'CAIO AUGUSTO DE CARVALHO COSTA': 1,
 'CAIO COSTA TAVARES': 1,
 'DANIEL FONSECA SOARES': 1,
 'DANIEL FRANCISCO FERNANDES ALVES CAIXETA': 1,
 'DANIEL LUIZ DE MELO THIESSEN': 1,
 'DAVI DE PAIVA PENHA': 1,
 'DAVI MUNIZ VASCONCELOS': 1,
 'DAVI XIE': 1,
 'ERIC EZEQUIEL YOSHIDA DE LIMA': 1,
 'ERICK DE ARAÚJO COELHO': 1,
 'FABIO FREITAS DE SOUZA FILHO': 1,
 'FABIO MACIEL BORELLA': 1,
 'FERNANDO ALVES DOMINGOS': 3,
 'FERNANDO GUSMÃO ZANCHITTA': 5,
 'FRANCISCO BRUNO DIAS RIBEIRO DA SILVA': 4,
 'FRANCISCO JOSÉ DE LAVOR PEREIRA': 1,
 'FREDISON SOARES DA SILVA JUNIOR': 1,
 'GABRIEL BARBOSA MARTINZ': 1,
 'GABRIEL CERQUEIRA SILVA': 1,
 'GABRIEL HENRIQUE GOBI': 4,
 'GABRIEL TEIXEIRA RODRIGUES': 1,
 'GUILHERME GOULART KOWALCZUK': 1,
 'GUILHERME NASCIMENTO DE OLIVEIRA': 1,
 'GUILHERME REIS MIGUEL': 1,
 'GUILHERME VIEIRA MANHAES': 1,
 'GUSTAVO DINIZ MISK': 1,
 'GUSTAVO JUN ASAI': 1,
 'GUSTAVO PEREIRA DE SOUZA': 4,
 'GUSTAVO VINICIUS FERNANDES CUNHA': 1,
 'HENRIQUE SILVA SIMPLICIO': 1,
 'IANN SA DE MEDEIROS E SILVA': 1,
 'ISABELA MATOS GOMES': 1,
 'JIAN LUCAS BRITO VERAS': 1,
 'JOÃO FRANCISCO CRISTOVÃO DE ANDRADE FERRAZ': 1,
 'JOÃO GABRIEL VIEIRA SILVA': 1,
 'JOÃO LUIS ROCHA SARMENTO': 1,
 'JOÃO MARCOS DE MORAIS SILVA': 1,
 'JOÃO PEDRO VIEIRA': 1,
 'JOÃO VICTOR GOMES DA SILVA': 4,
 'JOÃO VICTOR MOREIRA PIMENTEL': 1,
 'JOÃO VITOR GUERREIRO DIAS': 1,
 'JORGE MÁRCIO LOPES COSTA': 1,
 'KATHIANNE NIVAN DE AGUIAR LOPES': 3,
 'KENJI DE SOUZA YAMANE': 1,
 'KEVIN LUCAS HIRO NISHIMURA': 1,
 'LEVY BRUNO DO NASCIMENTO BATISTA': 1,
 'LUCA DE SOUZA PIRES': 1,
 'LUCA LARA RASSI': 1,
 'LUCAS ANTONIO ARAÚJO RAMOS PONTE': 1,
 'LUCAS DA SILVA SOUSA': 5,
 'LUCAS EDGAR MONTEIRO GERKE': 3,
 'LUCAS FIGUEIREDO MEDEF': 1,
 'LUCAS JOSÉ VELOSO DE SOUZA': 1,
 'LUCAS MELO DE OLIVEIRA': 1,
 'LUCAS MOREIRA BERNES': 1,
 'LUCAS NATAN BRIANESE DE OLIVEIRA': 1,
 'LUCIANO JACOB DE ARAÚJO FILHO': 1,
 'LÚCIO MARTINS DE SOUZA RAMOS': 2,
 'LUIS GUILHERME FONSECA FRANCO': 1,
 'MARCELLO AUGUSTO BORGES VASQUES': 3,
 'MÁRCIO MYLER FERREIRA PANTALEAO SILVA': 1,
 'MARINA GONÇALVES MOREIRA': 3,
 'MATEUS FERNANDES DA ROSA': 3,
 'MATEUS NOBRE SANTOS': 1,
 'MATEUS SALES DE OLIVEIRA': 3,
 'MATHEUS LOPES DE PROENÇA': 1,
 'MATHEUS MARTINS GODINHO': 1,
 'NACIB ABRAHÃO NEME NETO': 1,
 'OTAVIO HENRIQUE RIBAS GUIMARAES': 1,
 'PEDRO BRAZ IPLINSKY': 3,
 'PEDRO HENRIQUE BONFIM LEAL': 1,
 'RAFAEL CASSOL FRISCH': 1,
 'RAFAEL MELLO CELENTE': 1,
 'REGIS MILLER ALMEIDA DA COSTA': 1,
 'RENAN MEDEIROS AGUIAR': 1,
 'RENAN OLIVEIRA DE PAULA': 1,
 'RICARDO PATRIZI SCARPARI': 1,
 'RICARDO PEREIRA VILALBA': 1,
 'RINA CHEN CARVALHO': 1,
 'RODRIGO ARAUJO HOLANDA': 1,
 'RUBENS JULIO RAMOS': 3,
 'SAMUEL CRUZ FERNANDES': 3,
 'SAMUEL ESTEVAO VENDRAMINI': 1,
 'SARAH DA SILVA PEREIRA': 1,
 'THIAGO LOBO FERREIRA': 1,
 'THIAGO LOPES DE ARAÚJO': 1,
 'THIAGO MOURA MARINHO AMARO': 1,
 'VINICIUS ARAÚJO BASÍLIO': 1,
 'VINICIUS DE SOUZA LIMA': 1,
 'VINICIUS LACERDA LOPES': 1,
 'VINICIUS MARTINS DA SILVEIRA FULCONI': 1,
 'VINICIUS SOLEDADE MATOS AMORIM': 1,
 'VITOR BATISTA BICIATI': 1,
 'VITOR OTAVIO NASCIMENTO HALLEY CAVALCANTI': 1,
 'VITOR SILVA CARVALHO LYRA': 1,
 'YURI GAMA DE ARAÚJO': 1,
 'OBJETIVO ESTRATÉGICO\nINDICADOR\nRESPONSÁVEL PELO INDICADOR\nFÓRMULA\nMETA ANUAL\nOEE': 6,
 'CONTRIBUIR COM A DISSUASÃO EXTRARREGIONAL\nIR': 5,
 'AMPLIAR A PROJEÇÃO DO EXÉRCITO NO CENÁRIO INTERNACIONAL\nIR': 5,
 'CONTRIBUIR COM O DESENVOLVIMENTO SUSTENTÁVEL E A PAZ SOCIAL\nIR': 5,
 'ATUAR NO ESPAÇO CIBERNÉTICO COM LIBERDADE DE AÇÃO\nIR': 1,
 'EDSON LEAL PUJOL': 1476,
 'O O': 7467,
 'BATALHAO DE ENGENHARIA DE CONSTRUCAO': 3151,
 'OCS PSIC PSICOLOGIA CLINICA E ESPECIALIDADES INTEG': 1,
 'CNPJ N': 3351,
 'GIL VALADAO FORTES T': 13,
 'OCS J': 4,
 'C MESCHEDE LTDA': 9,
 'LAB VIDA': 1,
 'OCS CENTRO DE PESQUISA E DIAGNOSTICO ESPECIALIZADO LTDA': 1,
 'QUALIS DIAGNOSTICO': 1,
 'ANTONIO CARLOS MORETTI BERMUDEZ\nANEXO\nA': 1,
 'UNIDADE ORÇAMENTÁRIA': 48,
 'MINISTÉRIO DA DEFESA': 883,
 'X BR': 4,
 'COMANDO DA AERONÁUTICA': 292,
 'X\nD': 6,
 'CAIXA DE FINANCIAMENTO IMOBILIÁRIO DA AERONÁUTICA\nPROGRAMA': 5,
 'FUNDO AERONÁUTICO\nPROGRAMA': 6,
 'RECURSOS SOB SUPERVISÃO DA CAIXA DE FINANCIAMENTO IMOBILIÁRIO DA AERONÁUTICA\nPROGRAMA': 7,
 'CONSELHO DE ADMINISTRAÇÃO\nATA DA': 12,
 'REUNIÃO ORDINÁRIA': 7,
 'O G': 1280,
 'EDUARDO CESAR PASA': 2,
 'NÉLSON L': 1,
 'CYRINO A': 1,
 'RESOLUÇÃO N': 76,
 'DECÍLIO DE MEDEIROS SALES': 15,
 'DÉCIO LUÍS SCHONS\nP': 19,
 'IMBEL\nG': 7,
 'ADERICO VISCONTE PARDI MATTIOLI\nR': 12,
 'IMBEL\nNELSON LEITÃO PAES\nR': 5,
 'DENILSON PIMENTEL BARBETO\nR': 4,
 'IMBEL\nEDUARDO CÉSAR PASA\nR': 6,
 'MD\nFRANCISCO DE ASSIS LEME FRANCO\nR': 2,
 'MD\nCARLOS B': 4,
 'DESPACHO MB N': 59,
 'ADMIRAL VLADIMIRSKY': 1,
 'ARTHUR FERNANDO BETTEGA CORRÊA\nV': 38,
 'O CINDACTA III': 15,
 'A SA C': 1,
 'O SUBCHEFE DO ESTADO': 1,
 'MAIOR DO COMANDO DO COMANDO MILITAR DO NORDESTE': 1,
 'O PDTIC': 5,
 'A Í': 2,
 'MARCO ANTONIO MUNIZ LEITE': 6,
 'CMNE\nP': 7,
 'OCS MACEDO E AGUIAR': 1,
 'ROCHA LTDA': 35,
 'O N': 1224,
 'O GCM': 2,
 'AUCON S': 2,
 'JEFERSON DOMINGUES DE FREITAS': 315,
 'O EME': 107,
 'EDSON LEAL PUJOL\nC': 26,
 'DIOMACIO APOLINARIO DA SILVA': 2,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nFAR SCOTSMAN': 2,
 'JOSE VALDIVINO DA SILVA JUNIOR': 2,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nSTARNAV ANDROMEDA': 4,
 'CARLOS EDUARDO ALBUQUERQUE FEITOZA CARNEIRO': 4,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTO DE OPERAÇÃO AUTORIZADO\nBRAM BAHIA': 2,
 'JOÃO CARLOS FERREIRA PINHEIRO DOS SANTOS': 2,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nBRAM HERO': 4,
 'JEFFERSON DO NASCIMENTO CANTALICE': 1,
 'IGOR SANTANA DA SILVA': 1,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nHOS BRASS RING': 1,
 'PORTARIA DIRAP N': 3069,
 'O DIRETOR DE ADMINISTRAÇÃO DO PESSOAL': 6904,
 'MAURO MARTINS MACHADO': 1410,
 'TEC SED': 2,
 'PAULO CESAR FERREIRA DE DOMENICO': 1,
 'WAIDIKLONN JOOK RODRIGUES DA SILVA': 2,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nSTARNAV HYDRA': 1,
 'FRANCISCO JOSÉ BRITO DE SOUZA': 2,
 'EDGAR BORGES LEAL': 2,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTO DE OPERAÇÃO AUTORIZADO\nCBO COPACABANA': 4,
 'JUAREZ SILVA DE VASCONCELOS': 5,
 'KLINGER BARRA CAXIAS': 2,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nSTARNAV AQUARIUS': 6,
 'O CAPITÃO DOS PORTOS DO CEARÁ': 6,
 'FRANCISCO VALCILIO DE SALES': 2,
 'NAVEGANTES III': 1,
 'LUIZ AMÉRICO FILHO': 1,
 'MADSON CARDOSO SANTANA': 13,
 'TEC MAG': 4,
 'CATHEDRA COMÉRCIO E SERVIÇO EIRELI': 2,
 'ELÉSIO MARTINS FERREIRA C': 57,
 'CLAUDIA CRISTINA COELHO VICENTE': 19,
 'GILBERTO DA SILVA SANTOS': 2,
 'KAZ CARLOS PESSOA PEREIRA DA SILVA': 2,
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nSKANDI RIO': 2,
 'RETIFICAÇÃO\nN': 4917,
 'O SISSAR': 1,
 'PORTARIA CAE N': 111,
 'O COMANDANTE DO CENTRO DE AQUISIÇÕES ESPECÍFICAS': 101,
 'IMPLEMENTOS RODOVIÁRIOS LTDA': 3,
 'LUIZ RICARDO DE SOUZA NASCIMENTO': 66,
 'AEL SISTEMAS S': 140,
 'DECLARAÇÃO DE INIDONEIDADE': 1,
 'RMF ELETRICS EIRELI': 34,
 'CH GAB MD': 37,
 'O DIRETOR DE CIVIS': 5736,
 'PENSIONISTAS E ASSISTÊNCIA SOCIAL': 5798,
 'ALDER NEWMANN DE OLIVEIRA': 5,
 'ANTONIO VITOR VIEIRA TEIXEIRA': 2,
 'CRISTIANO LEMES GARCIA': 5,
 'EDILSON DE PAULA MERLIM BARBOSA': 3,
 'JAIR OLIVEIRA PEREIRA': 3,
 'MARCELO AZEVEDO': 5,
 'MARIO LUÍS CARVALHO BARBOSA DE SOUZA': 2,
 'RAUL JOSÉ VIDAL JUNIOR': 3,
 'PAULO HENRIQUE DOS SANTOS OLIVEIRA': 11,
 'JOSÉ DAGOBERTO DA SILVA': 2,
 'ADRYANO ALESSANDRO MARINHO NUNES CARNEIRO': 3,
 'ALEXANDRE CORREA DA SILVA': 3,
 'ALFREDO DE OLIVEIRA JUNIOR': 2,
 'GUILHERME FONTENELLE RIBEIRO DE OLIVEIRA': 10,
 'IGOR CARLOS BAPTISTA': 7,
 'ISMAR MACIEL JÚNIOR': 58,
 'MARLOS MAGNO FERNANDES SILVA': 10,
 'SIVALDO ROBERTO DA SILVA': 11,
 'SÓSTENES CAVALCANTE DE CASTRO': 3,
 'FRANCISCO FAURI': 2,
 'ANDRÉ FREITAS PINTO': 2,
 'ANTONIO SERGIO HENRIQUES NUNES': 3,
 'CARLOS AUGUSTO DOS SANTOS': 44,
 'DANIEL MOREIRA MARQUES': 6,
 'LAÉRCIO DE ARZAMBUJA DA ROCHA': 14,
 'MARCO JOSÉ DOS SANTOS': 19,
 'MARCOS ANTONIO TAVARES DA COSTA': 6,
 'RAFAELLE DE CARVALHO DE NARDI': 10,
 'ROMMEL VALERIO MENEZES BRITO DA SILVA': 4,
 'QEM QEMA': 53,
 'DAVID GOMES SANTIAGO': 5,
 'FABIO DOS ANJOS CRUZ': 3,
 'FRANCISCO NIXON LOPES FROTA': 38,
 'LUIZ HENRIQUE DA COSTA ARAÚJO': 9,
 'MARCO ANTONIO DIEL': 8,
 'WAGNER MUNIZ DE ANDRADE': 5,
 'EDSON SKORA ROSTY': 1432,
 'REQUISITOS MÍNIMOS PARA O ESTABELECIMENTO DE ESTAÇÕES DE MANUTENÇÃO E DE ESTAÇÕES DE SERVIÇO': 5,
 'REQUIREMENTS FOR MAINTENANCE': 5,
 'THOROUGH EXAMINATION OPERATIONAL TESTING': 5,
 'AND REPAIR OF LIFEBOATS AND RESCUE BOATS': 5,
 'LAUNCHING APPLIANCE AND RELEASE GEAR': 5,
 'REVISÕES DOS EQUIPAMENTOS DE SALVATAGEM': 3,
 'CERTIFICADOS DE REVISÃO DE EQUIPAMENTOS DE SALVATAGEM': 1,
 'CONTROLE DOS EQUIPAMENTOS REVISADOS': 1,
 'INSPEÇÕES DAS ESTAÇÕES DE MANUTENÇÃO E ESTAÇÕES DE SERVIÇO DE EQUIPAMENTOS DE SALVATAGEM': 3,
 'CERTIFICADO DE CREDENCIAMENTO DE ESTAÇÃO DE SERVIÇOS': 1,
 'CERTIFICADO DE CREDENCIAMENTO DE ESTAÇÃO DE MANUTENÇÃO DE EQUIPAMENTOS DE SALVATAGEM INFLÁVEIS': 1,
 'O COMANDANTE DA ESCOLA DE APERFEIÇOAMENTO DE OFICIAIS': 7,
 'CARLOS AUGUSTO RAMIRES TEIXEIRA': 22,
 'CEL RENATO FIANDRINI': 4,
 'CONCEDER APOSENTADORIA ESPECIAL': 7,
 'JOGINALDO SILVA CARVALHO': 4,
 'FLÁVIO ANDRÉ FARIAS DOS SANTOS': 82,
 'ANDRÉ VIVALDO LIMA E SILVA': 12,
 'ASS FLÁVIO ANDRÉ FARIAS DOS SANTOS': 4,
 'CONCEDER APOSENTADORIA': 254,
 'LUCIANA SOUSA MARTINS': 5,
 'RSC III': 125,
 'ANTONIO VALDIR COLIN': 8,
 'GABRIEL DLUGOLENSKI LACERDA': 5,
 'RAPHAEL DE MIRANDA ROCHA': 5,
 'EDSON LEAL PUJOL\nANEXO\nMETAS GLOBAIS DE DESEMPENHO INSTITUCIONAL PARA O ANO DE': 2,
 'APERFEIÇOAR O SISTEMA DE CIÊNCIA': 7,
 'TECNOLOGIA E INOVAÇÃO\nIR': 4,
 'C E': 29424,
 'D S': 1214,
 'AMERICAN BUREAU OF SHIPPING': 4,
 'ALEXANDRE CURSINO DE OLIVEIRA': 370,
 'DO PORTO': 1,
 'SÍTIO MEQUÉNS': 1,

In [51]:
contagem = pl.DataFrame(
    {
        'entidades': list(contagem_entidades.keys()),
        'contagem': list(contagem_entidades.values())
    }
).sort('contagem', descending=True)

In [52]:
contagem

shape: (616_498, 2)
┌─────────────────────────────────┬──────────┐
│ entidades                       ┆ contagem │
│ ---                             ┆ ---      │
│ str                             ┆ i64      │
╞═════════════════════════════════╪══════════╡
│ CPF CONTRATADA                  ┆ 97409    │
│ EXTRATO DE TERMO ADITIVO N      ┆ 70990    │
│ PORTARIA N                      ┆ 65315    │
│ AVISO DE LICITAÇÃO              ┆ 64528    │
│ P                               ┆          │
│ EXTRATO DE CONTRATO N           ┆ 61990    │
│ …                               ┆ …        │
│ SECRETARIA DE ESTADO DE EDUCAC… ┆ 1        │
│ CENTRO DE REABILITACAO E SAUDE… ┆ 1        │
│ CIM CARE                        ┆ 1        │
│ CENTRO DE INTERVENCAO MULTIPRO… ┆ 1        │
│ TOMOCENTRO SAO LUCAS LTDA       ┆ 1        │
└─────────────────────────────────┴──────────┘

In [53]:
covered_entities = set()
maybe_matches = {}
ents = contagem.filter(pl.col('contagem') > 5).get_column('entidades').to_list()
ents.sort(key=len)
ents = ents[::-1]
total = len(ents)

for i, ent in enumerate(ents[:-1]):
    print(f'{i*100/total:.2f}%', end='\r')
    if ent in covered_entities:
        continue

    tail = [candidate for candidate in ents[i + 1:] if candidate not in covered_entities]
    if not tail:
        continue

    scores = process.cdist(
        [ent],
        tail,
        scorer=rapidfuzz_fuzz.ratio,
        score_cutoff=81,
        dtype=np.uint8,
        workers=-1,
    )[0]
    matches = [candidate for candidate, score in zip(tail, scores) if score > 80]
    if matches:
        maybe_matches[ent] = matches
        covered_entities.update(matches)
        
maybe_matches = {k:list(set(v)) for k, v in maybe_matches.items()}

In [54]:
maybe_matches

{'PROGRAMA E BIBLIOGRAFIA PARA A PROVA ESCRITA DE CONHECIMENTOS PROFISSIONAIS PARA O CONCURSO PÚBLICO DE ADMISSÃO AO CURSO DE FORMAÇÃO PARA O INGRESSO NO CORPO AUXILIAR DE PRAÇAS DA MARINHA': ['DE CONHECIMENTOS PROFISSIONAIS PARA O CONCURSO PÚBLICO DE ADMISSÃO AO CURSO DE FORMAÇÃO PARA O INGRESSO NO CORPO AUXILIAR DE PRAÇAS DA MARINHA'],
 'DE CONHECIMENTOS PROFISSIONAIS\nPROGRAMA E BIBLIOGRAFIA PARA A PROVA ESCRITA DE CONHECIMENTOS PROFISSIONAIS PARA INGRESSO NO QUADRO COMPLEMENTAR DO CORPO DE INTENDENTES DA MARINHA': ['PROGRAMA E BIBLIOGRAFIA PARA A PROVA ESCRITA DE CONHECIMENTOS PROFISSIONAIS PARA INGRESSO NO QUADRO COMPLEMENTAR DO CORPO DE INTENDENTES DA MARINHA'],
 'MINISTÉRIO DA DEFESA\nCOMANDO DA AERONÁUTICA\nESCOLA DE ESPECIALISTAS DE AERONÁUTICA\nAUTORIZAÇÃO PARA CANDIDATO MENOR QUE OPTOU PELO SISTEMA DE RESERVA DE VAGAS': ['MINISTÉRIO DA DEFESA\nCOMANDO DA AERONÁUTICA\nESCOLA DE ESPECIALISTAS DE AERONÁUTICA\nAUTORIZAÇÃO PARA CANDIDATO MENOR DE IDADE\nE'],
 'EXTRATO DE TERMO ADITIVO\nCONTRATO DE ATIVIDADE ESPECIAL PARA ATENDER ENCARGOS TEMPORÁRIOS DE OBRAS E SERVIÇOS DE ENGENHARIA\nCREDENCIAMENTO DE OCS': ['EXTRATO DE CONTRATO\nCONTRATO DE ATIVIDADE ESPECIAL PARA ATENDER ENCARGOS TEMPORÁRIOS DE OBRAS E SERVIÇOS DE ENGENHARIA\nCREDENCIAMENTO DE OCS',
  'DE PRORROGAÇÃO DE PRAZO AO CONTRATO DE ATIVIDADE ESPECIAL PARA ATENDER ENCARGOS TEMPORÁRIOS DE OBRAS E SERVIÇOS DE ENGENHARIA',
  'CONTRATO DE ATIVIDADE ESPECIAL PARA ATENDER ENCARGOS TEMPORÁRIOS DE OBRAS E SERVIÇOS DE ENGENHARIA\nCREDENCIAMENTO DE OCS',
  'CONTRATO DE ATIVIDADE ESPECIAL PARA ATENDER ENCARGOS TEMPORÁRIOS DE OBRAS E SERVIÇOS DE ENGENHARIA CREDENCIAMENTO DE OCS'],
 'ANEXOS\nANEXO I\nCIDADES DE REALIZAÇÃO DAS PROVAS E DOS EVENTOS COMPLEMENTARES E AS RESPECTIVAS ORGANIZAÇÕES RESPONSÁVEIS PELA EXECUÇÃO LOCAL': ['CIDADES DE REALIZAÇÃO DAS PROVAS E DOS EVENTOS COMPLEMENTARES E AS RESPECTIVAS ORGANIZAÇÕES RESPONSÁVEIS PELA EXECUÇÃO LOCAL',
  'CIDADES DE REALIZAÇÃO DAS PROVAS E EVENTOS COMPLEMENTARES E ORGANIZAÇÕES RESPONSÁVEIS PELA EXECUÇÃO LOCAL',
  'ANEXOS\nANEXO I\nCIDADES DE REALIZAÇÃO DAS PROVAS E EVENTOS COMPLEMENTARES E ORGANIZAÇÕES RESPONSÁVEIS PELA EXECUÇÃO LOCAL',
  'ANEXO I\nCIDADES DE REALIZAÇÃO DAS PROVAS E DOS EVENTOS COMPLEMENTARES E AS RESPECTIVAS ORGANIZAÇÕES RESPONSÁVEIS PELA EXECUÇÃO LOCAL',
  'CIDADES DE REALIZAÇÃO DAS PROVAS E EVENTOS COMPLEMENTARES E AS RESPECTIVAS ORGANIZAÇÕES RESPONSÁVEIS PELA EXECUÇÃO LOCAL'],
 'MINISTERIO DA DEFESA\nCOMANDO DA AERONAUTICA\nCOMISSÃO AERONÁUTICA BRASILEIRA EM WASHINGTON\nAQUISIÇÃO DE SPARE PARTS PARA SUPORTE': ['MINISTERIO DA DEFESA\nCOMANDO DA AERONAUTICA\nCOMISSÃO AERONÁUTICA BRASILEIRA EM WASHINGTON\nO',
  'MINISTERIO DA DEFESA\nCOMANDO DA AERONAUTICA\nCOMISSÃO AERONÁUTICA BRASILEIRA EM WASHINGTON\nA'],
 'AVISO DE INEXIGIBILIDADE DE LICITAÇÃO\nA ADMINISTRAÇÃO DO PARQUE DE MATERIAL DE ELETRÔNICA DA AERONÁUTICA DO RIO DE JANEIRO': ['AVISO DE INEXIGIBILIDADE DE LICITAÇÃO\nO PARQUE DE MATERIAL DE ELETRÔNICA DA AERONÁUTICA DO RIO DE JANEIRO'],
 'MINISTÉRIO DA DEFESA\nCOMANDO DA AERONÁUTICA\nDECLARAÇÃO PARA A REALIZAÇÃO DO TESTE DE AVALIAÇÃO E CONDICIONAMENTO FÍSICO\nE': ['MINISTÉRIO DA DEFESA\nCOMANDO DA AERONÁUTICA\nRECURSO QUANTO AO TESTE DE AVALIAÇÃO DO CONDICIONAMENTO FÍSICO'],
 'CALENDÁRIO ANUAL DO CONCURSO DE ADMISSÃO PARA MATRÍCULA NOS CURSOS DE FORMAÇÃO E GRADUAÇÃO DE SARGENTOS DAS ÁREAS GERAL': ['CONCURSO PÚBLICO PARA ADMISSÃO E MATRÍCULA NOS CURSOS DE FORMAÇÃO E GRADUAÇÃO DE SARGENTOS DAS ÁREAS GERAL'],
 'AQUISIÇÃO DE MATERIAIS HOSPITALARES DE USO COMUM PARA ATENDER AS ORGANIZAÇÕES DE SAÚDE DA AERONÁUTICA PARA O ANO DE': ['AQUISIÇÃO DE MATERIAIS HOSPITALARES DE USO COMUM PARA ATENDER ASORGANIZAÇÕES DE SAÚDE DA AERONÁUTICA PARA O ANO DE'],
 'CONCURSO DE ADMISSÃO AOS CURSOS DE FORMAÇÃO E GRADUAÇÃO DE OFICIAIS DA RESERVA DO QUADRO DE ENGENHEIROS MILITARES': ['CONCURSO DE ADMISSÃO AOS CURSOS DE FORMAÇÃO E GRADUAÇÃO DE OFICIAIS DA ATIVA DO QUADRO DE ENGENHEIROS MILITARES',
  'CONCURSO DE ADMISSÃO AO CURSO DE FORMAÇÃO DE OFICIAIS DA ATIVA DO QUADRO DE ENGENHEIROS MILITARES'],
 'MINISTÉRIO DA DEFESA\nCOMANDO DA AERONÁUTICA\nDECLARAÇÃO QUANTO INVESTIDURA OU NÃO INVESTIDURA EM CARGO PÚBLICO\nE': ['MINISTÉRIO DA DEFESA\nCOMANDO DA AERONÁUTICA\nDECLARAÇÃO QUANTO A NÃO INVESTIDURA EM CARGO'],
 'A SANCAO DE SUSPENSAO TEMPORARIA DE PARTICIPACAO EM LICITACAO E IMPEDIMENTO DE CONTRATAR COM A ADMINISTRACAO': ['SUSPENSÃO TEMPORÁRIA DE PARTICIPAR EM LICITAÇÃO E IMPEDIMENTO DE CONTRATAR COM A ADMINISTRAÇÃO',
  'SUSPENSÃO TEMPORÁRIA DE PARTICIPAÇÃO EM LICITAÇÃO E IMPEDIMENTO DE CONTRATAR COM A ADMNISTRAÇÃO',
  'SUSPENSÃO TEMPORÁRIA DE PARTICIPAÇÃO EM LICITAÇÃO E IMPEDIMENTO DE CONTRATAR COM A ADMINISTRAÇÃO',
  'SUSPENÇÃO TEMPORÁRIA DE PARTICIPAÇÃO EM LICITAÇÃO E IMPEDIMENTO DE CONTRATAR COM A ADMINISTRAÇÃO'],
 'EXTRATO DE TERMO ADITIVO\nEXTRATO DE TERMO ADITIVO AO CONTRATO INDIVIDUAL DE TRABALHO POR TEMPO DETERMINADO N': ['EXTRATO DE CONTRATO\nEXTRATO DE TERMO DE CONTRATO INDIVIDUAL DE TRABALHO POR TEMPO DETERMINADO N',
  'EXTRATO DE TERMO ADITIVO AO CONTRATO INDIVIDUAL DE TRABALHO POR TEMPO DETERMINADO N',
  'EXTRATO DE TERMO ADITIVO\nAO CONTRATO INDIVIDUAL DE TRABALHO POR TEMPO DETERMINADO N',
  'EXTRATO DE TERMO ADITIVO\nCONTRATO INDIVIDUAL DE TRABALHO POR TEMPO DETERMINADO N',
  'EXTRATO DE TERMO ADITIVO\nTERMO ADITIVO AO CONTRATO INDIVIDUAL DE TRABALHO POR TEMPO DETERMINADO N'],
 'O PRESENTE TERMO ADITIVO TEM POR FINALIDADE A PRORROGAÇÃO DO PRAZO DE VIGÊNCIA DO TERMO DE CREDENCIAMENTO N': ['O PRESENTE TERMO ADITIVO TEM POR FINALIDADE A PRORROGAÇÃO DO PRAZO DE VIGÊNCIA DO CONTRATO N'],
 'EFETIVAÇÃO DE MATRÍCULA NO PRIMEIRO ANO DO CURSO DE FORMAÇÃO E GRADUAÇÃO DO INSTITUTO MILITAR DE ENGENHARIA': ['EFETIVAÇÃO DE MATRÍCULA NO CURSO DE FORMAÇÃO DO INSTITUTO MILITAR DE ENGENHARIA'],
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nSTARNAV AQUARIUS': ['NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nMAERSK VENTURA',
  'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nCBO ISABELLA'],
 'CONCURSO PÚBLICO DE ADMISSÃO AO CURSO DE FORMAÇÃO PARA INGRESSO NO CORPO AUXILIAR DE PRAÇAS DA MARINHA EM': ['CONCURSO PÚBLICO DE ADMISSÃO AO CURSO DE FORMAÇÃO PARA INGRESSO NO CORPO AUXILIAR DE PRAÇAS DA MARINHA'],
 'AVISO DE PENALIDADE\nO COMANDANTE DO SEGUNDO CENTRO INTEGRADO DE DEFESA AÉREA E CONTROLE DE TRÁFEGO AÉREO': ['PARA O SEGUNDO CENTRO INTEGRADO DE DEFESA AÉREA E CONTROLE DE TRÁFEGO AÉREO'],
 'CONTRATO DE ATIVIDADE ESPECIAL PARA ATENDER ENCARGOS TEMPORÁRIOS DE OBRAS E SERVIÇOS DE ENGENHARIA\nP': ['CONTRATO DE ATIVIDADE ESPECIAL PARA ATENDER ENCARGOS TEMPORÁRIOS DE OBRAS E SERVIÇOS DE ENGENHARIA'],
 'SGRH SERVICOS DE GESTAO DE RECURSOS HUMANOS CONSTRUCOES E COMERCIO DE MATERIAIS DE CONSTRUCAO LTDA': ['SGRH SERVICOS DE CONSTRUCOES E COMERCIO DE MATERIAL DE CONSTRUCAO LTDA'],
 'FEDERAÇÃO DE COOPERATIVAS DA AGRICULTURA FAMILIAR E ECONOMIA SOLIDÁRIA DO ESTADO DE MINAS GERAIS': ['FEDERACAO DE COOPERATIVAS DA AGRICULTURA FAMILIAR E ECONOMIA SOLIDARIA DO ESTADO'],
 'PARA A PRESTAÇÃO DO SERVIÇO MILITAR VOLUNTÁRIO COMO PRAÇAS TEMPORÁRIAS DA MARINHA DO BRASIL\nO C': ['PARA A PRESTAÇÃO DO SERVIÇO MILITAR VOLUNTÁRIO COMO PRAÇAS TEMPORÁRIAS DA MARINHA DO BRASIL'],
 'AQUISIÇÃO DE MATERIAIS ESPECÍFICOS DE ODONTOLOGIA PARA AS ORGANIZAÇÕES DE SAÚDE DA AERONÁUTICA': ['AQUISIÇÃO DE MATERIAIS DE HEMOTERAPIA PARA AS ORGANIZAÇÕES DE SAÚDE DA AERONÁUTICA'],
 'MODELO DE DECLARAÇÃO DE APRESENTAÇÃO DE COMPROVANTE DE CONCLUSÃO DE CURSO DE RESIDÊNCIA MÉDICA': ['MODELO DE DECLARAÇÃO DE APRESENTAÇÃO DE COMPROVANTE DE CONCLUSÃO DE CURSO',
  'MODELO DE DECLARAÇÃO DE APRESENTAÇÃO DE COMPROVANTE DE CONCLUSÃO DE CURSO\nDECLARAÇÃO\nE'],
 'AVISO DE REGISTRO DE PREÇOS\nCENTRO DE INSTRUÇÃO ALMIRANTE ALEXANDRINO\nPUBLICAÇÃO TRIMESTRAL\nA': ['CENTRO DE INSTRUÇÃO ALMIRANTE ALEXANDRINO\nPUBLICAÇÃO TRIMESTRAL\nA',
  'EXTRATO DE REGISTRO DE PREÇO\nCENTRO DE INSTRUÇÃO ALMIRANTE ALEXANDRINO\nP',
  'EXTRATO DE REGISTRO DE PREÇOS\nCENTRO DE INSTRUÇÃO ALMIRANTE ALEXANDRINO\nP',
  'AVISO DE REGISTRO DE PREÇOS\nCENTRO DE INSTRUÇÃO ALMIRANTE ALEXANDRINO'],
 'CONCURSO PÚBLICO PARA INGRESSO NO QUADRO DE CAPELÃES NAVAIS DO CORPO AUXILIAR DA MARINHA EM': ['CONCURSO PÚBLICO PARA INGRESSO NO QUADRO TÉCNICO DO CORPO AUXILIAR DA MARINHA',
  'CONCURSO PÚBLICO PARA INGRESSO NO QUADRO TÉCNICO DO CORPO AUXILIAR DA MARINHA EM'],
 'RECURSO QUANTO AO INDEFERIMENTO DA SOLICITAÇÃO DE ISENÇÃO DO PAGAMENTO DA TAXA DE INSCRIÇÃO': ['REQUERIMENTO DE SOLICITAÇÃO DE ISENÇÃO DE PAGAMENTO DE TAXA DE INSCRIÇÃO'],
 'DEFENSER MILITAR AVENTURA E OUTDOOR COMERCIO DE EQUIPAMENTOS E ARTIGOS DE SEGURANÇA EIRELI': ['DEFENSER MILITAR AVENTURA E OUTDOOR COMERCIO DE EQUIPAMENTOS E ARTIGOS DE SEGURA'],
 'ED INFO SUPRIMENTOS DE INFORMATICA INDUSTRIA EDITORIAL COMERCIO E SERVICOS GRAFICOS EIRELI': ['ED INFO SUPRIMENTOS DE INFORMATICA INDUSTRIA EDITORIAL COMERCIO E SERVICOS GRAFI'],
 'VISTA E RECURSOS DAS PROVAS ESCRITAS OBJETIVAS DE CONHECIMENTOS PROFISSIONAIS E DA REDAÇÃO': ['VISTA E RECURSOS DA PROVA ESCRITA OBJETIVA DE CONHECIMENTOS PROFISSIONAIS',
  'VISTA E RECURSOS DA PROVA ESCRITA OBJETIVA DE CONHECIMENTOS PROFISSIONAIS E DA REDAÇÃO',
  'PROVA ESCRITA OBJETIVA DE CONHECIMENTOS PROFISSIONAIS E DA REDAÇÃO',
  'PROVA ESCRITA OBJETIVA DE CONHECIMENTOS PROFISSIONAIS E REDAÇÃO',
  'VISTA E RECURSOS DA PROVA ESCRITA OBJETIVA DE CONHECIMENTOS PROFISSIONAIS E REDAÇÃO',
  'VISTA E RECURSOS DAS PROVAS ESCRITAS OBJETIVA E DISCURSIVA DE CONHECIMENTOS PROFISSIONAIS'],
 'INSTRUÇÕES PARA O PROCESSO SELETIVO DE PROFISSIONAIS DE NÍVEL SUPERIOR DAS ÁREAS DE SAÚDE': ['PROCESSO SELETIVO DE PROFISSIONAIS DE NÍVEL SUPERIOR DAS ÁREAS DE SAÚDE',
  'INSTRUÇÕES PARA O PROCESSO SELETIVO DE PROFISSIONAIS DE NÍVEL MÉDIO DAS ÁREAS INDUSTRIAL'],
 'MODELO DE DECLARAÇÃO DE APRESENTAÇÃO DE COMPROVANTE DO REGISTRO PROFISSIONAL\nDECLARAÇÃO\nE': ['MODELO DE DECLARAÇÃO DE APRESENTAÇÃO DO REGISTRO PROFISSIONAL\nDECLARAÇÃO\nE'],
 'FORMULAÇÃO DE QUESTÕES DAS PROVAS OBJETIVAS E AOS SEUS RESPECTIVOS GABARITOS PROVISÓRIOS': ['FORMULAÇÃO DE QUESTÕES DAS PROVAS ESCRITAS E AOS SEUS RESPECTIVOS GABARITOS'],
 'CENTRO DE INSTRUÇÃO E ADESTRAMENTO AERONAVAL ALMIRANTE JOSÉ MARIA DO AMARAL OLIVEIRA\nSO': ['CENTRO DE INSTRUÇÃO E ADESTRAMENTO AERONAVAL ALMIRANTE JOSÉ MARIA DO AMARAL OLIVEIRA'],
 'GE HEALTHCARE DO BRASIL COMÉRCIO E SERVIÇOS PARA EQUIPAMENTOS MÉDICOS HOSPITALARES LTDA': ['GE HEALTHCARE DO BRASIL COMÉRCIO E SERVIÇOS PARA EQUIPAMENTOS MÉDICO',
  'GE HEALTHCARE DO BRASIL COMERCIO E SERVICOS PARA EQUIPAMENTOS MEDICO'],
 'MODELO DO ATESTADO MÉDICO PARA O TESTE DE APTIDÃO FÍSICA DE INGRESSO\nATESTADO MÉDICO\nA': ['MODELO DE ATESTADO MÉDICO PARA O TESTE DE APTIDÃO FÍSICA\nATESTADO MÉDICO\nA'],
 'CENTRO DE INSTRUÇÃO E ADESTRAMENTO DE BRASÍLIA ALMIRANTE DOMINGOS DE MATTOS CORTEZ\nSD': ['CENTRO DE INSTRUÇÃO E ADESTRAMENTO DE BRASÍLIA ALMIRANTE DOMINGOS DE MATTOS CORTEZ'],
 'RETIFICAÇÃO DO EDITAL DE CONCURSO PÚBLICO PARA INGRESSO NO CORPO DE SAÚDE DA MARINHA': ['CONCURSO PÚBLICO PARA INGRESSO NO CORPO DE SAÚDE DA MARINHA',
  'EDITAL\nRETIFICAÇÃO DO CONCURSO PÚBLICO PARA INGRESSO NO CORPO DE SAÚDE DA MARINHA'],
 'COOPERATIVA DE PRODUCAO DA AGRICULTURA FAMILIAR E BIO COMBUSTIVEL DO ESTADO DO CEARA': ['COOPERATIVA DE PRODUCAO DA AGRICULTURA FAMILIAR E BIO COMBUSTIVEL DO ESTADO DO C'],
 'EXTRATO DE REGISTRO DE PREÇOS\nEXTRATO DE PREGÃO PARA REGISTRO DE PREÇOS\nREGISTRADOR': ['EXTRATO DE REGISTRO DE PRECOS\nEXTRATO DE REGISTRO DE PREÇOS R',
  'EXTRATO DE REGISTRO DE PREÇOS\nEXTRATO DE ATA DE REGISTRO DE PREÇOS N',
  'EXTRATOS DE REGISTROS DE PREÇOS\nEXTRATO DE REGISTRO DE PREÇOS R',
  'EXTRATO DE REGISTRO DE PREÇOS\nEXTRATO DE REGISTRO DE PREÇOS R'],
 'CONCURSO PÚBLICO PARA INGRESSO NOS QUADROS COMPLEMENTARES DE OFICIAIS DA MARINHA EM': ['CONCURSO PÚBLICO PARA INGRESSO NOS QUADROS COMPLEMENTARES DE OFICIAIS DA MARINHA'],
 'DESPACHO POR PERÍODO PARA EMBARCAÇÕES EMPREGADAS NA NAVEGAÇÃO DE APOIO MARÍTIMO\nO': ['DESPACHO POR PERÍODO PARA EMBARCAÇÕES EMPREGADAS NA NAVEGAÇÃO DE CABOTAGEM\nO',
  'DESPACHO POR PERÍODO PARA EMBARCAÇÕES EMPREGADAS NA NAVEGAÇÃO INTERIOR\nO'],
 'CEBW\nEXTRATO DE AUTORIZAÇÃO PARA CONTRATAÇÃO DIRETA POR DISPENSA DE LICITAÇÃO\nNUP': ['CEBW\nEXTRATO DE CONTRATAÇÃO DIRETA POR DISPENSA DE LICITAÇÃO'],
 'EDITAL DE NOTIFICAÇÃO\nNOTIFICAÇÃO DA SOLUÇÃO DE PROCESSO ADMINISTRATIVO\nPROCESSO': ['EDITAL DE NOTIFICAÇÃO\nNOTIFICAÇÃO DE SOLUÇÃO DE PROCESSO ADMINISTRATIVO\nO'],
 'ADVANCED STERILIZATION PRODUCTS DISTRIBUICAO E COMERCIO DE PRODUTOS PARA SAUDE L': ['ADVANCED STERILIZATION PRODUCTS DISTRIBUICAO E COMERCIO'],
 'CIRURGICA CERON IMPORTADORA E EXPORTADORA DE EQUIPAMENTOS HOSPITALARES E VETERIN': ['CIRURGICA CERON IMPORTADORA E EXPORTADORA DE EQUIPAMENTOS',
  'CIRURGICAS MULLET IMPORTADORA E EXPORTADORA DE EQUIPAMENTOS HOSPITALARES E ODONT',
  'CIRURGICA CERON IMPORTADORA E EXPORTADORA DE EQUIPAMENT'],
 'COOPERATIVA MISTA DOS PRODUTORES RURAIS DO PROJETO DE ASSENTAMENTO TARUMÃ MIRIM': ['COOPERATIVA MISTA DOS PRODUTORES RURAIS DO PROJETO DE ASSENTAMENTO TARUMA MIRIM'],
 'ALIANÇA CARVALHO COMÉRCIO E SERVIÇOS DE PRODUTOS INDUSTRIAIS E AUTOMOTIVOS LTDA': ['MS COMERCIO E SERVICOS DE PRODUTOS INDUSTRIAIS E AUTOMOTIVOS LTDA',
  'FENIX RIO COMERCIO E SERVICOS DE PRODUTOS INDUSTRIAIS E AUTOMOTIVOS LTDA',
  'ALIANCA CARVALHO COMERCIO E SERVICOS DE PRODUTOS INDUSTRIAIS E AUTOMOTIVOS LTDA'],
 'INTERNATIONAL SUPPLIES IMPORTACAO E COMERCIO DE PRODUTOS HOSPITALARES LTDA CNPJ': ['INTERNATIONAL SUPPLIES IMPORTACAO E COMERCIO DE PRODUTOS HOSPITALARES LTDA'],
 'CIRURGICA SAO LUIS DISTRIBUIDORA DE MEDICAMENTOS E PRODUTOS HOSPITALARES EIRELI': ['CIRURGICA SAO LUIS DISTRIBUIDORA DE MEDICAMENTOS E PROD',
  'CONQUISTA DISTRIBUIDORA DE MEDICAMENTOS E PRODUTOS HOSPITALARES LTDA',
  'CONQUISTA DISTRIBUIDORA DE MEDICAMENTOS E PRODUTOS HOSPITALARES EIRELI',
  'ZAFRA DISTRIBUIDORA DE MEDICAMENTOS E PRODUTOS HOSPITALARES LTDA',
  'IMUNOFARMA DISTRIBUIDORA DE MEDICAMENTOS E PRODUTOS HOSPITALARES LTDA'],
 'TERCEIRO SERVIÇO REGIONAL DE INVESTIGAÇÃO E PREVENÇÃO DE ACIDENTES AERONÁUTICOS': ['SEGUNDO SERVIÇO REGIONAL DE INVESTIGAÇÃO E PREVENÇÃO DE ACIDENTES AERONÁUTICOS',
  'CENTRO DE INVESTIGAÇÃO E PREVENÇÃO DE ACIDENTES AERONÁUTICOS',
  'QUINTO SERVIÇO REGIONAL DE INVESTIGAÇÃO E PREVENÇÃO DE ACIDENTES AERONÁUTICOS',
  'QUARTO SERVIÇO REGIONAL DE INVESTIGAÇÃO E PREVENÇÃO DE ACIDENTES AERONÁUTICOS'],
 'EDITAL DE NOTIFICAÇÃO\nCENTRO DE INTENDÊNCIA TECNOLÓGICO DA MARINHA EM SÃO PAULO': ['CENTRO DE INTENDÊNCIA TECNOLÓGICO DA MARINHA EM SÃO PAULO'],
 'EXTRATO DE INEXIGIBILIDADE DE LICITAÇÃO\nEXTRATO DE INEXIGIBILIDADE DE LICITAÇÃO': ['EXTRATO DE INEXIGIBILIDADE DE LICITAÇÃO\nINEXIGIBILIDADE N'],
 'DF ELETROTECNICA COMERCIO MANUTENCAO E LOCACAO DE EQUIPAMENTOS ELETRICOS EIRELI': ['DF ELETROTECNICA COMERCIO MANUTENCAO E LOCACAO DE EQUIPAMENTOS ELETRICOS LTDA',
  'DF ELETROTECNICA COMERCIO MANUTENCAO E LOCACAO DE EQUIP'],
 'CENTRO DE PREPARAÇÃO DE OFICIAIS DA RESERVA E COLÉGIO MILITAR DE BELO HORIZONTE': ['CENTRO DE PREPARAÇÃO DE OFICIAIS DA RESERVA DE BELO HORIZONTE'],
 'LIMP DESC COMERCIO DE MATERIAIS DE LIMPEZA E DESCARTAVEIS EM GERAL EIRELI CNPJ': ['LIMP DESC COMÉRCIO DE MATERIAIS DE LIMPEZA E DESCARTÁVEIS EM GERAL EIRELI',
  'LIMP DESC COMERCIO DE MATERIAIS DE LIMPEZA E DESCARTAVEIS EM GERAL LTDA',
  'LIMP DESC COMERCIO DE MATERIAIS DE LIMPEZA E DESCARTAVEIS EM GERAL EIRELI',
  'LIMP DESC COMERCIO DE MATERIAIS DE LIMPEZA E DESCARTAVE'],
 'ANEXO C\nRELAÇÃO DE ASSUNTOS PARA O EXAME INTELECTUAL\nDO CONCURSO DE ADMISSÃO\nI': ['ANEXO C\nRELAÇÃO DE ASSUNTOS PARA OS EXAMES INTELECTUAIS\nI'],
 'TECNO TRADE COMERCIO E SERVICOS DE EQUIPAMENTOS ELETRONICOS E SONORIZACAO LTDA': ['TECNO TRADE COMERCIO E SERVICOS DE EQUIPAMENTOS ELETRON'],
 'COOPERATIVA DE ECONOMIA DA AGRICULTURA FAMILIAR DA MICROREGIÃO DE JUIZ DE FORA': ['COOPERATIVA DE ECONOMIA DA AGRICULTURA FAMILIAR DA MICROREGIAO DE JUIZ DE FORA',
  'COOPERATIVA DE ECONOMIA DA AGRICULTURA FAMILIAR DA MIC'],
 'AVIO DO BRASIL FABRICACAO E MANUTENCAO DE MOTORES E PECAS PARA AERONAVES LTDA': ['AVIO DO BRASIL FABRICAÇÃO E MANUTENÇÃO DE MOTORES E PEÇAS PARA AERONAVES LTDA'],
 'SERVIÇO DE RECRUTAMENTO E PREPARO DE PESSOAL DA AERONÁUTICA DO RIO DE JANEIRO': ['SERVIÇO DE RECRUTAMENTO E PREPARO DE PESSOAL DA AERONÁUTICA DE CANOAS',
  'SERVIÇO DE RECRUTAMENTO E PREPARO DE PESSOAL DA AERONÁUTICA DE RECIFE',
  'SERVIÇO DE RECRUTAMENTO E PREPARO DE PESSOAL DA AERONÁUTICA DE BELÉM'],
 'HMA COMERCIO E ATACADISTA DE PRODUTOS DE INFORMATICA E ELETROELETRONICOS LTDA': ['EGC COMERCIO E ATACADISTA DE INFORMATICA E ELETROELETRONICOS EIRELI'],
 'PROCEDIMENTO DE VERIFICAÇÃO DOCUMENTAL COMPLEMENTAR PARA PESSOAS QUILOMBOLAS': ['PROCEDIMENTO DE VERIFICAÇÃO DOCUMENTAL COMPLEMENTAR PARA PESSOAS INDÍGENAS'],
 'RECIBO DO RECURSO QUANTO AO PROCEDIMENTO DE HETEROIDENTIFICAÇÃO COMPLEMENTAR': ['RECURSO QUANTO AO PROCEDIMENTO DE HETEROIDENTIFICAÇÃO COMPLEMENTAR',
  'E DO PROCEDIMENTO DE HETEROIDENTIFICAÇÃO COMPLEMENTAR'],
 'SOLUCOES SERVICOS DE LOCACAO DE MAQUINAS E EQUIPAMENTOS PARA ESCRITORIO LTDA': ['SOLUCOES SERVICOS DE LOCACAO DE MAQUINAS E EQUIPAMENTO'],
 'COOPERATIVA DE AGRICULTORES E AGROINDUSTRIAS FAMILIARES E CAXIAS DO SUL LTDA': ['COOPERATIVA DE AGRICULTORES E AGROINDÚSTRIAS FAMILIARES DE CAXIAS DO SUL',
  'COOPERATIVA DE AGRICULTORES E AGROINDUSTRIAS FAMILIARES'],
 'COOPERATIVA AGROINDUSTRIAL DA AGRICULTURA FAMILIAR DO TERRITÓRIO ENTRE RIOS': ['COOPERATIVA AGROINDUSTRIAL DA AGRICULTURA FAMILIAR DO TERRITORIO ENTRE RIOS'],
 'EDITAL DE NOTIFICAÇÃO\nO CENTRO DE INTENDÊNCIA DA MARINHA EM PARADA DE LUCAS': ['EDITAL DE NOTIFICAÇÃO\nCENTRO DE INTENDÊNCIA DA MARINHA EM PARADA DE LUCAS'],
 'EDITAL DE INTIMAÇÃO\nO ORDENADOR DE DESPESAS DO GRUPAMENTO DE APOIO DE NATAL': ['EDITAL DE INTIMAÇÃO\nO ORDENADOR DE DESPESAS DA BASE AÉREA DE NATAL',
  'EDITAL DE INTIMAÇÃO\nO ORDENADORA DE DESPESAS DA BASE AÉREA DE NATAL',
  'O ORDENADOR DE DESPESAS DO GRUPAMENTO DE APOIO DE NATAL'],
 'COOPERATIVA DE USUARIOS DE AERONAVES EM REGIME DE PROPRIEDADE COMPARTILHADA': ['COOP DE USUARIOS DE AER EM REGIME DE PROP COMPARTILHADA'],
 'VALDANHA ROMERO COMERCIO E REPRESENTACAO DE EQUIPAMENTOS FRIGORIFICOS LTDA': ['VALDANHA ROMERO COMERCIO E REPRESENTACAO DE EQUIPAMENTO'],
 'COOPERATIVA DOS MÉDICOS ANESTESIOLOGISTAS DO ESTADO DO RIO GRANDE DO NORTE': ['COOPERATIVA DOS MEDICOS ANESTESIOLOGISTAS DO ESTADO DE MATO GROSSO',
  'COOPERATIVA DOS MEDICOS ANESTESIOLOGISTASDO ESTADO DO RIO GRANDE',
  'COOPERATIVA DOS MEDICOS ANESTESIOLOGISTAS DO ESTADO DO RIO GRANDE'],
 'AVISO DE INEXIGIBILIDADE DE LICITAÇÃO\nO GRUPAMENTO DE APOIO DE LAGOA SANTA': ['AVISO DE INEXIGIBILIDADE DE LICITAÇÃO\nO GRUPAMENTO DE APOIO LOGÍSTICO'],
 'COOPERATIVA MISTA DOS PRODUTORES RURAIS NA AGRICULTURA FAMILIAR DA PARAIBA': ['COOPERATIVA MISTA DOS PRODUTORES RURAIS NA AGRICULTURA'],
 'MARIMAX COMERCIO E IMPORTACAO DE PRODUTOS PARA SAUDE E VETERINARIOS EIRELI': ['MARIMAX COMERCIO E IMPORTACAO DE PRODUTOS PARA SAUDE E'],
 'PARTES\nASPECTOS AVALIADOS\nPONTOS DEBITADOS POR ERRO COMETIDO\nI\nEXPRESSÃO\nP': ['PARTE\nASPECTOS AVALIADOS\nPONTOS DEBITADOS POR ERRO COMETIDO\nI\nEXPRESSÃO\nP'],
 'MEGA COMERCIO ATACADISTA DE ROUPAS E ACESSORIOS PARA USO PROFISSIONAL LTDA': ['MEGA COMERCIO ATACADISTA DE ROUPAS E ACESSORIOS PARA US'],
 'COOPERATIVAS DA AGRICULTURA FAMILIAR E ECONOMIA SOLIDARIA DO POTENGI CNPJ': ['COOPERATIVA DA AGRICULTURA FAMILIAR E ECONOMIA SOLIDÁRIA DE PINDORETAMA'],
 'QUALITY LUX COMERCIO E INDUSTRIA DE MATERIAIS ELETRICOS E ILUMINACAO LTDA': ['A ILUMINADA COMERCIO E SERVICOS DE MATERIAIS ELETRICOS E ILUMINACAO LTDA',
  'QUALITY LUX COMERCIO E INDUSTRIA DE MATERIAIS ELETRICO'],
 'TOTAL MED COMERCIO E IMPORTACAO DE PRODUTOS MEDICO HOSPITALARES LTDA CNPJ': ['MED COMERCIO E DISTRIBUICAO DE PRODUTOS HOSPITALARES LTDA CNPJ'],
 'FENIX SOLUCOES COMERCIO DE EQUIPAMENTOS E SUPRIMENTOS DE INFORMATICA LTDA': ['BFF COMERCIO DE EQUIPAMENTOS E SUPRIMENTOS DE INFORMATI'],

In [55]:
def find_substring(s_key, s_list):
    s_list.append(s_key)
    for s in set(s_list):
        align = rapidfuzz_fuzz.partial_ratio_alignment(min(s_key, s, key=len), max(s_key, s, key=len))
        s_key = min(s_key, s, key=len)[align.dest_start: align.dest_end]
    return {s_key:list(set(s_list))}

In [56]:
lean_matches = {}
for item in maybe_matches.items():
    lean_matches.update(find_substring(*item))

In [57]:
lean_matches

{'MARINHA': ['CAIXA DE CONSTRUÇÕES DE CASAS PARA O PESSOAL DA MARINHA',
  'O PRESIDENTE DA CAIXA DE CONSTRUÇÕES DE CASAS PARA O PESSOAL DA MARINHA'],
 'PROVA ESCRITA DE CONHECIMENTOS PROFISSIONAIS PARA INGRESSO NO QUADRO COMPLEMENTAR DO CORPO DE INTENDENTES DA MARINHA': ['DE CONHECIMENTOS PROFISSIONAIS\nPROGRAMA E BIBLIOGRAFIA PARA A PROVA ESCRITA DE CONHECIMENTOS PROFISSIONAIS PARA INGRESSO NO QUADRO COMPLEMENTAR DO CORPO DE INTENDENTES DA MARINHA',
  'PROGRAMA E BIBLIOGRAFIA PARA A PROVA ESCRITA DE CONHECIMENTOS PROFISSIONAIS PARA INGRESSO NO QUADRO COMPLEMENTAR DO CORPO DE INTENDENTES DA MARINHA'],
 'MINISTÉRIO DA DEFESA\nCOMANDO DA AERONÁUTICA\nESCOLA DE ESPECIALISTAS DE AERONÁUTICA\nAUTORIZAÇÃO PARA CANDIDATO MENOR DE I': ['MINISTÉRIO DA DEFESA\nCOMANDO DA AERONÁUTICA\nESCOLA DE ESPECIALISTAS DE AERONÁUTICA\nAUTORIZAÇÃO PARA CANDIDATO MENOR QUE OPTOU PELO SISTEMA DE RESERVA DE VAGAS',
  'MINISTÉRIO DA DEFESA\nCOMANDO DA AERONÁUTICA\nESCOLA DE ESPECIALISTAS DE AERONÁUTICA\nAUTORIZAÇÃO PARA CANDIDATO MENOR DE IDADE\nE'],
 '': ['R M', 'RC M'],
 'MINISTERIO DA DEFESA\nCOMANDO DA AERONAUTICA\nCOMISSÃO AERONÁUTICA BRASILEIRA EM WASHINGTON\n': ['MINISTERIO DA DEFESA\nCOMANDO DA AERONAUTICA\nCOMISSÃO AERONÁUTICA BRASILEIRA EM WASHINGTON\nAQUISIÇÃO DE SPARE PARTS PARA SUPORTE',
  'MINISTERIO DA DEFESA\nCOMANDO DA AERONAUTICA\nCOMISSÃO AERONÁUTICA BRASILEIRA EM WASHINGTON\nO',
  'MINISTERIO DA DEFESA\nCOMANDO DA AERONAUTICA\nCOMISSÃO AERONÁUTICA BRASILEIRA EM WASHINGTON\nA'],
 'AVISO DE INEXIGIBILIDADE DE LICITAÇÃO\nO PARQUE DE MATERIAL DE ELETRÔNICA DA AERONÁUTICA DO RIO DE JANEIRO': ['AVISO DE INEXIGIBILIDADE DE LICITAÇÃO\nO PARQUE DE MATERIAL DE ELETRÔNICA DA AERONÁUTICA DO RIO DE JANEIRO',
  'AVISO DE INEXIGIBILIDADE DE LICITAÇÃO\nA ADMINISTRAÇÃO DO PARQUE DE MATERIAL DE ELETRÔNICA DA AERONÁUTICA DO RIO DE JANEIRO'],
 'MINISTÉRIO DA DEFESA\nCOMANDO DA AERONÁUTICA\nRECURSO QUANTO AO TESTE DE AVALIAÇÃO DO CONDICIONAMENTO FÍSICO': ['MINISTÉRIO DA DEFESA\nCOMANDO DA AERONÁUTICA\nDECLARAÇÃO PARA A REALIZAÇÃO DO TESTE DE AVALIAÇÃO E CONDICIONAMENTO FÍSICO\nE',
  'MINISTÉRIO DA DEFESA\nCOMANDO DA AERONÁUTICA\nRECURSO QUANTO AO TESTE DE AVALIAÇÃO DO CONDICIONAMENTO FÍSICO'],
 'S DE FORMAÇÃO E GRADUAÇÃO DE SARGENTOS DAS ÁREAS GERAL': ['CONCURSO PÚBLICO PARA ADMISSÃO E MATRÍCULA NOS CURSOS DE FORMAÇÃO E GRADUAÇÃO DE SARGENTOS DAS ÁREAS GERAL',
  'CALENDÁRIO ANUAL DO CONCURSO DE ADMISSÃO PARA MATRÍCULA NOS CURSOS DE FORMAÇÃO E GRADUAÇÃO DE SARGENTOS DAS ÁREAS GERAL'],
 'AQUISIÇÃO DE MATERIAIS HOSPITALARES DE USO COMUM PARA ATENDER ASORGANIZAÇÕES DE SAÚDE DA AERONÁUTICA PARA O ANO DE': ['AQUISIÇÃO DE MATERIAIS HOSPITALARES DE USO COMUM PARA ATENDER ASORGANIZAÇÕES DE SAÚDE DA AERONÁUTICA PARA O ANO DE',
  'AQUISIÇÃO DE MATERIAIS HOSPITALARES DE USO COMUM PARA ATENDER AS ORGANIZAÇÕES DE SAÚDE DA AERONÁUTICA PARA O ANO DE'],
 'CONCURSO DE ADMISSÃO AO CURSO DE FORMAÇÃO DE OFICIAIS DA ATIVA DO QUADRO DE ENGENHEIROS MILITARES': ['CONCURSO DE ADMISSÃO AOS CURSOS DE FORMAÇÃO E GRADUAÇÃO DE OFICIAIS DA ATIVA DO QUADRO DE ENGENHEIROS MILITARES',
  'CONCURSO DE ADMISSÃO AOS CURSOS DE FORMAÇÃO E GRADUAÇÃO DE OFICIAIS DA RESERVA DO QUADRO DE ENGENHEIROS MILITARES',
  'CONCURSO DE ADMISSÃO AO CURSO DE FORMAÇÃO DE OFICIAIS DA ATIVA DO QUADRO DE ENGENHEIROS MILITARES'],
 'MINISTÉRIO DA DEFESA\nCOMANDO DA AERONÁUTICA\nDECLARAÇÃO QUANTO A NÃO I': ['MINISTÉRIO DA DEFESA\nCOMANDO DA AERONÁUTICA\nDECLARAÇÃO QUANTO A NÃO INVESTIDURA EM CARGO',
  'MINISTÉRIO DA DEFESA\nCOMANDO DA AERONÁUTICA\nDECLARAÇÃO QUANTO INVESTIDURA OU NÃO INVESTIDURA EM CARGO PÚBLICO\nE'],
 'O PRESENTE TERMO ADITIVO TEM POR FINALIDADE A PRORROGAÇÃO DO PRAZO DE VIGÊNCIA DO CON': ['O PRESENTE TERMO ADITIVO TEM POR FINALIDADE A PRORROGAÇÃO DO PRAZO DE VIGÊNCIA DO CONTRATO N',
  'O PRESENTE TERMO ADITIVO TEM POR FINALIDADE A PRORROGAÇÃO DO PRAZO DE VIGÊNCIA DO TERMO DE CREDENCIAMENTO N'],
 'O DE FORMAÇÃO DO INSTITUTO MILITAR DE ENGENHARIA': ['EFETIVAÇÃO DE MATRÍCULA NO PRIMEIRO ANO DO CURSO DE FORMAÇÃO E GRADUAÇÃO DO INSTITUTO MILITAR DE ENGENHARIA',
  'EFETIVAÇÃO DE MATRÍCULA NO CURSO DE FORMAÇÃO DO INSTITUTO MILITAR DE ENGENHARIA'],
 'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\n': ['NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nSTARNAV AQUARIUS',
  'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nMAERSK VENTURA',
  'NOME DA EMBARCAÇÃO\nNÚMERO DE INSCRIÇÃO\nLOCAL DE INSCRIÇÃO\nPORTOS DE OPERAÇÃO AUTORIZADOS\nCBO ISABELLA'],
 'CONCURSO PÚBLICO DE ADMISSÃO AO CURSO DE FORMAÇÃO PARA INGRESSO NO CORPO AUXILIAR DE PRAÇAS DA MARINHA': ['CONCURSO PÚBLICO DE ADMISSÃO AO CURSO DE FORMAÇÃO PARA INGRESSO NO CORPO AUXILIAR DE PRAÇAS DA MARINHA EM',
  'CONCURSO PÚBLICO DE ADMISSÃO AO CURSO DE FORMAÇÃO PARA INGRESSO NO CORPO AUXILIAR DE PRAÇAS DA MARINHA'],
 'DE DEFESA AÉREA E CONTROLE DE TRÁFEGO AÉREO': ['AVISO DE PENALIDADE\nO COMANDANTE DO SEGUNDO CENTRO INTEGRADO DE DEFESA AÉREA E CONTROLE DE TRÁFEGO AÉREO',
  'PARA O SEGUNDO CENTRO INTEGRADO DE DEFESA AÉREA E CONTROLE DE TRÁFEGO AÉREO'],
 'CONTRATO DE ATIVIDADE ESPECIAL PARA ATENDER ENCARGOS TEMPORÁRIOS DE OBRAS E SERVIÇOS DE ENGENHARIA': ['CONTRATO DE ATIVIDADE ESPECIAL PARA ATENDER ENCARGOS TEMPORÁRIOS DE OBRAS E SERVIÇOS DE ENGENHARIA',
  'CONTRATO DE ATIVIDADE ESPECIAL PARA ATENDER ENCARGOS TEMPORÁRIOS DE OBRAS E SERVIÇOS DE ENGENHARIA\nP'],
 'E MATERIAL DE CONSTRUCAO LTDA': ['SGRH SERVICOS DE GESTAO DE RECURSOS HUMANOS CONSTRUCOES E COMERCIO DE MATERIAIS DE CONSTRUCAO LTDA',
  'SGRH SERVICOS DE CONSTRUCOES E COMERCIO DE MATERIAL DE CONSTRUCAO LTDA'],
 'FEDERACAO DE COOPERATIVAS DA AGRICULTURA FAMILIAR E ECONOMIA SOLIDARIA DO ESTADO': ['FEDERAÇÃO DE COOPERATIVAS DA AGRICULTURA FAMILIAR E ECONOMIA SOLIDÁRIA DO ESTADO DE MINAS GERAIS',
  'FEDERACAO DE COOPERATIVAS DA AGRICULTURA FAMILIAR E ECONOMIA SOLIDARIA DO ESTADO'],
 'PARA A PRESTAÇÃO DO SERVIÇO MILITAR VOLUNTÁRIO COMO PRAÇAS TEMPORÁRIAS DA MARINHA DO BRASIL': ['PARA A PRESTAÇÃO DO SERVIÇO MILITAR VOLUNTÁRIO COMO PRAÇAS TEMPORÁRIAS DA MARINHA DO BRASIL',
  'PARA A PRESTAÇÃO DO SERVIÇO MILITAR VOLUNTÁRIO COMO PRAÇAS TEMPORÁRIAS DA MARINHA DO BRASIL\nO C'],
 'ZAÇÕES DE SAÚDE DA AERONÁUTICA': ['AQUISIÇÃO DE MATERIAIS DE HEMOTERAPIA PARA AS ORGANIZAÇÕES DE SAÚDE DA AERONÁUTICA',
  'AQUISIÇÃO DE MATERIAIS ESPECÍFICOS DE ODONTOLOGIA PARA AS ORGANIZAÇÕES DE SAÚDE DA AERONÁUTICA'],
 'MODELO DE DECLARAÇÃO DE APRESENTAÇÃO DE COMPROVANTE DE CONCLUSÃO DE CURSO': ['MODELO DE DECLARAÇÃO DE APRESENTAÇÃO DE COMPROVANTE DE CONCLUSÃO DE CURSO',
  'MODELO DE DECLARAÇÃO DE APRESENTAÇÃO DE COMPROVANTE DE CONCLUSÃO DE CURSO\nDECLARAÇÃO\nE',
  'MODELO DE DECLARAÇÃO DE APRESENTAÇÃO DE COMPROVANTE DE CONCLUSÃO DE CURSO DE RESIDÊNCIA MÉDICA'],
 ' REGISTRO DE PREÇOS\nCENTRO DE INSTRUÇÃO ALMIRANTE ALEXANDRINO': ['EXTRATO DE REGISTRO DE PREÇO\nCENTRO DE INSTRUÇÃO ALMIRANTE ALEXANDRINO\nP',
  'EXTRATO DE REGISTRO DE PREÇOS\nCENTRO DE INSTRUÇÃO ALMIRANTE ALEXANDRINO\nP',
  'AVISO DE REGISTRO DE PREÇOS\nCENTRO DE INSTRUÇÃO ALMIRANTE ALEXANDRINO',
  'CENTRO DE INSTRUÇÃO ALMIRANTE ALEXANDRINO\nPUBLICAÇÃO TRIMESTRAL\nA',
  'AVISO DE REGISTRO DE PREÇOS\nCENTRO DE INSTRUÇÃO ALMIRANTE ALEXANDRINO\nPUBLICAÇÃO TRIMESTRAL\nA'],
 'CONCURSO PÚBLICO PARA INGRESSO NO QUADRO TÉCNICO DO CORPO AUXILIAR DA MARINHA': ['CONCURSO PÚBLICO PARA INGRESSO NO QUADRO TÉCNICO DO CORPO AUXILIAR DA MARINHA',
  'CONCURSO PÚBLICO PARA INGRESSO NO QUADRO TÉCNICO DO CORPO AUXILIAR DA MARINHA EM',
  'CONCURSO PÚBLICO PARA INGRESSO NO QUADRO DE CAPELÃES NAVAIS DO CORPO AUXILIAR DA MARINHA EM'],
 'E INSCRIÇÃO': ['REQUERIMENTO DE SOLICITAÇÃO DE ISENÇÃO DE PAGAMENTO DE TAXA DE INSCRIÇÃO',
  'RECURSO QUANTO AO INDEFERIMENTO DA SOLICITAÇÃO DE ISENÇÃO DO PAGAMENTO DA TAXA DE INSCRIÇÃO'],
 'DEFENSER MILITAR AVENTURA E OUTDOOR COMERCIO DE EQUIPAMENTOS E ARTIGOS DE SEGURA': ['DEFENSER MILITAR AVENTURA E OUTDOOR COMERCIO DE EQUIPAMENTOS E ARTIGOS DE SEGURA',
  'DEFENSER MILITAR AVENTURA E OUTDOOR COMERCIO DE EQUIPAMENTOS E ARTIGOS DE SEGURANÇA EIRELI'],
 'ED INFO SUPRIMENTOS DE INFORMATICA INDUSTRIA EDITORIAL COMERCIO E SERVICOS GRAFI': ['ED INFO SUPRIMENTOS DE INFORMATICA INDUSTRIA EDITORIAL COMERCIO E SERVICOS GRAFICOS EIRELI',
  'ED INFO SUPRIMENTOS DE INFORMATICA INDUSTRIA EDITORIAL COMERCIO E SERVICOS GRAFI'],
 'MODELO DE DECLARAÇÃO DE APRESENTAÇÃO DO REGISTRO PROFISSIONAL\nDECLARAÇÃO\nE': ['MODELO DE DECLARAÇÃO DE APRESENTAÇÃO DO REGISTRO PROFISSIONAL\nDECLARAÇÃO\nE',
  'MODELO DE DECLARAÇÃO DE APRESENTAÇÃO DE COMPROVANTE DO REGISTRO PROFISSIONAL\nDECLARAÇÃO\nE'],
 'FORMULAÇÃO DE QUESTÕES DAS PROVAS ESCRITAS E AOS SEUS RESPECTIVOS GABARITOS': ['FORMULAÇÃO DE QUESTÕES DAS PROVAS OBJETIVAS E AOS SEUS RESPECTIVOS GABARITOS PROVISÓRIOS',
  'FORMULAÇÃO DE QUESTÕES DAS PROVAS ESCRITAS E AOS SEUS RESPECTIVOS GABARITOS'],
 'CENTRO DE INSTRUÇÃO E ADESTRAMENTO AERONAVAL ALMIRANTE JOSÉ MARIA DO AMARAL OLIVEIRA': ['CENTRO DE INSTRUÇÃO E ADESTRAMENTO AERONAVAL ALMIRANTE JOSÉ MARIA DO AMARAL OLIVEIRA',
  'CENTRO DE INSTRUÇÃO E ADESTRAMENTO AERONAVAL ALMIRANTE JOSÉ MARIA DO AMARAL OLIVEIRA\nSO'],
 'GE HEALTHCARE DO BRASIL COMÉRCIO E SERVIÇOS PARA EQUIPAMENTOS MÉDICO': ['GE HEALTHCARE DO BRASIL COMÉRCIO E SERVIÇOS PARA EQUIPAMENTOS MÉDICO',
  'GE HEALTHCARE DO BRASIL COMERCIO E SERVICOS PARA EQUIPAMENTOS MEDICO',
  'GE HEALTHCARE DO BRASIL COMÉRCIO E SERVIÇOS PARA EQUIPAMENTOS MÉDICOS HOSPITALARES LTDA'],
 'MODELO DE ATESTADO MÉDICO PARA O TESTE DE APTIDÃO FÍSICA': ['MODELO DE ATESTADO MÉDICO PARA O TESTE DE APTIDÃO FÍSICA\nATESTADO MÉDICO\nA',
  'MODELO DO ATESTADO MÉDICO PARA O TESTE DE APTIDÃO FÍSICA DE INGRESSO\nATESTADO MÉDICO\nA'],
 'CENTRO DE INSTRUÇÃO E ADESTRAMENTO DE BRASÍLIA ALMIRANTE DOMINGOS DE MATTOS CORTEZ': ['CENTRO DE INSTRUÇÃO E ADESTRAMENTO DE BRASÍLIA ALMIRANTE DOMINGOS DE MATTOS CORTEZ',
  'CENTRO DE INSTRUÇÃO E ADESTRAMENTO DE BRASÍLIA ALMIRANTE DOMINGOS DE MATTOS CORTEZ\nSD'],
 'COOPERATIVA DE PRODUCAO DA AGRICULTURA FAMILIAR E BIO COMBUSTIVEL DO ESTADO DO C': ['COOPERATIVA DE PRODUCAO DA AGRICULTURA FAMILIAR E BIO COMBUSTIVEL DO ESTADO DO CEARA',
  'COOPERATIVA DE PRODUCAO DA AGRICULTURA FAMILIAR E BIO COMBUSTIVEL DO ESTADO DO C'],
 'EXTRATO DE REGISTRO DE PRECOS\nEXTRATO DE REGI': ['EXTRATO DE REGISTRO DE PRECOS\nEXTRATO DE REGISTRO DE PREÇOS R',
  'EXTRATO DE REGISTRO DE PREÇOS\nEXTRATO DE ATA DE REGISTRO DE PREÇOS N',
  'EXTRATO DE REGISTRO DE PREÇOS\nEXTRATO DE REGISTRO DE PREÇOS R',
  'EXTRATO DE REGISTRO DE PREÇOS\nEXTRATO DE PREGÃO PARA REGISTRO DE PREÇOS\nREGISTRADOR',
  'EXTRATOS DE REGISTROS DE PREÇOS\nEXTRATO DE REGISTRO DE PREÇOS R'],
 'CONCURSO PÚBLICO PARA INGRESSO NOS QUADROS COMPLEMENTARES DE OFICIAIS DA MARINHA': ['CONCURSO PÚBLICO PARA INGRESSO NOS QUADROS COMPLEMENTARES DE OFICIAIS DA MARINHA',
  'CONCURSO PÚBLICO PARA INGRESSO NOS QUADROS COMPLEMENTARES DE OFICIAIS DA MARINHA EM'],
 'DESPACHO POR PERÍODO PARA EMBARCAÇÕES EMPREGADAS NA NAVEGAÇÃO ': ['DESPACHO POR PERÍODO PARA EMBARCAÇÕES EMPREGADAS NA NAVEGAÇÃO DE CABOTAGEM\nO',
  'DESPACHO POR PERÍODO PARA EMBARCAÇÕES EMPREGADAS NA NAVEGAÇÃO INTERIOR\nO',
  'DESPACHO POR PERÍODO PARA EMBARCAÇÕES EMPREGADAS NA NAVEGAÇÃO DE APOIO MARÍTIMO\nO'],
 'EDITAL DE NOTIFICAÇÃO\nNOTIFICAÇÃO DE SOLUÇÃO DE PROCESSO ADMINISTRATIVO\n': ['EDITAL DE NOTIFICAÇÃO\nNOTIFICAÇÃO DA SOLUÇÃO DE PROCESSO ADMINISTRATIVO\nPROCESSO',
  'EDITAL DE NOTIFICAÇÃO\nNOTIFICAÇÃO DE SOLUÇÃO DE PROCESSO ADMINISTRATIVO\nO'],
 'ADVANCED STERILIZATION PRODUCTS DISTRIBUICAO E COMERCIO': ['ADVANCED STERILIZATION PRODUCTS DISTRIBUICAO E COMERCIO',
  'ADVANCED STERILIZATION PRODUCTS DISTRIBUICAO E COMERCIO DE PRODUTOS PARA SAUDE L'],
 'CIRURGICA CERON IMPORTADORA E EXPORTADORA DE EQUIPAMENT': ['CIRURGICA CERON IMPORTADORA E EXPORTADORA DE EQUIPAMENTOS',
  'CIRURGICAS MULLET IMPORTADORA E EXPORTADORA DE EQUIPAMENTOS HOSPITALARES E ODONT',
  'CIRURGICA CERON IMPORTADORA E EXPORTADORA DE EQUIPAMENT',
  'CIRURGICA CERON IMPORTADORA E EXPORTADORA DE EQUIPAMENTOS HOSPITALARES E VETERIN'],
 'COOPERATIVA MISTA DOS PRODUTORES RURAIS DO PROJETO DE ASSENTAMENTO TARUMÃ MIRIM': ['COOPERATIVA MISTA DOS PRODUTORES RURAIS DO PROJETO DE ASSENTAMENTO TARUMA MIRIM',
  'COOPERATIVA MISTA DOS PRODUTORES RURAIS DO PROJETO DE ASSENTAMENTO TARUMÃ MIRIM'],
 'INTERNATIONAL SUPPLIES IMPORTACAO E COMERCIO DE PRODUTOS HOSPITALARES LTDA': ['INTERNATIONAL SUPPLIES IMPORTACAO E COMERCIO DE PRODUTOS HOSPITALARES LTDA CNPJ',
  'INTERNATIONAL SUPPLIES IMPORTACAO E COMERCIO DE PRODUTOS HOSPITALARES LTDA'],
 'CIRURGICA SAO LU': ['CIRURGICA SAO LUIS DISTRIBUIDORA DE MEDICAMENTOS E PROD',
  'CONQUISTA DISTRIBUIDORA DE MEDICAMENTOS E PRODUTOS HOSPITALARES LTDA',
  'CONQUISTA DISTRIBUIDORA DE MEDICAMENTOS E PRODUTOS HOSPITALARES EIRELI',
  'CIRURGICA SAO LUIS DISTRIBUIDORA DE MEDICAMENTOS E PRODUTOS HOSPITALARES EIRELI',
  'ZAFRA DISTRIBUIDORA DE MEDICAMENTOS E PRODUTOS HOSPITALARES LTDA',
  'IMUNOFARMA DISTRIBUIDORA DE MEDICAMENTOS E PRODUTOS HOSPITALARES LTDA'],
 'TECNOLÓGICO DA MARINHA EM SÃO PAULO': ['EDITAL DE NOTIFICAÇÃO\nCENTRO DE INTENDÊNCIA TECNOLÓGICO DA MARINHA EM SÃO PAULO',
  'CENTRO DE INTENDÊNCIA TECNOLÓGICO DA MARINHA EM SÃO PAULO'],
 'EXTRATO DE INEXIGIBILIDADE DE LICITAÇÃO\nINEXIGIBILIDA': ['EXTRATO DE INEXIGIBILIDADE DE LICITAÇÃO\nEXTRATO DE INEXIGIBILIDADE DE LICITAÇÃO',
  'EXTRATO DE INEXIGIBILIDADE DE LICITAÇÃO\nINEXIGIBILIDADE N'],
 'DF ELETROTECNICA COMERCIO MANUTENCAO E LOCACAO DE EQUIP': ['DF ELETROTECNICA COMERCIO MANUTENCAO E LOCACAO DE EQUIPAMENTOS ELETRICOS LTDA',
  'DF ELETROTECNICA COMERCIO MANUTENCAO E LOCACAO DE EQUIPAMENTOS ELETRICOS EIRELI',
  'DF ELETROTECNICA COMERCIO MANUTENCAO E LOCACAO DE EQUIP'],
 'CENTRO DE PREPARAÇÃO DE OFICIAIS DA RESERVA DE': ['CENTRO DE PREPARAÇÃO DE OFICIAIS DA RESERVA DE BELO HORIZONTE',
  'CENTRO DE PREPARAÇÃO DE OFICIAIS DA RESERVA E COLÉGIO MILITAR DE BELO HORIZONTE'],
 'LIMP DESC COMERCIO DE MATERIAIS DE LIMPEZA E DESCARTAVE': ['LIMP DESC COMÉRCIO DE MATERIAIS DE LIMPEZA E DESCARTÁVEIS EM GERAL EIRELI',
  'LIMP DESC COMERCIO DE MATERIAIS DE LIMPEZA E DESCARTAVEIS EM GERAL EIRELI',
  'LIMP DESC COMERCIO DE MATERIAIS DE LIMPEZA E DESCARTAVE',
  'LIMP DESC COMERCIO DE MATERIAIS DE LIMPEZA E DESCARTAVEIS EM GERAL EIRELI CNPJ',
  'LIMP DESC COMERCIO DE MATERIAIS DE LIMPEZA E DESCARTAVEIS EM GERAL LTDA'],
 'ANEXO C\nRELAÇÃO DE ASSUNTOS PARA OS EXAMES INTELECT': ['ANEXO C\nRELAÇÃO DE ASSUNTOS PARA OS EXAMES INTELECTUAIS\nI',
  'ANEXO C\nRELAÇÃO DE ASSUNTOS PARA O EXAME INTELECTUAL\nDO CONCURSO DE ADMISSÃO\nI'],
 'TECNO TRADE COMERCIO E SERVICOS DE EQUIPAMENTOS ELETRON': ['TECNO TRADE COMERCIO E SERVICOS DE EQUIPAMENTOS ELETRONICOS E SONORIZACAO LTDA',
  'TECNO TRADE COMERCIO E SERVICOS DE EQUIPAMENTOS ELETRON'],
 'COOPERATIVA DE ECONOMIA DA AGRICULTURA FAMILIAR DA MIC': ['COOPERATIVA DE ECONOMIA DA AGRICULTURA FAMILIAR DA MICROREGIAO DE JUIZ DE FORA',
  'COOPERATIVA DE ECONOMIA DA AGRICULTURA FAMILIAR DA MIC',
  'COOPERATIVA DE ECONOMIA DA AGRICULTURA FAMILIAR DA MICROREGIÃO DE JUIZ DE FORA'],
 'AVIO DO BRASIL FABRICACAO E MANUTENCAO DE MOTORES E PECAS PARA AERONAVES LTDA': ['AVIO DO BRASIL FABRICAÇÃO E MANUTENÇÃO DE MOTORES E PEÇAS PARA AERONAVES LTDA',
  'AVIO DO BRASIL FABRICACAO E MANUTENCAO DE MOTORES E PECAS PARA AERONAVES LTDA'],
 'SERVIÇO DE RECRUTAMENTO E PREPARO DE PESSOAL DA AERONÁUTICA DE': ['SERVIÇO DE RECRUTAMENTO E PREPARO DE PESSOAL DA AERONÁUTICA DO RIO DE JANEIRO',
  'SERVIÇO DE RECRUTAMENTO E PREPARO DE PESSOAL DA AERONÁUTICA DE CANOAS',
  'SERVIÇO DE RECRUTAMENTO E PREPARO DE PESSOAL DA AERONÁUTICA DE RECIFE',
  'SERVIÇO DE RECRUTAMENTO E PREPARO DE PESSOAL DA AERONÁUTICA DE BELÉM'],
 'COMERCIO E ATACADISTA DE INFORMATICA E ELETROELETRONICOS EIRELI': ['HMA COMERCIO E ATACADISTA DE PRODUTOS DE INFORMATICA E ELETROELETRONICOS LTDA',
  'EGC COMERCIO E ATACADISTA DE INFORMATICA E ELETROELETRONICOS EIRELI'],
 'PROCEDIMENTO DE VERIFICAÇÃO DOCUMENTAL COMPLEMENTAR PARA PESSOAS ': ['PROCEDIMENTO DE VERIFICAÇÃO DOCUMENTAL COMPLEMENTAR PARA PESSOAS QUILOMBOLAS',
  'PROCEDIMENTO DE VERIFICAÇÃO DOCUMENTAL COMPLEMENTAR PARA PESSOAS INDÍGENAS'],
 ' PROCEDIMENTO DE HETEROIDENTIFICAÇÃO COMPLEMENTAR': ['RECIBO DO RECURSO QUANTO AO PROCEDIMENTO DE HETEROIDENTIFICAÇÃO COMPLEMENTAR',
  'RECURSO QUANTO AO PROCEDIMENTO DE HETEROIDENTIFICAÇÃO COMPLEMENTAR',
  'E DO PROCEDIMENTO DE HETEROIDENTIFICAÇÃO COMPLEMENTAR'],
 'SOLUCOES SERVICOS DE LOCACAO DE MAQUINAS E EQUIPAMENTO': ['SOLUCOES SERVICOS DE LOCACAO DE MAQUINAS E EQUIPAMENTO',
  'SOLUCOES SERVICOS DE LOCACAO DE MAQUINAS E EQUIPAMENTOS PARA ESCRITORIO LTDA'],
 'COOPERATIVA DE AGRICULTORES E AGROINDUSTRIAS FAMILIARES': ['COOPERATIVA DE AGRICULTORES E AGROINDUSTRIAS FAMILIARES E CAXIAS DO SUL LTDA',
  'COOPERATIVA DE AGRICULTORES E AGROINDÚSTRIAS FAMILIARES DE CAXIAS DO SUL',
  'COOPERATIVA DE AGRICULTORES E AGROINDUSTRIAS FAMILIARES'],
 'COOPERATIVA AGROINDUSTRIAL DA AGRICULTURA FAMILIAR DO TERRITÓRIO ENTRE RIOS': ['COOPERATIVA AGROINDUSTRIAL DA AGRICULTURA FAMILIAR DO TERRITÓRIO ENTRE RIOS',
  'COOPERATIVA AGROINDUSTRIAL DA AGRICULTURA FAMILIAR DO TERRITORIO ENTRE RIOS'],
 'EDITAL DE NOTIFICAÇÃO\nCENTRO DE INTENDÊNCIA DA MARINHA EM PARADA DE LUCAS': ['EDITAL DE NOTIFICAÇÃO\nO CENTRO DE INTENDÊNCIA DA MARINHA EM PARADA DE LUCAS',
  'EDITAL DE NOTIFICAÇÃO\nCENTRO DE INTENDÊNCIA DA MARINHA EM PARADA DE LUCAS'],
 'EDITAL DE INTIMAÇÃO\nO ORDEN': ['EDITAL DE INTIMAÇÃO\nO ORDENADOR DE DESPESAS DA BASE AÉREA DE NATAL',
  'EDITAL DE INTIMAÇÃO\nO ORDENADORA DE DESPESAS DA BASE AÉREA DE NATAL',
  'EDITAL DE INTIMAÇÃO\nO ORDENADOR DE DESPESAS DO GRUPAMENTO DE APOIO DE NATAL',
  'O ORDENADOR DE DESPESAS DO GRUPAMENTO DE APOIO DE NATAL'],
 'VALDANHA ROMERO COMERCIO E REPRESENTACAO DE EQUIPAMENTO': ['VALDANHA ROMERO COMERCIO E REPRESENTACAO DE EQUIPAMENTO',
  'VALDANHA ROMERO COMERCIO E REPRESENTACAO DE EQUIPAMENTOS FRIGORIFICOS LTDA'],
 'COOPERATIVA DOS MEDICOS ANESTESIOLOGISTAS DO ESTADO D': ['COOPERATIVA DOS MEDICOS ANESTESIOLOGISTAS DO ESTADO DE MATO GROSSO',
  'COOPERATIVA DOS MEDICOS ANESTESIOLOGISTAS DO ESTADO DO RIO GRANDE',
  'COOPERATIVA DOS MEDICOS ANESTESIOLOGISTASDO ESTADO DO RIO GRANDE',
  'COOPERATIVA DOS MÉDICOS ANESTESIOLOGISTAS DO ESTADO DO RIO GRANDE DO NORTE'],
 'AVISO DE INEXIGIBILIDADE DE LICITAÇÃO\nO GRUPAMENTO DE APOIO ': ['AVISO DE INEXIGIBILIDADE DE LICITAÇÃO\nO GRUPAMENTO DE APOIO LOGÍSTICO',
  'AVISO DE INEXIGIBILIDADE DE LICITAÇÃO\nO GRUPAMENTO DE APOIO DE LAGOA SANTA'],
 'COOPERATIVA MISTA DOS PRODUTORES RURAIS NA AGRICULTURA': ['COOPERATIVA MISTA DOS PRODUTORES RURAIS NA AGRICULTURA',
  'COOPERATIVA MISTA DOS PRODUTORES RURAIS NA AGRICULTURA FAMILIAR DA PARAIBA'],
 'MARIMAX COMERCIO E IMPORTACAO DE PRODUTOS PARA SAUDE E': ['MARIMAX COMERCIO E IMPORTACAO DE PRODUTOS PARA SAUDE E',
  'MARIMAX COMERCIO E IMPORTACAO DE PRODUTOS PARA SAUDE E VETERINARIOS EIRELI'],
 'PARTE\nASPECTOS AVALIADOS\nPONTOS DEBITADOS POR ERRO COMETIDO\nI\nEXPRESSÃO\nP': ['PARTES\nASPECTOS AVALIADOS\nPONTOS DEBITADOS POR ERRO COMETIDO\nI\nEXPRESSÃO\nP',
  'PARTE\nASPECTOS AVALIADOS\nPONTOS DEBITADOS POR ERRO COMETIDO\nI\nEXPRESSÃO\nP'],
 'MEGA COMERCIO ATACADISTA DE ROUPAS E ACESSORIOS PARA US': ['MEGA COMERCIO ATACADISTA DE ROUPAS E ACESSORIOS PARA USO PROFISSIONAL LTDA',
  'MEGA COMERCIO ATACADISTA DE ROUPAS E ACESSORIOS PARA US'],
 'COOPERATIVA DA AGRICULTURA FAMILIAR E ECONOMIA SOLIDÁRIA DE PIND': ['COOPERATIVAS DA AGRICULTURA FAMILIAR E ECONOMIA SOLIDARIA DO POTENGI CNPJ',
  'COOPERATIVA DA AGRICULTURA FAMILIAR E ECONOMIA SOLIDÁRIA DE PINDORETAMA'],
 'QUALITY LUX COMERCIO E INDUSTRIA DE MATERIAIS ': ['QUALITY LUX COMERCIO E INDUSTRIA DE MATERIAIS ELETRICOS E ILUMINACAO LTDA',
  'A ILUMINADA COMERCIO E SERVICOS DE MATERIAIS ELETRICOS E ILUMINACAO LTDA',
  'QUALITY LUX COMERCIO E INDUSTRIA DE MATERIAIS ELETRICO'],
 'IO E DISTRIBUICAO DE PRODUTOS HOSPITALARES LTDA CNPJ': ['TOTAL MED COMERCIO E IMPORTACAO DE PRODUTOS MEDICO HOSPITALARES LTDA CNPJ',
  'MED COMERCIO E DISTRIBUICAO DE PRODUTOS HOSPITALARES LTDA CNPJ'],

In [58]:
test_key = list(maybe_matches.keys())[0]
test_value = maybe_matches[test_key][0]

print(test_key, test_value, sep='\n')

PROGRAMA E BIBLIOGRAFIA PARA A PROVA ESCRITA DE CONHECIMENTOS PROFISSIONAIS PARA O CONCURSO PÚBLICO DE ADMISSÃO AO CURSO DE FORMAÇÃO PARA O INGRESSO NO CORPO AUXILIAR DE PRAÇAS DA MARINHA
DE CONHECIMENTOS PROFISSIONAIS PARA O CONCURSO PÚBLICO DE ADMISSÃO AO CURSO DE FORMAÇÃO PARA O INGRESSO NO CORPO AUXILIAR DE PRAÇAS DA MARINHA

In [59]:
align = rapidfuzz_fuzz.partial_ratio_alignment(min(test_key, test_value, key=len), max(test_key, test_value, key=len))

In [60]:
min(test_key, test_value, key=len)[align.dest_start:align.dest_end]

'O PÚBLICO DE ADMISSÃO AO CURSO DE FORMAÇÃO PARA O INGRESSO NO CORPO AUXILIAR DE PRAÇAS DA MARINHA'

In [61]:
min(test_key, test_value, key=len)

'DE CONHECIMENTOS PROFISSIONAIS PARA O CONCURSO PÚBLICO DE ADMISSÃO AO CURSO DE FORMAÇÃO PARA O INGRESSO NO CORPO AUXILIAR DE PRAÇAS DA MARINHA'

In [62]:
find_substring(test_key, maybe_matches[test_key])

{'MARINHA': ['DE CONHECIMENTOS PROFISSIONAIS PARA O CONCURSO PÚBLICO DE ADMISSÃO AO CURSO DE FORMAÇÃO PARA O INGRESSO NO CORPO AUXILIAR DE PRAÇAS DA MARINHA',
  'PROGRAMA E BIBLIOGRAFIA PARA A PROVA ESCRITA DE CONHECIMENTOS PROFISSIONAIS PARA O CONCURSO PÚBLICO DE ADMISSÃO AO CURSO DE FORMAÇÃO PARA O INGRESSO NO CORPO AUXILIAR DE PRAÇAS DA MARINHA']}

In [63]:
all_keys = list(maybe_matches.keys())

for key in all_keys:

_IncompleteInputError: incomplete input (1631670437.py, line 4)