In [13]:
import numpy as np
import polars as pl
from rapidfuzz import fuzz as rapidfuzz_fuzz, process

In [2]:
textos = pl.read_parquet('../database/textos/*.parquet').select('id', 'texto')

In [3]:
VALOR_PATTERN = r'R\$\s?(?:\d{1,3}(?:\.\d{3})*|\d+)(?:,\d{2})?'
ENT_PATTERN = r'[A-ZÁÂÃÉÊÍÓÔÕÚÇ]+\s[A-ZÁÂÃÉÊÍÓÔÕÚÇ\s]+'
PROCESSO_PATTERN = r'\b\d{5}\.?\d{6}\/?\d{4}\-?\d{2}\b'
CNPJ_PATTERN = r'\b\d{2}\.?\d{3}\.?\d{3}\/?\d{4}\-?\d{2}\b'
DATA_PATTERN = r'\b\d{1,2}/\d{1,2}/\d{2,4}\b|\b\d{1,2}\s+de\s+[a-zçãõáéíóúâêô]+\s+de\s+\d{4}\b'

In [4]:
def filter_nested_entities(items):
    if items is None:
        return []

    normalized_items = [item.strip() for item in items if item and item.strip()]

    return [
        item
        for item in normalized_items
        if not any(item != other and item in other for other in normalized_items)
    ]

textos = textos.with_columns(
    valores=pl.col('texto').str.extract_all(VALOR_PATTERN),
    entidades=pl.col('texto').str.extract_all(ENT_PATTERN).map_elements(
        filter_nested_entities,
        return_dtype=pl.List(pl.String)
    ),
    nups=pl.col('texto').str.extract_all(PROCESSO_PATTERN),
    cnpjs=pl.col('texto').str.extract_all(CNPJ_PATTERN),
    datas=pl.col('texto').str.to_lowercase().str.extract_all(DATA_PATTERN)
)

In [5]:
textos

shape: (1_262_498, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ id           ┆ texto       ┆ valores     ┆ entidades   ┆ nups        ┆ cnpjs       ┆ datas       │
│ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ str          ┆ str         ┆ list[str]   ┆ list[str]   ┆ list[str]   ┆ list[str]   ┆ list[str]   │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 12002010442  ┆ PORTARIA    ┆ []          ┆ ["PORTARIA  ┆ []          ┆ []          ┆ ["26 de     │
│              ┆ DAC Nº      ┆             ┆ DAC N", "DE ┆             ┆             ┆ dezembro de │
│              ┆ 1.747/SIE,  ┆             ┆ DEZEMBR…    ┆             ┆             ┆ 2001", "21… │
│              ┆ DE …        ┆             ┆             ┆             ┆             ┆             │
│ 12002010443  ┆ PORTARIA    ┆ []          ┆ ["PORTARIA  ┆ []          ┆ []          ┆ ["26 de     │
│              ┆ DAC Nº      ┆             ┆ DAC N", "DE ┆             ┆             ┆ dezembro de │
│              ┆ 1.748/SIE,  ┆             ┆ DEZEMBR…    ┆             ┆             ┆ 2001", "21… │
│              ┆ DE …        ┆             ┆             ┆             ┆             ┆             │
│ 12002010444  ┆ PORTARIA    ┆ []          ┆ ["PORTARIA  ┆ []          ┆ []          ┆ ["26 de     │
│              ┆ DAC Nº      ┆             ┆ DAC N", "DE ┆             ┆             ┆ dezembro de │
│              ┆ 1.749/SIE,  ┆             ┆ DEZEMBR…    ┆             ┆             ┆ 2001", "21… │
│              ┆ DE …        ┆             ┆             ┆             ┆             ┆             │
│ 12002010445  ┆ PORTARIA Nº ┆ []          ┆ ["PORTARIA  ┆ []          ┆ []          ┆ ["27 de     │
│              ┆ 45/DAdM, DE ┆             ┆ N", "DE     ┆             ┆             ┆ dezembro de │
│              ┆ 27 DE …     ┆             ┆ DEZEMBRO    ┆             ┆             ┆ 2001", "25… │
│              ┆             ┆             ┆ DE…         ┆             ┆             ┆             │
│ 12002010746  ┆ PORTARIA    ┆ []          ┆ ["PORTARIA  ┆ []          ┆ []          ┆ ["3 de      │
│              ┆ INTERMINIST ┆             ┆ INTERMINIST ┆             ┆             ┆ janeiro de  │
│              ┆ ERIAL Nº 2… ┆             ┆ ERIAL N"…   ┆             ┆             ┆ 2002", "11  │
│              ┆             ┆             ┆             ┆             ┆             ┆ d…          │
│ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           │
│ 530_20251231 ┆ EXTRATO DE  ┆ ["R$ 151.06 ┆ ["EXTRATO   ┆ ["63064.010 ┆ ["08.242.47 ┆ ["15/12/202 │
│ _23469728    ┆ CREDENCIAME ┆ 2,00"]      ┆ DE CREDENCI ┆ 971/2023-38 ┆ 1/0001-18"] ┆ 5", "14/12/ │
│              ┆ NTO Nº 3…   ┆             ┆ AMENTO N"…  ┆ "]          ┆             ┆ 2026", ……   │
│ 530_20251231 ┆ EXTRATO DE  ┆ ["R$        ┆ ["EXTRATO   ┆ ["63064.010 ┆ ["60.143.97 ┆ ["15/12/202 │
│ _23470217    ┆ CREDENCIAME ┆ 20.000,00"] ┆ DE CREDENCI ┆ 971/2023-38 ┆ 2/0001-67"] ┆ 5", "14/12/ │
│              ┆ NTO Nº 3…   ┆             ┆ AMENTO N"…  ┆ "]          ┆             ┆ 2026", ……   │
│ 530_20251231 ┆ EXTRATO DE  ┆ ["R$        ┆ ["EXTRATO   ┆ ["63064.010 ┆ ["70.030.60 ┆ ["09/12/202 │
│ _23470438    ┆ CREDENCIAME ┆ 20.000,00"] ┆ DE CREDENCI ┆ 971/2023-38 ┆ 6/0001-55"] ┆ 5", "08/12/ │
│              ┆ NTO Nº 2…   ┆             ┆ AMENTO N"…  ┆ "]          ┆             ┆ 2026", ……   │
│ 530_20251231 ┆ EXTRATO DE  ┆ ["R$        ┆ ["EXTRATO   ┆ ["63064.010 ┆ []          ┆ ["10/12/202 │
│ _23470552    ┆ CREDENCIAME ┆ 5.000,00"]  ┆ DE CREDENCI ┆ 971/2023-38 ┆             ┆ 5", "09/12/ │
│              ┆ NTO Nº 3…   ┆             ┆ AMENTO N"…  ┆ "]          ┆             ┆ 2026", ……   │
│ 530_20251231 ┆ EXTRATO DE  ┆ ["R$        ┆ ["EXTRATO   ┆ ["63064.010 ┆ []          ┆ ["15/12/202 │
│ _23470580    ┆ CREDENCIAME ┆ 20.000,00"] ┆ DE CREDENCI ┆ 971/2023-38 ┆             ┆ 5", "14/12/ │
│              ┆ NTO Nº 3…   ┆             ┆ AMENTO N"…  ┆ "]          ┆             ┆ 2026", ……   │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [6]:
print(textos.filter(pl.col('valores').list.len() > 0).item(6, 'texto'))

PORTARIA Nº 739/MD, DE 26 DE NOVEMBRO DE 2001
O MINISTRO DE ESTADO DA DEFESA, no uso da atribuição que lhe é conferida pelo art. 87, inciso IV, da Constituição Federal e da delegação de competência de trata o art. 1º do Decreto nº 3.439, de 25 de abril de 2000, tendo em vista o que consta dos processos nº 07-01/95218/00 - DAC e 60041.000029/01-19 - MD, resolve:
Art. 1º Fica concedida autorização à TRANSPORTES AÉREOS MERCANTILES PANAMERICANOS S.A., que poderá usar em sua razão social TAMPA S.A., com sede na cidade de Medellín, Colômbia, para funcionar no Brasil como empresa de transporte aéreo internacional regular de carga.
Art. 2º Ficam ainda estabelecidas as seguintes obrigações:
I - a TAMPA S.A. é obrigada a ter, permanentemente, um representante legal no Brasil, com plenos e ilimitados poderes para tratar e, definitivamente, resolver as questões que venham a surgir, quer com o Governo, quer com particulares, podendo ser demandado e receber citação inicial pela sociedade;
II - todos os atos praticados no Brasil ficarão sujeitos unicamente às respectivas leis e tribunais brasileiros, sem que, em tempo algum, possa a referida empresa reclamar qualquer exceção, fundada em seus estatutos;
III - a sociedade não poderá realizar, no Brasil, atividades constantes de seus estatutos, que são vedados às sociedades estrangeiras, e somente poderá exercer as que dependam de aprovação prévia de órgão governamental, depois de obtida esta e sob as condições autorizadas; IV - qualquer alteração que a empresa fizer em seus atos constitutivos ou estatuto, dependerá de aprovação do Governo Federal para produzir efeitos no Brasil; V - ser-lhe-á cassada a autorização para funcionamento no Brasil se vier a infringir as cláusulas anteriores ou se, a juízo do Governo brasileiro, a empresa exercer atividades contrárias ao interesse público; e
IV - em caso de transgressão de qualquer das cláusulas para qual não exista cominação especial, será a empresa punida com as multas estabelecidas pela legislação interna.
Art. 3º O exercício efetivo de qualquer atividade da TAMPA S.A. no Brasil, relacionada com os serviços objeto desta autorização, fica sujeito à legislação brasileira, em especial ao Código Brasileiro de Aeronáutica, respeitados os Acordos Internacionais, dos quais o Brasil seja signatário.
Art. 4º Esta Portaria entra em vigor na data de sua publicação.
GERALDO MAGELA DA CRUZ QUINTÃO
(Nº 29292 - 16/1/2002 - R$ 9.454,72)
ANEXO

In [7]:
print(textos.item(1, 'texto'))

PORTARIA DAC Nº 1.748/SIE, DE 26 DE DEZEMBRO DE 2001
Autoriza a empresa FREE HANDLING SERVIÇOS AUXILIARES DE TRANS-
PORTES AÉREOS LTDA a executar serviços auxiliares de transporte aéreo nos aeroportos brasileiros.
O CHEFE DO SUBDEPARTAMENTO DE INFRA-ESTRUTURA DO DEPARTAMENTO DE AVIAÇÃO CIVIL, no uso da delegação de competência outorgada pela Portaria DAC Nº 1727/DGAC, de 21 de dezembro de 2001, e de acordo com o art. 1º e 7º da Portaria nº 467/GM-5, de 3 de junho de 1993, e com fundamento no art. 102 da Lei nº 7565, de 19 de dezembro de 1986, que dispõe sobre o Código Brasileiro de Aeronáutica, resolve:
Art. 1º Autorizar a empresa FREE HANDLING SERVIÇOS AUXILIARES DE TRANSPORTES AÉREOS LTDA, sediada na cidade de São Paulo, para executar serviços auxiliares de transporte aéreo, nos aeroportos brasileiros, denominados Serviços Operacionais, discriminados no subitem 2.1 da Instrução de Aviação Civil IAC 2301-0899, aprovada pela Portaria nº 533/DGAC, de 12 de agosto de 1999, publicada no Diário Oficial da União nº 160, de 20 de agosto de 1999.
Art. 2º A empresa ora autorizada se compromete por si e seus prepostos, sob pena de revogação desta Portaria:
a) não transferir seu controle acionário ou parte de seu capital à pessoa física ou jurídica, sem prévia autorização do DAC; e
b) informar, a cada período de 6 meses, o aeroporto onde está operando.
Art. 3º Para operar em qualquer aeroporto brasileiro, a empresa deverá atender às disposições contidas na IAC supracitada.
Art. 4º Esta Portaria entra em vigor na data de sua publicação, no Diário Oficial da União.
Cel. Eng. ALLEMANDER JESUS PEREIRA FILHO

In [8]:
textos.item(1,  'entidades')

shape: (6,)
Series: '' [str]
[
	"PORTARIA DAC N"
	"DE DEZEMBRO DE"
	"O CHEFE DO SUBDEPARTAMENTO DE …
	"ESTRUTURA DO DEPARTAMENTO DE A…
	"FREE HANDLING SERVIÇOS AUXILIA…
	"ALLEMANDER JESUS PEREIRA FILHO"
]

In [9]:
contagem_entidades = {}

for i in range(textos.height):
    for entidade in textos.item(i, 'entidades'):
        if entidade not in contagem_entidades:
            contagem_entidades[entidade] = 1
        else:
            contagem_entidades[entidade] += 1

In [10]:
contagem_entidades

{'PORTARIA DAC N': 1907,
 'DE DEZEMBRO DE': 20205,
 'JET SERVICE COMERCIAL LTDA': 2,
 'O CHEFE DO SUBDEPARTAMENTO DE INFRA': 1599,
 'ESTRUTURA DO DEPARTAMENTO DE AVIAÇÃO CIVIL': 1595,
 'ALLEMANDER JESUS PEREIRA FILHO': 1121,
 'FREE HANDLING SERVIÇOS AUXILIARES DE TRANSPORTES AÉREOS LTDA': 2,
 'SANPRESS SERVIÇOS AUXILIARES DO TRANSPORTE\nAÉREO LTDA': 1,
 'SANPRESS SERVIÇOS AUXILIARES DO TRANSPORTE AÉREO LTDA': 2,
 'PORTARIA N': 153949,
 'O DIRETOR DE ADMINISTRAÇÃO DA MARINHA': 537,
 'V A': 10346,
 'ADOLF MAGNUS MONIZ OSTWALD': 8,
 'PORTARIA INTERMINISTERIAL N': 180,
 'DE JANEIRO DE': 20544,
 'OS MINISTROS DE ESTADO DO PLANEJAMENTO': 25,
 'ORÇAMENTO E GESTÃO': 3150,
 'DA FAZENDA E DA DEFESA': 3,
 'MARTUS TAVARES M': 2,
 'PEDRO MALAN\nM': 1,
 'GERALDO MAGELA DA CRUZ QUINTÃO\nM': 5,
 'ANEXO\nEMPRESA BRASILEIRA DE AERONÁUTICA S': 2,
 'EMBRAER\nPROCESSO INTERESSADO PROCESSO ANTERIOR': 1,
 'EDISON BOTOSSI CARDOSO': 1,
 'RONEY JOSE FERREIRA': 1,
 'O DIRETOR DO CENTRO TECNOLÓGICO DA MARINHA EM SÃO PAULO': 118,
 'AVALIAÇÃO DE DESEMPENHO ADMINISTRATIVO': 1,
 'MARCUS VINICIUS OLIVEIRA DOS SANTOS': 100,
 'O COMANDANTE DA AERONÁUTICA': 19808,
 'CARLOS DE ALMEIDA BAPTISTA\nANEXO I\nR': 3,
 'ANEXO II\nR': 11,
 'O DIRETOR': 5570,
 'GERAL DO DEPARTAMENTO DE AVIAÇÃO CIVIL': 436,
 'O A': 1376,
 'O E': 13817,
 'VENANCIO GROSSI': 58,
 'MASTER FREIGHT TRANSPORTES INTERNACIONAIS LTDA': 9,
 'A E': 6573,
 'FRANCISCO MOACIR FARIAS MESQUITA': 22,
 'JC AIRLINES LOGÍSTICA LTDA': 2,
 'AYRES CARGAS AÉREAS S': 2,
 'C LTDA': 2853,
 'SERVICE FREIGHT DO BRASIL LTDA': 3,
 'EMBASSY FREIGHT RIO DE JANEIRO LTDA': 2,
 'SERVIMEX LOGÍSTICA LTDA': 4,
 'SERVIMEX LOGÍTICA LTDA': 1,
 'SAN ASSESSORIA E COMÉRCIO EXTERIOR LTDA': 1,
 'WORLD LINE TRANSPORTES INTERNACIONAIS LTDA': 2,
 'WORLD LINE FREIGHT\nFORWARDER': 1,
 'WORLD LINE FREIGHT FORWARDER': 1,
 'GTI LOGÍSTICA E TRANSPORTES LTDA': 1,
 'O MINISTRO DE ESTADO DA DEFESA': 16212,
 'GERALDO MAGELA DA CRUZ QUINTÃO\nMINISTÉRIO DA DEFESA SECRETARIA DE ORGANIZAÇÃO INSTITUCIONAL\nLIMITES PARA MOVIMENTAÇÃO E EMPENHO RELATIVOS A DOTAÇÕES CONSTANTES DA LEI ORÇAMENTÁRIA PARA': 1,
 'REFERENTES AO ANEXO I DA PORTARIA N': 1,
 'DE FEVEREIRO DE': 19902,
 'REFERENTES AO ANEXO II DA PORTARIA N': 1,
 'MINISTÉRIO DA DEFESA\nSECRETARIA DE ORGANIZAÇÃO INSTITUCIONAL\nLIMITES PARA PAGAMENTOS RELATIVOS A DOTAÇÕES CONSTANTES DA LEI ORÇAMENTÁRIA PARA': 1,
 'E AOS RESTOS A PAGAR DE': 23,
 'REFERENTES AO ANEXO IV DA\nPORTARIA N': 1,
 'ANEXO III': 577,
 'MINISTÉRIO DA DEFESA SECRETARIA DE ORGANIZAÇÃO INSTITUCIONAL\nLIMITES PARA PAGAMENTOS RELATIVOS A DOTAÇÕES CONSTANTES DA LEI ORÇAMENTÁRIA PARA': 1,
 'REFERENTES AO ANEXO V DA\nPORTARIA N': 1,
 'MINISTÉRIO DA DEFESA SECRETARIA DE ORGANIZAÇÃO INSTITUCIONAL\nLIMITES PARA PAGAMENTOS RELATIVOS A DOTAÇÕES CONSTANTES DA LEI ORÇAMENTÁRIAS PARA': 1,
 'REFERENTES AO ANEXO VI DA\nPORTARIA N': 1,
 'DE OUTUBRO DE': 20025,
 'O CHEFE DO SUBDEPARTAMENTO DE PLANEJAMENTO DO DEPARTAMENTO DE AVIAÇÃO CIVIL': 960,
 'CARLOS ALBERTO DE CARVALHO FAGUNDES': 22,
 'O CONVICE': 3,
 'CARLOS DE ALMEIDA BAPTISTA': 350,
 'CINDACTA I': 4280,
 'REGULAMENTO DO DEPARTAMENTO DE CONTROLE DO ESPAÇO AÉREO\nPRIMEIRA PARTE\nD': 1,
 'CAPÍTULO I\nF': 7,
 'O DECEA': 54,
 'CAPÍTULO II\nA': 11,
 'SEGUNDA PARTE\nE': 6,
 'CAPÍTULO I\nE': 8,
 'CAPITULO II\nA': 1,
 'A V': 562,
 'O S': 2610,
 'CAPÍTULO III\nP': 6,
 'O V': 535,
 'O C': 10442,
 'TERCEIRA PARTE\nD': 6,
 'CAPÍTULO I\nD': 23,
 'CAPÍTULO II\nD': 35,
 'PORTARIA NO': 630,
 'EXPRESSO MERCÚRIO S': 4,
 'DE NOVEMBRO DE': 19935,
 'DINAR LÍNEAS AÉREAS SOCIEDAD ANÓNIMA': 3,
 'GERALDO MAGELA DA CRUZ QUINTÃO': 246,
 'TRADUÇÃO N': 41,
 'CLÁUDIA GENI FRANKE': 7,
 'ABM B': 1,
 'DINAR LÍNEAS AÉREAS S': 1,
 'CLÁUDIO CABRAL UCHOA REZENDE': 2,
 'ATA REGISTRADA EM CARTÓRIO': 7,
 'ANDRÉS JULIO DESIMONE': 1,
 'DINAR LINEAS AEREAS SOCIEDAD ANONIMA': 1,
 'O COLÉGIO DE ESCRIVÃES': 2,
 'SANTA CATARINA': 52,
 'PRIMEIRO TRASLADO': 17,
 'ESCRITURA NÚMERO CENTO E QUARENTA E SEIS': 1,
 'ANDRES JULIO DESIMONE': 5,
 'JULIO EMILIO RUIZ DE LOS LLANOS': 5,
 'MIGUEL ANGEL DESIMONE': 4,
 'ALBERTO ALEJANDRO DESIMONE': 4,
 'DINAR SOCIEDAD DE RESPONSABILIDAD LIMITADA CAMBIO': 3,
 'BOLSA Y TURISMO': 3,
 'DINAR LÍNEAS AÉREAS SOCIEDAD ANONIMA': 4,
 'DOIS BILHÕES E QUINHENTOS MILHÕES DE AUSTRAIS': 2,
 'ADRIAN JOSE LUIS MARTINI': 1,
 'CARLOS RAFAEL MORALES MIY': 1,
 'CARLOS ARTURO ULIVARRI': 3,
 'SILVIA ADRIANA TONCOVICH': 2,
 'DOLLY STELLA ARANDA': 1,
 'ARTIGO PRIMEIRO': 4,
 'ARTIGO SEGUNDO': 4,
 'ARTIGO TERCEIRO DURAÇÃO': 1,
 'ARTIGO QUARTO': 7,
 'ARTIGO QUINTO': 6,
 'CAPITAL SOCIAL': 4,
 'UM MILHÃO DE AUSTRAIS': 1,
 'ARTIGO SEXTO': 4,
 'ARTIGO SÉTIMO': 4,
 'EMISSÃO COM PRÊMIO': 1,
 'ARTIGO OITAVO': 7,
 'FORMALIDADES DOS TÍTULOS E CERTIFICADOS PROVISÓRIOS': 1,
 'ARTIGO NONO': 5,
 'SUBSCRIÇÃO PREFERENCIAL': 1,
 'MORA NA INTEGRALIZAÇÃO DAS AÇÕES': 1,
 'ARTIGO DÉCIMO PRIMEIRO': 4,
 'VENDA DE AÇÕES': 1,
 'DIREITO DE PREFERÊNCIA': 1,
 'ARTIGO DÉCIMO SEGUNDO': 4,
 'BÔNUS DE PARTICIPAÇÃO': 1,
 'ARTIGO DÉCIMO TERCEIRO ADMINISTRAÇÃO E REPRESENTAÇÃO DA SOCIEDADE': 1,
 'ARTIGO DÉCIMO QUARTO': 4,
 'REMUNERAÇÃO DOS DIRETORES E FISCAIS': 1,
 'ARTIGO DÉCIMO QUINTO': 4,
 'FACULDADES DA DIRETORIA COMITÊ EXECUTIVO': 1,
 'ARTIGO DÉCIMO SEXTO FISCALIZAÇÃO': 1,
 'ARTIGO DÉCIMO SÉTIMO': 4,
 'ASSEMBLÉIA CONVOCAÇÃO': 1,
 'ARTIGO DÉCIMO OITAVO': 4,
 'EXERCÍCIO ECONÔMICO FINANCEIRO': 1,
 'ARTIGO DÉCIMO NONO': 4,
 'DISSOLUÇÃO E LIQUIDAÇÃO': 2,
 'DESIMONE A': 2,
 'A  N': 1,
 'ESCRITURA NÚMERO CENTO E SETENTA E CINCO': 1,
 'ALTERAÇÃO DE CONTRATO DE CONSTITUIÇÃO DE SOCIEDADE': 1,
 'A F': 734,
 'DEL MONTE': 4,
 'DINAR LINEAS AÉREAS S': 1,
 'ATA DE ASSEMBLÉIA': 2,
 'ATAS DE DIRETORIA N': 1,
 'DINAR LINEAS AEREAS S': 1,
 'O D': 415,
 'DOCUMENTO DE CONCESSÃO PARA EXPLORAÇÃO DE SERVIÇOS': 1,
 'BUENOS AIRES': 15,
 'REPÚBLICA ARGENTINA': 27,
 'SÃO PAULO': 2382,
 'REPÚBLICA FEDERATIVA DO BRASIL': 15,
 'RIO DE JANEIRO': 32551,
 'PUNTA DEL ESTE': 3,
 'REPÚBLICA DO URUGUAI': 2,
 'SANTIAGO DO CHILE': 2,
 'REPÚBLICA DO CHILE': 2,
 'SANTA CRUZ DE LA SIERRA': 4,
 'REPÚBLICA DA BOLÍVIA': 4,
 'AEROLINEAS ARGENTINAS SOCIEDAD ANONIMA': 1,
 'DINAR LÍNEAS AEREAS SOCIEDAD ARGENTINA': 1,
 'O MINISTÉRIO DA ECONOMIA E OBRAS E SERVIÇOS PÚBLICOS RESOLVE': 1,
 'DINAR LÍNEAS AÉREAS SOCIEDAD ANÔNIMA': 2,
 'CENTO E OITENTA': 3,
 'FORÇA AÉREA ARGENTINA': 1,
 'COMANDO DE REGIÕES AÉREAS': 1,
 'DIREÇÃO NACIONAL DE TRANSPORTE AEROCOMERCIAL': 2,
 'SECRETARIA DE TRANSPORTE AEROCOMERCIAL': 2,
 'FLUVIAL E MARÍTIMO': 2,
 'SECRETARIA DE TRANSPORTES': 2,
 'SECRETARIA DE TANSPORTES': 1,
 'RESOLUÇÃO N': 1071,
 'DEMONSTRATIVO DA SITUAÇÃO PATRIMONIAL EM': 1,
 'BALANÇO\nDEMONSTRATIVO DE RESULTADOS DO EXERCÍCIO\nENCERRADO EM': 1,
 'BALANÇO\nDEMONSTRATIVO DA EVOLUÇÃO DO PATRIMÔNIO LÍQUIDO DO EXERCÍCIO ENCERRADO EM': 1,
 'DE\nDEZEMBRO DE': 1,
 'DINAR LÍNEAS AÉREAS SOCIEDAD ANONIMA\nE': 1,
 'A U': 4690,
 'COMANDANTE DA AERONÁUTICA': 12,
 'TRANSPORTES AÉREOS MERCANTILES PANAMERICANOS S': 2,
 'TAMPA S': 7,
 'LIVRO N': 20,
 'AUMENTO DE CAPITAL': 1,
 'TRANSPORTES AEREOS MERCANTILES PANAMERICANOS S': 4,
 'ESCRITURA N': 2,
 'DOIS MIL CENTO E QUARENTA E OITO': 1,
 'ANTONIO CAMPILLO VILLEGAS': 1,
 'DOIS MIL E CEM MILHÕES DE PESOS M': 1,
 'TRÊS MILHÕES DE PESOS M': 1,
 'SESSENTA MILHÕES DE AÇÕES': 1,
 'TRANSPORTES AEREOS MERCANTILES S': 1,
 'ARTIGO TERCEIRO': 4,
 'FINALIDADE SOCIAL': 1,
 'ARTIGO DÉCIMO': 1,
 'ARTIGO ONZE': 1,
 'ARTIGO DOZE': 1,
 'ARTIGO TREZE': 1,
 'ARTIGO CATORZE': 1,
 'ARTIGO QUINZE': 1,
 'DIREÇÃO E ADMINISTRAÇÃO': 1,
 'ARTIGO DEZESSEIS': 1,
 'ÓRGÃOS SOCIAIS': 1,
 'ASSEMBLÉIA GERAL\nDE ACIONISTAS': 1,
 'ARTIGO DEZESSETE': 1,
 'ARTIGO DEZOITO': 1,
 'ARTIGO DEZENOVE': 1,
 'ARTIGO VINTE E UM': 1,
 'REUNIÕES EXTRAORDINÁRIAS': 1,
 'ARTIGO VINTE E DOIS': 1,
 'QUORUM DELIBERATIVO': 1,
 'ARTIGO VINTE E TRÊS': 1,
 'ARTIGO VINTE EQUATRO': 1,
 'DIREITO AO VOTO': 1,
 'ARTIGO VINTE E CINCO': 1,
 'REGRAS SOBRE VOTAÇÕES': 1,
 'ARTIGO VINTE E SEIS': 1,
 'ARTIGO VINTE E SETE': 1,
 'FUNÇÕES DA ASSEMBLÉIA GERAL DE ACIONISTAS': 1,
 'ARTIGO\nVINTE E OITO': 1,
 'ARTIGO VINTE E NOVE': 1,
 'ARTIGO TRINTA E UM': 1,
 'FUNÇÕES DA JUNTA DIRETIVA': 1,
 'ARTIGO TRINTA E DOIS': 1,
 'ARTIGO TRINTA E TRÊS': 1,
 'ARTIGO TRINTA E QUATRO': 1,
 'ARTIGO TRINTA E CINCO': 1,
 'A R': 1329,
 'ARTIGO TRINTA E SEIS': 1,
 'ARTIGO TRINTA E SETE': 1,
 'FUNÇÕES DO REPRESENTANTE LEGAL': 1,
 'ARTIGO TRINTA E OITO': 1,
 'ARTIGO TRINTA E NOVE': 1,
 'QUALIDADE E REGIME LEGAL': 1,
 'FUNÇÕES DO REVISOR FISCAL': 1,
 'RESERVAS E DIVIDENDOS': 1,
 'ARTIGO QUARENTA E UM': 1,
 'ARTIGO QUARENTA E DOIS LUCROS': 1,
 'ARTIGO QUARENTA E TRÊS': 1,
 'DISTRIBUIÇÃO DE LUCROS': 1,
 'ARTIGO QUARENTA E QUATRO': 1,
 'A SOCIEDADE SE DISSOLVE': 1,
 'ARTIGO QUARENTA E CINCO': 1,
 'ARTIGO QUARENTA E SEIS': 1,
 'ARTIGO QUARENTA E SETE': 1,
 'ARTIGO QUARENTA E OITO': 1,
 'ARTIGO QUARENTA E NOVE': 1,
 'ARTIGO CINCOENTA': 1,
 'DEVERES DO SECRETÁRIO GERAL': 1,
 'LIDA PELOS QUE A ELA COMPARECERAM': 1,
 'NA CORRETA E EM SINAL DE APROVAÇÃO ASSINAM PERANTE MIM': 1,
 'O NOTÁRIO': 1,
 'QUE DOU FÉ': 1,
 'FOI ESCRITA CONFORME A MINUTA APRESENTADA': 1,
 'FOI ESCRITA NAS FOLHAS NOTARIAIS NÚMEROS': 1,
 'DIREITOS NOTARIAIS': 1,
 'QUE R': 2,
 'EM FÉ DO QUE': 10,
 'MANOEL ANTONIO SCHIMIDT': 6,
 'JUNTA DIRETIVA': 1,
 'TITULARESSUPLENTES A': 1,
 'OUTROS PRESENTES': 1,
 'DESENVOLVIMENTO DA REUNIÃO': 1,
 'VERIFICAÇÃO DO QUORUM': 1,
 'A S': 2019,
 'NOMEAÇÃO DE PRESIDENTE E SECRETÁRIO': 1,
 'LEITURA E APROVAÇÃO DA ATA ANTERIOR': 1,
 'AUTORIZAÇÕES E VÁRIOS': 1,
 'SUPERINTENDÊNCIA DE NOTARIADO E REGISTRO': 1,
 'EUNICE TAVARES DE CAMPOS': 8,
 'TRADUTORA PÚBLICA JURAMENTADA E INTÉRPRETE COMERCIAL': 5,
 'BALANÇOS GERAIS DE': 1,
 'DEMONSTRATIVOS DE RESULTADOS PARA OS ANOS FINDOS EM': 1,
 'EXPRESSOS EM MILHARES DE PESOS': 1,
 'POR TRADUÇÃO CONFORME': 23,
 'ATLAS AIR': 6,
 'DOCUMENTO N': 5,
 'EDUARDO ARTUR RODRIGUES SILVA': 6,
 'DAVID N': 5,
 'EUGENE DESSEL': 1,
 'LILY SOTO T': 1,
 'MINHA COMISSÃO VENCE EM': 4,
 'DEPARTAMENTO DE ESTADO': 5,
 'O SELO GRANDE DO ESTADO DA FLÓRIDA': 2,
 'EM DEUS ACREDITAMOS': 2,
 'OBSERVAÇÕES QUE APARECEM NAS BORDAS DESTE DOCUMENTO': 2,
 'VERTICAL E HORIZONTALMENTE': 2,
 'COMO SEGUE': 2,
 'NÃO ACEITE A MENOS QUE VISTA': 2,
 'GERAL DO BRASIL EM MIAMI': 2,
 'KATHERINE HARRIS': 3,
 'GERAL DA REPÚBLICA FEDERATIVA DO BRASIL': 2,
 'ARMANDO DE FRANÇA E SILVA': 5,
 'TRADUTOR PÚBLICO': 5,
 'TRADUÇÃO PÚBLICA JURAMENTADA': 4,
 'ESTADO DA FLÓRIDA': 2,
 'NÃO O ACEITE A MENOS QUE POSSA\nVÊ': 1,
 'JOHN BERNARDI': 2,
 'DIRETOR DE VENDAS': 1,
 'JOHN F': 1,
 'CONTRATO SOCIAL REFORMULADO DA ATLAS AIR': 1,
 'A D': 2063,
 'EM TESTEMUNHO DO QUE': 31,
 'RICHARD H': 1,
 'ESTADO DE DELAWARE': 1,
 'GABINETE DO SECRETÁRIO DE ESTADO': 1,
 'LILY SOTO': 2,
 'OUTROSSIM RESOLVIDO': 4,
 'BRIAN ROWE': 1,
 'ENDEREÇO EMBARQUE': 1,
 'IMPRIMIR NOME': 1,
 'TABELIÃ PÚBLICA DO ESTADO DA FLÓRIDA': 1,
 'O T': 995,
 'CONSULADOGERAL DO BRASIL EM MIAMI': 1,
 'E SUBSIDIÁRIAS': 5,
 'BALANÇOS PATRIMONIAIS CONSOLIDADOS': 1,
 'TOTAL PASSIVO E PATRIMÔNIO LÍQUIDO': 1,
 'AIR CANADA': 17,
 'ANEXO\nAIR CANADÁ': 1,
 'PROVÍNCIA DE QUEBEC': 1,
 'DISTRITO DE MONTREAL': 1,
 'CERTIFICADO NOTARIAL': 2,
 'PIERRE PAYMENT': 2,
 'PAUL LÉTOURNEAU': 3,
 'CÉLINE COMTOIS': 3,
 'JOHN M': 5,
 'LEI DE SOCIEDADES DO CANADÁ': 4,
 'ARTIGOS DE PRORROGAÇÃO': 1,
 'CAPITAL AUTORIZADO': 1,
 'AÇÕES ORDINÁRIAS': 1,
 'AÇÕES PREFERENCIAIS': 1,
 'A OC': 1,
 'SE UM NOME OU MUDANÇA DE NOME ESTIVER ENVOLVIDO': 1,
 'A SEGUINTE PRECAUÇÃO DEVE SER OBSERVADA': 1,
 'LEI DE SOCIEDADES DO CANADA': 1,
 'UAL C': 12,
 'CIBC M': 2,
 'PARA USO EXCLUSIVO DO DEPARTAMENTO': 2,
 'ESTATUTO SOCIAL N': 1,
 'FICA PROMULGADO': 1,
 'CLÁUSULA UM INTERPRETAÇÃO': 1,
 'DISPOSIÇÃO TRANSITÓRIA E': 1,
 'CONFLITO COM LEI OU ARTIGOS ESPECIAIS': 1,
 'CLÁUSULA DOIS': 1,
 'NEGÓCIOS DA EMPRESA': 1,
 'ESCRITÓRIO REGISTRADO': 1,
 'SELO EMPRESARIAL': 1,
 'EXERCÍCIO FINANCEIRO': 1,
 'AUTORIDADE DE COMPROMETIMENTO E ASSINATURA DE INSTRUMENTOS': 1,
 'ACORDOS BANCÁRIOS': 1,
 'PLANO EMPRESARIAL': 1,
 'CLÁUSULA TRÊS': 1,
 'NÚMERO DE DIRETORES E QUORUM': 1,
 'ELEIÇÃO E TERMOS C': 1,
 'DESTITUIÇÃO DE DIRETORES': 1,
 'VAGAS DE CARGOS': 1,
 'MAIORIA CANADENSE': 1,
 'REUNIÃO TELEFÔNICA': 1,
 'LOCAL DAS REUNIÕES': 1,
 'CONVOCAÇÃO DAS REUNIÕES': 1,
 'NOTIFICAÇÃO DE REUNIÃO': 1,
 'REUNIÃO ADIADA': 1,
 'REUNIÕES ORDINÁRIAS': 1,
 'VOTOS QUE REGEM AS QUESTÕES': 1,
 'CONFLITO DE INTERESSES': 2,
 'REMUNERAÇÃO E DESPESAS': 1,
 'CLÁUSULA QUATRO': 3,
 'COMITÊS DE DIRETORES': 1,
 'CONSELHO FISCAL': 11,
 'TRATAMENTO DE ASSUNTOS O': 1,
 'DISPENSA E VAGAS O': 1,
 'MANDATO DO CARGO': 1,
 'PRAZO DE VIGÊNCIA DO CARGO E REMUNERAÇÃO': 1,
 'NOTIFICAÇÃO DE RESCISÃO': 1,
 'SUSPENSÃO OU DEMISSÃO': 1,
 'AGENTES E ADVOGADOS': 1,
 'CLÁUSULA SEIS': 1,
 'PROTEÇÃO DE DIRETORES': 1,
 'ADMINISTRADORES E OUTROS': 1,
 'LIMITAÇÃO DE RESPONSABILIDADE': 1,
 'REGISTRO DE TRANSFERÊNCIAS O': 1,
 'DECLARAÇÕES ESTATUTÁRIAS P': 1,
 'AGENTES DE TRANSFERÊNCIA E ENCARREGADOS DE REGISTRO': 1,
 'NÃO RECONHECIMENTO DE FUNDOS DE FIDEICOMISSO': 1,
 'CAUTELAS DE AÇÕES': 1,
 'SUBSTITUIÇÃO DE CAUTELAS DE CERTIFICADO': 1,
 'ACIONISTAS CONJUNTOS S': 1,
 'ACIONISTAS FALECIDOS': 1,
 'CHEQUES DE DIVIDENDOS': 1,
 'NÃO RECEBIMENTO DE CHEQUES': 1,
 'DATA DE REGISTRO PARA DIVIDENDOS E DIREITOS': 1,
 'DIVIDENDOS NÃO RECLAMADOS Q': 1,
 'ASSEMBLÉIA DE ACIONISTAS': 1,
 'ASSEMBLÉIAS ANUAIS': 1,
 'ASSEMBLÉIAS EXTRAORDINÁRIAS': 1,
 'LUGAR DAS ASSEMBLÉIAS': 1,
 'NOTIFICAÇÃO DAS ASSEMBLÉIAS': 1,
 'LISTA DOS ACIONISTAS COM DIREITO': 1,
 'DATA DE REGISTRO PARA NOTIFICAÇÃO': 1,
 'ASSEMBLÉIAS SEM NOTIFICAÇÃO': 1,
 'SECRETÁRIO E ESCRUTINADORES': 1,
 'PESSOAS COM DIREITO A ESTAR PRESENTES': 1,
 'DIREITO A VOTO': 1,
 'TEMPO PARA APRESENTAÇÃO DE PROCURAÇÕES': 1,
 'VOTOS PARA APROVAÇÃO': 1,
 'CONTAGEM DE MÃOS O': 1,
 'SUBSIDIÁRIAS E OUTRAS EMPRESAS': 1,
 'DIVISÕES E DEPARTAMENTOS': 1,
 'CRIAÇÃO E CONSOLIDAÇÃO DE DIVISÕES': 1,
 'NOME DA DIVISÃO': 1,
 'ADMINISTRADORES DAS DIVISÕES': 1,
 'RESOLUÇÕES RELATIVAS': 2,
 'ADMINISTRAÇÃO E POSIÇÃO': 2,
 'MÉTODO PARA ENVIAR NOTIFICAÇÕES': 1,
 'NOTIFICAÇÃO PARA ACIONISTAS CONJUNTOS': 1,
 'CÁLCULO DO TEMPO': 1,
 'NOTIFICAÇÕES NÃO ENTREGUES': 1,
 'OMISSÕES E ERROS': 1,
 'PESSOAS COM DIREITO POR MORTE OU FORÇA DA LEI': 1,
 'CONTRAÇÃO DE EMPRÉSTIMOS': 1,
 'EMPRÉSTIMO DE PODERES': 1,
 'DATA DE VIGÊNCIA': 77,
 'VAGA DO CARGO': 1,
 'EXTRATO DE UMA RESOLUÇÃO APROVADA EM UMA REUNIÃO DO CONSELHO DE DIRETORES DA AIR CANADA R': 1,
 'EXTRATO DA ATA DE UMA REUNIÃO DO CONSELHO DE DIRETORES DA AIR CANADA': 1,
 'FICA RESOLVIDO QUE T': 1,
 'CERTIFICADO COMO LISTA CORRETA DOS ADMINISTRADORES DATADA EM SAINT': 1,
 'AUTORIDADES DELEGADAS PELO PRESIDENTE PARA': 1,
 'ADMINISTRADORES DA EMPRESA DE ACORDO COM O ESTATUTO N': 1,
 'AUTORIDADE PARA ASSUMIR COMPROMISSOS E TRATAR DE NEGÓCIOS': 1,
 'INSTRUMENTO DE PROCURAÇÃO': 1,
 'A OAB': 3,
 'PO B': 5,
 'NADA MAIS': 19,
 'DOU FÉ': 27,
 'ANTONIO ERNESTO PASQUALIN': 1,
 'CANADIAN AIRLINES INTERNATIONAL LTD': 6,
 'BALANÇO REALIZADO EM': 1,
 'DEMONSTRAÇÃO DO RESULTADO DO EXERCÍCIO DE': 1,
 'LUIZ VIRGILIO DE SIQUEIRA RUSSI': 1,
 'DOMINIO ASSESSORES LTDA': 1,
 'RONALDO HELENO DA SILVA': 1,
 'AEROFOTO CRUZEIRO S': 2,
 'AGRITEC AGRIMENSURA AEROFOTOGRAMETRIA S': 1,
 'MUHASE SERVIÇOS AUXILIARES DE TRANSPORTE AÉREO LTDA': 8,
 'PORTARIA DAC NO': 619,
 'ALX P': 2,
 'CARLOS ALBERTO DE\nCARVALHO FAGUNDES': 61,
 'JAT A': 1,
 'ESAT A': 2,
 'CONCLUSÃO\nA': 28,
 'VOTO\nO': 66,
 'IRAM SARAIVA M': 28,
 'ACÓRDÃO N': 49295,
 'WALTON ALENCAR RODRIGUES N': 5,
 'IRAM SARAIVA\nM': 48,
 'CRISTINA MACHADO DA COSTA E SILVA R': 20,
 'CÂMARA TC': 34,
 'PA\nR': 193,
 'TCU\nE': 46,
 'O M': 1856,
 'VOTO\nA': 157,
 'GRUPO II': 642,
 'BA INTERESSADO': 1,
 'VOTO\nE': 69,
 'DECISÃO N': 1667,
 'IRAM SARAIVA N': 13,
 'WALTON ALENCAR RODRIGUES\nM': 330,
 'MA EMBARGANTE': 1,
 'VOTO\nN': 50,
 'WALTON ALENCAR RODRIGUES M': 11,
 'CLASSE II': 194,
 'TCU P': 404,
 'PI R': 144,
 'PI J': 2,
 'ENGENHARIA CIVIL': 101,
 'VOTO\nC': 218,
 'PE RESPONSÁVEL': 1,
 'III ENECON': 1,
 'BA R': 209,
 'GUILHERME PALMEIRA M': 30,
 'GUILHERME PALMEIRA\nM': 544,
 'VOTO\nP': 157,
 'RELATÓRIO\nT': 1016,
 'AUGUSTO SHERMAN CAVALCANTI M': 7,
 'AUGUSTO SHERMAN CAVALCANTI\nM': 326,
 'PROPOSTA DE DECISÃO\nC': 25,
 'MARCOS BEMQUERER COSTA R': 23,
 'MARCOS BEMQUERER COSTA\nR': 898,
 'A P': 4383,
 'PROPOSTA DE DECISÃO\nA': 38,
 'CLASSE IV': 81,
 'FINEP I': 2,
 'RELATÓRIO E VOTO\nR': 4,
 'A SEFIP': 37,
 'CLASSE V': 277,
 'VOTO\nD': 74,
 'A C': 10749,
 'O P': 7434,
 'RELATÓRIO\nE': 119,
 'VOTO\nR': 113,
 'DE EZEMBRO DE': 1,
 'PROPOSTA DE DECISÃO\nP': 13,
 'LINCOLN MAGALHÃES DA ROCHA R': 24,
 'VALMIR CAMPELO P': 145,
 'LINCOLN MAGALHÃES DA ROCHA\nR': 208,
 'UBALDO ALVES CALDAS R': 32,
 'A TCE': 12,
 'CLÁUSULA OITAVA': 61,
 'IN STN': 375,
 'NÃO CONHECER': 3,
 'LHE PROVIMENTO': 15,
 'AFCE E': 3,
 'PROPOSTA DE DECISÃO\nF': 1,
 'ACORDÃO N': 22,
 'GRUPO I CLASSE II': 19,
 'PB R': 209,
 'RELATÓRIO E VOTO\nT': 28,
 'A L': 838,
 'VALMIR CAMPELO M': 40,
 'ADYLSON MOTTA N': 4,
 'VALMIR CAMPELO\nM': 134,
 'TO R': 92,
 'CONTROLE DE PAGAMENTO DO SIA': 1,
 'SESAU N': 1,
 'HOSPITAL ESTADUAL DE SÃO BENTO DO TOCANTINS': 1,
 'CEF RESPONSÁVEIS': 1,
 'BENJAMIN ZYMLER M': 25,
 'S P': 131,
 'BENJAMIN ZYMLER\nM': 218,
 'VOTO\nI': 64,
 'BENJAMIN ZYMLER R': 32,
 'HOSPITALMED U': 1,
 'HOSPITALMED LTDA': 1,
 'MARCOS VINÍCIOS VILAÇA': 2,
 'RELATÓRIO\nC': 266,
 'SUPERINTENDÊNCIA REGIONAL DO DEPARTAMENTO DE POLÍCIA FEDERAL': 1,
 'CLASSE III': 94,
 'A CEF': 20,
 'MET': 2,
 'I\nA': 51,
 'O IDAP': 3,
 'XV O': 1,
 'AUTOESP ULTIMA': 1,
 'XII A': 4,
 'XXVII J': 2,
 'ABACUS M': 3,
 'XXIV J': 1,
 'ADYLSON MOTTA M': 41,
 'ADYLSON MOTTA\nM': 322,
 'HFA I': 1,
 'RELATÓRIO GRUPO I': 4,
 'UBIRATAN AGUIAR M': 52,
 'MINISTRO UBIRATAN AGUIAR': 762,
 'UBIRATAN AGUIAR\nM': 424,
 'RS I': 98,
 'RJ I': 153,
 'RELATÓRIO\nA': 218,
 'CNEN I': 1,
 'O CHEFE DO SUBDEPARTAMENTO TÉCNICO DO DEPARTAMENTO DE AVIAÇÃO CIVIL': 255,
 'C C': 277,
 'CHE N': 47,
 'RENILSON RIBEIRO PEREIRA': 61,
 'MANUTENÇÃO E SERVIÇOS AUXILIARES DOS TRANSPORTES AÉREOS': 1,
 'MANUTENÇÃO E SERVIÇOS LTDA': 7,
 'STOPH CAR TAPEÇARIA LTDA': 2,
 'SP CEP': 72,
 'UTA BASE': 2,
 'BRASÍLIA AERONAVES E SERVIÇOS LTDA': 1,
 'O DIRETOR DE PORTOS E COSTAS': 2993,
 'NORMAS DA AUTORIDADE MARÍTIMA PARA O SERVIÇO DE PRATICAGEM': 7,
 'SALVADOR SIQUEIRA': 4,
 'EUCLIDES DUNCAN JANOT DE MATOS': 19,
 'GUSTAVO FONTENELLE MATIAS': 3,
 'IMDG C': 93,
 'EUCLIDES DUCAN JANOT DE MATOS': 1,
 'EXTRATO DA PAUTA N': 123,
 'RECURSOS E PEDIDOS DE REEXAME\nR': 1,
 'RS\nTC': 7,
 'MS\nR': 100,
 'AL\nI': 32,
 'MG\nI': 177,
 'TCU\nC': 5,
 'TOMADAS E PRESTAÇÕES DE CONTAS\nR': 3,
 'RO\nR': 72,
 'PE\nR': 373,
 'PB\nR': 211,
 'RN\nR': 196,
 'EG E': 5,
 'AUDITORIAS E OUTRAS MATÉRIAS CONCERNENTES': 7,
 'FISCALIZAÇÃO CONTÁBIL': 6,
 'OPERACIONAL E PAT R I M O N I A L': 1,
 'REFORMAS E PENSÕES\nR': 2,
 'SE\nI': 19,
 'II\nC': 119,
 'BNDESPAR\nR': 1,
 'MIGUEL VINÍCIUS DA SILVA S': 1,
 'ANEXO\nREGULAMENTO DO GABINETE DO COMANDANTE DA AERONÁUTICA\nPRIMEIRA PARTE\nD': 1,
 'O GABAER': 17,
 'CAPÍTULO II A': 4,
 'SEGUNDA PARTE E': 2,
 'A GCDA': 1,
 'A SCONT': 1,
 'CAPÍTULO III P': 2,
 'TERCEIRA PARTE D': 2,
 'CAPÍTULO II D': 4,
 'ANEXO\nREGULAMENTO DO ESTADO': 1,
 'MAIOR DA AERONÁUTICA\nPRIMEIRA PARTE\nD': 1,
 'O EMAER': 24,
 'O G': 2536,
 'O DAC': 26,
 'CARLOS DE ALMEIDA BAPTISTA\nANEXO': 3,
 'GERAL DO DEPARTAMENTO NACIONAL DE PRODUÇÃO MINERAL': 1,
 'DOU N': 1302,
 'O DNPM': 6,
 'O PL': 2,
 'O PCIAM': 2,
 'MARCELO RIBEIRO TUNES\nANEXO I\nNORMAS REGULADORAS DE MINERAÇÃO': 1,
 'NRM\nÍNDICE GERAL\nNRM': 1,
 'O PGR': 5,
 'N\nNRM': 1,
 'TOQUES TIPO DE TOQUE AÇÃO': 1,
 'ANEXO II\nQUADRO DE PRAZOS MÁXIMOS PARA CUMPRIMENTO DAS NRM': 1,
 'MÉTODO PARA O PLANEJAMENTO INSTITUCIONAL DA AERONÁUTICA': 1,
 'INMARSAT LIMITED': 2,
 'FLÁVIO DE OLIVEIRA LENCASTRE': 21,
 'ROCHA SERVIÇOS AÉREOS E RODOVIÁRIOS LTDA': 2,
 'ALLEMANDER JESUS PEREIRA FILHO\nI': 39,
 'STAR SERVIÇOS AEROPORTUÁRIOS LTDA': 37,
 'TÁXI AÉREO S': 1,
 'PETROBRÁS XXV': 4,
 'DADOS DO HELIPONTO': 85,
 'VFR D': 285,
 'ALLEMANDER J': 73,
 'PEREIRA FILHO\nI': 2,

In [11]:
contagem = pl.DataFrame(
    {
        'entidades': list(contagem_entidades.keys()),
        'contagem': list(contagem_entidades.values())
    }
).sort('contagem', descending=True)

In [ ]:
maybe_matches = {}
ents = contagem.get_column('entidades').to_list()

for i, ent in enumerate(ents[:-1]):
    print(i, end='\r')
    tail = ents[i + 1:]
    scores = process.cdist(
        [ent],
        tail,
        scorer=rapidfuzz_fuzz.ratio,
        score_cutoff=81,
        dtype=np.uint8,
        workers=-1,
    )[0]
    matches = [candidate for candidate, score in zip(tail, scores) if score > 80]
    if matches:
        maybe_matches[ent] = matches